package com.cnit.yoyo.dao.goods;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cnit.yoyo.autohome.model.AutohomeCarInfoDTO;
import com.cnit.yoyo.model.goods.Brand;

public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbggenerated Sat Mar 21 14:54:18 CST 2015
     */
    int deleteByPrimaryKey(Integer[] brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbggenerated Sat Mar 21 14:54:18 CST 2015
     */
    int insert(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbggenerated Sat Mar 21 14:54:18 CST 2015
     */
    int insertSelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbggenerated Sat Mar 21 14:54:18 CST 2015
     */
    Brand selectByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbggenerated Sat Mar 21 14:54:18 CST 2015
     */
    int updateByPrimaryKeySelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbggenerated Sat Mar 21 14:54:18 CST 2015
     */
    int updateByPrimaryKey(Brand record);
    
    
    List<Brand> findBrandList(Brand brand);
    
    int findBrandByName(Brand brand);
    
    /**
      * @description <b>查询汽车品牌</b>
      * @author 王鹏
      * @version 1.0.0
      * @data 2015-5-11
      * @param @return
      * @return List<Brand>
    */
    List<Brand> selectCarBrand(Map<String, Object> params);
    
    /**
     * @Title:  selectAllBrand  
     * @Description:  TODO(查询所有品牌)  
     * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
     * @date 2015-5-12 上午11:41:22  
     * @version 1.0.0 
     * @param @return
     * @return List<Brand>  返回类型 
     * @throws
     */
    List<Brand> selectAllBrand();
    
    List<Brand> selectByIds(Integer[] brandIds);
    
    /**
     * @description <b>查询包含商品的汽车品牌</b>
     * @author 王鹏
     * @version 1.0.0
     * @data 2015年7月30日
     * @param params
     * @return
     * List<Brand>
    */
    List<Brand> selectCarBrandHasGoods(Map<String, Object> params);

	List<Brand> selectCarBrandSpiderDataList(List<AutohomeCarInfoDTO> list);

	Brand selectCarBrandSpiderData(AutohomeCarInfoDTO data);
	
	List<Brand> findBrandByCatId(Integer catId);
}