package com.cnit.yoyo.dao.goods;

import com.cnit.yoyo.model.goods.DriveOrConsult;
import com.cnit.yoyo.model.goods.DriveOrConsultExample;
import com.cnit.yoyo.model.goods.dto.DriveOrConsultDTO;
import com.cnit.yoyo.model.other.drive.ReservationDrive;
import com.cnit.yoyo.model.other.drive.dto.ReservationDriveQryDTO;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DriveOrConsultMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_drive_or_consult
	 * @mbggenerated  Tue May 12 16:37:40 CST 2015
	 */
	int countByExample(DriveOrConsultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_drive_or_consult
	 * @mbggenerated  Tue May 12 16:37:40 CST 2015
	 */
	int deleteByExample(DriveOrConsultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_drive_or_consult
	 * @mbggenerated  Tue May 12 16:37:40 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_drive_or_consult
	 * @mbggenerated  Tue May 12 16:37:40 CST 2015
	 */
	int insert(DriveOrConsult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_drive_or_consult
	 * @mbggenerated  Tue May 12 16:37:40 CST 2015
	 */
	int insertSelective(DriveOrConsult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_drive_or_consult
	 * @mbggenerated  Tue May 12 16:37:40 CST 2015
	 */
	List<DriveOrConsult> selectByExample(DriveOrConsultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_drive_or_consult
	 * @mbggenerated  Tue May 12 16:37:40 CST 2015
	 */
	DriveOrConsult selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_drive_or_consult
	 * @mbggenerated  Tue May 12 16:37:40 CST 2015
	 */
	int updateByExampleSelective(@Param("record") DriveOrConsult record,
			@Param("example") DriveOrConsultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_drive_or_consult
	 * @mbggenerated  Tue May 12 16:37:40 CST 2015
	 */
	int updateByExample(@Param("record") DriveOrConsult record,
			@Param("example") DriveOrConsultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_drive_or_consult
	 * @mbggenerated  Tue May 12 16:37:40 CST 2015
	 */
	int updateByPrimaryKeySelective(DriveOrConsult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_drive_or_consult
	 * @mbggenerated  Tue May 12 16:37:40 CST 2015
	 */
	int updateByPrimaryKey(DriveOrConsult record);
	
	/**
	 * @Title:  selectByParam  
	 * @Description:  TODO(根据给定参数查询)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-12 下午5:20:41  
	 * @version 1.0.0 
	 * @param @param carId
	 * @param @param cityId
	 * @param @param phone
	 * @param @param type
	 * @param @param isReplace
	 * @param @param state
	 * @param @return
	 * @return List<DriveOrConsult>  返回类型 
	 * @throws
	 */
	List<DriveOrConsult> selectByParam(@Param("carId") Integer carId, @Param("cityId") Integer cityId, 
			@Param("phone") String phone, @Param("type") String type, @Param("isReplace") Integer isReplace,
			@Param("state") Integer state);
	
//	/**
//	 * @Title:  selectByPage  
//	 * @Description:  TODO(倒序查询申请历史记录)  
//	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
//	 * @date 2015-5-12 下午5:19:20  
//	 * @version 1.0.0 
//	 * @param @return
//	 * @return List<DriveOrConsultDTO>  返回类型 
//	 * @throws
//	 */
//	List<DriveOrConsultDTO> selectAll();
	
	/**
	 * @Title:  selectAllByType  
	 * @Description:  TODO(根据类型倒序查询申请历史记录)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-14 下午3:54:11  
	 * @version 1.0.0 
	 * @param @param type
	 * @param @return
	 * @return List<DriveOrConsultDTO>  返回类型 
	 * @throws
	 */
	List<DriveOrConsultDTO> selectAllByType(String type);
	
	
	/**
	  * @description <b>查询预约试驾列表信息</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-5-27
	  * @param @return
	  * @return List<ReservationDrive>
	*/
	public List<ReservationDrive> selectReservationDrive(ReservationDriveQryDTO qryDTO);
	
	/**
	  * @description <b>卖家中心预约试驾查询</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-5-27
	  * @param @return
	  * @return List<ReservationDrive>
	*/
	public List<ReservationDrive> selectShopReservationDrive(ReservationDriveQryDTO qryDTO);
	
	/**
	  * @description <b>查询咨询最低价列表</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-5-27
	  * @param @return
	  * @return List<ReservationDrive>
	*/
	public List<ReservationDrive> selectLowPriceConsult(ReservationDriveQryDTO qryDTO);
	
	/**
	  * @description <b>卖家中心询问最低价查询</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-5-27
	  * @param @return
	  * @return List<ReservationDrive>
	*/
	public List<ReservationDrive> selectShopLowPriceConsult(ReservationDriveQryDTO qryDTO);
	
	int deleteDriveOrConsult(Integer [] ids);
}