package com.cnit.yoyo.dao.goods;

import com.cnit.yoyo.model.goods.GoodsProductPicShip;
import com.cnit.yoyo.model.goods.GoodsProductPicShipExample;
import com.cnit.yoyo.model.goods.dto.GoodsProductPicShipDTO;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsProductPicShipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_produc_pic_ship
     *
     * @mbggenerated Sat Apr 11 11:13:42 CST 2015
     */
    int deleteByExample(GoodsProductPicShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_produc_pic_ship
     *
     * @mbggenerated Sat Apr 11 11:13:42 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_produc_pic_ship
     *
     * @mbggenerated Sat Apr 11 11:13:42 CST 2015
     */
    int insert(GoodsProductPicShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_produc_pic_ship
     *
     * @mbggenerated Sat Apr 11 11:13:42 CST 2015
     */
    int insertSelective(GoodsProductPicShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_produc_pic_ship
     *
     * @mbggenerated Sat Apr 11 11:13:42 CST 2015
     */
    List<GoodsProductPicShip> selectByExample(GoodsProductPicShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_produc_pic_ship
     *
     * @mbggenerated Sat Apr 11 11:13:42 CST 2015
     */
    GoodsProductPicShip selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_produc_pic_ship
     *
     * @mbggenerated Sat Apr 11 11:13:42 CST 2015
     */
    int updateByExampleSelective(@Param("record") GoodsProductPicShip record, @Param("example") GoodsProductPicShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_produc_pic_ship
     *
     * @mbggenerated Sat Apr 11 11:13:42 CST 2015
     */
    int updateByExample(@Param("record") GoodsProductPicShip record, @Param("example") GoodsProductPicShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_produc_pic_ship
     *
     * @mbggenerated Sat Apr 11 11:13:42 CST 2015
     */
    int updateByPrimaryKeySelective(GoodsProductPicShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_produc_pic_ship
     *
     * @mbggenerated Sat Apr 11 11:13:42 CST 2015
     */
    int updateByPrimaryKey(GoodsProductPicShip record);
    
    List<GoodsProductPicShipDTO> findPicByGoodsId(Integer goodsId);
}