package com.cnit.yoyo.dao.goods;

import com.cnit.yoyo.model.goods.GoodsViewHistory;
import com.cnit.yoyo.model.goods.GoodsViewHistoryExample;
import com.cnit.yoyo.model.goods.GoodsViewHistoryKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsViewHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_view_history
     *
     * @mbggenerated Sat May 09 18:27:15 CST 2015
     */
    int countByExample(GoodsViewHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_view_history
     *
     * @mbggenerated Sat May 09 18:27:15 CST 2015
     */
    int deleteByExample(GoodsViewHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_view_history
     *
     * @mbggenerated Sat May 09 18:27:15 CST 2015
     */
    int deleteByPrimaryKey(GoodsViewHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_view_history
     *
     * @mbggenerated Sat May 09 18:27:15 CST 2015
     */
    int insert(GoodsViewHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_view_history
     *
     * @mbggenerated Sat May 09 18:27:15 CST 2015
     */
    int insertSelective(GoodsViewHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_view_history
     *
     * @mbggenerated Sat May 09 18:27:15 CST 2015
     */
    List<GoodsViewHistory> selectByExample(GoodsViewHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_view_history
     *
     * @mbggenerated Sat May 09 18:27:15 CST 2015
     */
    GoodsViewHistory selectByPrimaryKey(GoodsViewHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_view_history
     *
     * @mbggenerated Sat May 09 18:27:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") GoodsViewHistory record, @Param("example") GoodsViewHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_view_history
     *
     * @mbggenerated Sat May 09 18:27:15 CST 2015
     */
    int updateByExample(@Param("record") GoodsViewHistory record, @Param("example") GoodsViewHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_view_history
     *
     * @mbggenerated Sat May 09 18:27:15 CST 2015
     */
    int updateByPrimaryKeySelective(GoodsViewHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_view_history
     *
     * @mbggenerated Sat May 09 18:27:15 CST 2015
     */
    int updateByPrimaryKey(GoodsViewHistory record);
}