package com.cnit.yoyo.dao.goods;

import java.util.Map;

import com.cnit.yoyo.model.goods.GoodsTimePrice;

public interface GoodsTimePriceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_time_price
	 * @mbggenerated  Mon Aug 17 16:27:11 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_time_price
	 * @mbggenerated  Mon Aug 17 16:27:11 CST 2015
	 */
	int insert(GoodsTimePrice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_time_price
	 * @mbggenerated  Mon Aug 17 16:27:11 CST 2015
	 */
	int insertSelective(GoodsTimePrice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_time_price
	 * @mbggenerated  Mon Aug 17 16:27:11 CST 2015
	 */
	GoodsTimePrice selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_time_price
	 * @mbggenerated  Mon Aug 17 16:27:11 CST 2015
	 */
	int updateByPrimaryKeySelective(GoodsTimePrice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_time_price
	 * @mbggenerated  Mon Aug 17 16:27:11 CST 2015
	 */
	int updateByPrimaryKey(GoodsTimePrice record);
	
	/**
	 * @description <b>获取商品时间区间价格</b>
	 * @author 王鹏
	 * @version 1.0.0
	 * @data 2015年8月19日
	 * @param param
	 * @return
	 * GoodsTimePrice
	*/
	GoodsTimePrice selectGoodsTimePrice(Map<String, Object> param);
}