package com.cnit.yoyo.dao.goods;

import com.cnit.yoyo.model.goods.GoodsKeywords;
import com.cnit.yoyo.model.goods.GoodsKeywordsExample;
import com.cnit.yoyo.model.goods.GoodsKeywordsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsKeywordsMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_keywords
     * @mbggenerated  Mon Apr 13 18:56:46 CST 2015
     */
    int deleteByExample(GoodsKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_keywords
     * @mbggenerated  Mon Apr 13 18:56:46 CST 2015
     */
    int deleteByPrimaryKey(GoodsKeywordsKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_keywords
     * @mbggenerated  Mon Apr 13 18:56:46 CST 2015
     */
    int insert(GoodsKeywords record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_keywords
     * @mbggenerated  Mon Apr 13 18:56:46 CST 2015
     */
    int insertSelective(GoodsKeywords record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_keywords
     * @mbggenerated  Mon Apr 13 18:56:46 CST 2015
     */
    List<GoodsKeywords> selectByExample(GoodsKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_keywords
     * @mbggenerated  Mon Apr 13 18:56:46 CST 2015
     */
    GoodsKeywords selectByPrimaryKey(GoodsKeywordsKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_keywords
     * @mbggenerated  Mon Apr 13 18:56:46 CST 2015
     */
    int updateByExampleSelective(@Param("record") GoodsKeywords record, @Param("example") GoodsKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_keywords
     * @mbggenerated  Mon Apr 13 18:56:46 CST 2015
     */
    int updateByExample(@Param("record") GoodsKeywords record, @Param("example") GoodsKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_keywords
     * @mbggenerated  Mon Apr 13 18:56:46 CST 2015
     */
    int updateByPrimaryKeySelective(GoodsKeywords record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_keywords
     * @mbggenerated  Mon Apr 13 18:56:46 CST 2015
     */
    int updateByPrimaryKey(GoodsKeywords record);

    /**
     *@description <一句话方法简述>
     *@detail <方法详细描述>
     *@author <a href="liming@cnitcloud.com">李明</a>
     *@version 1.0.0
     *@data 2015年4月14日
     *@param goodsKeywordsList
     */
    int batchInsert(@Param("list")List<GoodsKeywords> goodsKeywordsList);
    
    /**
     * @Title:  selectByKeyWordList  
     * @Description:  TODO(通过关键字列表查询关键字对象)  
     * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
     * @date 2015-5-8 下午4:58:58  
     * @version 1.0.0 
     * @param @param keyWordList
     * @param @return
     * @return List<GoodsKeywords>  返回类型 
     * @throws
     */
    List<GoodsKeywords> selectByKeyWordList(List<String> keyWordList);
}