package com.cnit.yoyo.dao.goods;

import com.cnit.yoyo.model.goods.SpecGoodsIndex;
import com.cnit.yoyo.model.goods.SpecGoodsIndexExample;
import com.cnit.yoyo.model.goods.SpecGoodsIndexKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpecGoodsIndexMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_goods_index
     * @mbggenerated  Wed Apr 15 17:41:47 CST 2015
     */
    int deleteByExample(SpecGoodsIndexExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_goods_index
     * @mbggenerated  Wed Apr 15 17:41:47 CST 2015
     */
    int deleteByPrimaryKey(SpecGoodsIndexKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_goods_index
     * @mbggenerated  Wed Apr 15 17:41:47 CST 2015
     */
    int insert(SpecGoodsIndex record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_goods_index
     * @mbggenerated  Wed Apr 15 17:41:47 CST 2015
     */
    int insertSelective(SpecGoodsIndex record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_goods_index
     * @mbggenerated  Wed Apr 15 17:41:47 CST 2015
     */
    List<SpecGoodsIndex> selectByExample(SpecGoodsIndexExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_goods_index
     * @mbggenerated  Wed Apr 15 17:41:47 CST 2015
     */
    SpecGoodsIndex selectByPrimaryKey(SpecGoodsIndexKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_goods_index
     * @mbggenerated  Wed Apr 15 17:41:47 CST 2015
     */
    int updateByExampleSelective(@Param("record") SpecGoodsIndex record, @Param("example") SpecGoodsIndexExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_goods_index
     * @mbggenerated  Wed Apr 15 17:41:47 CST 2015
     */
    int updateByExample(@Param("record") SpecGoodsIndex record, @Param("example") SpecGoodsIndexExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_goods_index
     * @mbggenerated  Wed Apr 15 17:41:47 CST 2015
     */
    int updateByPrimaryKeySelective(SpecGoodsIndex record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_goods_index
     * @mbggenerated  Wed Apr 15 17:41:47 CST 2015
     */
    int updateByPrimaryKey(SpecGoodsIndex record);
}