package com.cnit.yoyo.dao.goods;

import com.cnit.yoyo.dto.spec.SpecQryDTO;
import com.cnit.yoyo.model.goods.SpecValues;
import com.cnit.yoyo.model.goods.SpecValuesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpecValuesMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_values
     * @mbggenerated  Wed Mar 25 10:32:24 CST 2015
     */
    int deleteByExample(SpecValuesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_values
     * @mbggenerated  Wed Mar 25 10:32:24 CST 2015
     */
    int deleteByPrimaryKey(Integer specValueId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_values
     * @mbggenerated  Wed Mar 25 10:32:24 CST 2015
     */
    int insert(SpecValues record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_values
     * @mbggenerated  Wed Mar 25 10:32:24 CST 2015
     */
    int insertSelective(SpecValues record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_values
     * @mbggenerated  Wed Mar 25 10:32:24 CST 2015
     */
    List<SpecValues> selectByExample(SpecValuesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_values
     * @mbggenerated  Wed Mar 25 10:32:24 CST 2015
     */
    SpecValues selectByPrimaryKey(Integer specValueId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_values
     * @mbggenerated  Wed Mar 25 10:32:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") SpecValues record, @Param("example") SpecValuesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_values
     * @mbggenerated  Wed Mar 25 10:32:24 CST 2015
     */
    int updateByExample(@Param("record") SpecValues record, @Param("example") SpecValuesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_values
     * @mbggenerated  Wed Mar 25 10:32:24 CST 2015
     */
    int updateByPrimaryKeySelective(SpecValues record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_spec_values
     * @mbggenerated  Wed Mar 25 10:32:24 CST 2015
     */
    int updateByPrimaryKey(SpecValues record);
    
    /**
     * 
    * @Title: selectSpecAndValueById 
    * @Description: 根据商品规格值id列表查询商品规格
    * @author <a href="cmlai@chinacnit.com">赖彩妙</a>
    * @param @param valueIdList
    * @param @return    设定文件 
    * @return List<SpecQryDTO>    返回类型 
    * @throws
     */
    List<SpecQryDTO> selectSpecAndValueById(List<Integer> valueIdList);
}