package com.cnit.yoyo.model.activity;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class SalesRuleGoodsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	public SalesRuleGoodsExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRuleIdIsNull() {
			addCriterion("rule_id is null");
			return (Criteria) this;
		}

		public Criteria andRuleIdIsNotNull() {
			addCriterion("rule_id is not null");
			return (Criteria) this;
		}

		public Criteria andRuleIdEqualTo(Integer value) {
			addCriterion("rule_id =", value, "ruleId");
			return (Criteria) this;
		}

		public Criteria andRuleIdNotEqualTo(Integer value) {
			addCriterion("rule_id <>", value, "ruleId");
			return (Criteria) this;
		}

		public Criteria andRuleIdGreaterThan(Integer value) {
			addCriterion("rule_id >", value, "ruleId");
			return (Criteria) this;
		}

		public Criteria andRuleIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("rule_id >=", value, "ruleId");
			return (Criteria) this;
		}

		public Criteria andRuleIdLessThan(Integer value) {
			addCriterion("rule_id <", value, "ruleId");
			return (Criteria) this;
		}

		public Criteria andRuleIdLessThanOrEqualTo(Integer value) {
			addCriterion("rule_id <=", value, "ruleId");
			return (Criteria) this;
		}

		public Criteria andRuleIdIn(List<Integer> values) {
			addCriterion("rule_id in", values, "ruleId");
			return (Criteria) this;
		}

		public Criteria andRuleIdNotIn(List<Integer> values) {
			addCriterion("rule_id not in", values, "ruleId");
			return (Criteria) this;
		}

		public Criteria andRuleIdBetween(Integer value1, Integer value2) {
			addCriterion("rule_id between", value1, value2, "ruleId");
			return (Criteria) this;
		}

		public Criteria andRuleIdNotBetween(Integer value1, Integer value2) {
			addCriterion("rule_id not between", value1, value2, "ruleId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIsNull() {
			addCriterion("company_id is null");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIsNotNull() {
			addCriterion("company_id is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyIdEqualTo(Long value) {
			addCriterion("company_id =", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotEqualTo(Long value) {
			addCriterion("company_id <>", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdGreaterThan(Long value) {
			addCriterion("company_id >", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdGreaterThanOrEqualTo(Long value) {
			addCriterion("company_id >=", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdLessThan(Long value) {
			addCriterion("company_id <", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdLessThanOrEqualTo(Long value) {
			addCriterion("company_id <=", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIn(List<Long> values) {
			addCriterion("company_id in", values, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotIn(List<Long> values) {
			addCriterion("company_id not in", values, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdBetween(Long value1, Long value2) {
			addCriterion("company_id between", value1, value2, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotBetween(Long value1, Long value2) {
			addCriterion("company_id not between", value1, value2, "companyId");
			return (Criteria) this;
		}

		public Criteria andStoreIdIsNull() {
			addCriterion("store_id is null");
			return (Criteria) this;
		}

		public Criteria andStoreIdIsNotNull() {
			addCriterion("store_id is not null");
			return (Criteria) this;
		}

		public Criteria andStoreIdEqualTo(Long value) {
			addCriterion("store_id =", value, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdNotEqualTo(Long value) {
			addCriterion("store_id <>", value, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdGreaterThan(Long value) {
			addCriterion("store_id >", value, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdGreaterThanOrEqualTo(Long value) {
			addCriterion("store_id >=", value, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdLessThan(Long value) {
			addCriterion("store_id <", value, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdLessThanOrEqualTo(Long value) {
			addCriterion("store_id <=", value, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdIn(List<Long> values) {
			addCriterion("store_id in", values, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdNotIn(List<Long> values) {
			addCriterion("store_id not in", values, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdBetween(Long value1, Long value2) {
			addCriterion("store_id between", value1, value2, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdNotBetween(Long value1, Long value2) {
			addCriterion("store_id not between", value1, value2, "storeId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andFromTimeIsNull() {
			addCriterion("from_time is null");
			return (Criteria) this;
		}

		public Criteria andFromTimeIsNotNull() {
			addCriterion("from_time is not null");
			return (Criteria) this;
		}

		public Criteria andFromTimeEqualTo(Date value) {
			addCriterion("from_time =", value, "fromTime");
			return (Criteria) this;
		}

		public Criteria andFromTimeNotEqualTo(Date value) {
			addCriterion("from_time <>", value, "fromTime");
			return (Criteria) this;
		}

		public Criteria andFromTimeGreaterThan(Date value) {
			addCriterion("from_time >", value, "fromTime");
			return (Criteria) this;
		}

		public Criteria andFromTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("from_time >=", value, "fromTime");
			return (Criteria) this;
		}

		public Criteria andFromTimeLessThan(Date value) {
			addCriterion("from_time <", value, "fromTime");
			return (Criteria) this;
		}

		public Criteria andFromTimeLessThanOrEqualTo(Date value) {
			addCriterion("from_time <=", value, "fromTime");
			return (Criteria) this;
		}

		public Criteria andFromTimeIn(List<Date> values) {
			addCriterion("from_time in", values, "fromTime");
			return (Criteria) this;
		}

		public Criteria andFromTimeNotIn(List<Date> values) {
			addCriterion("from_time not in", values, "fromTime");
			return (Criteria) this;
		}

		public Criteria andFromTimeBetween(Date value1, Date value2) {
			addCriterion("from_time between", value1, value2, "fromTime");
			return (Criteria) this;
		}

		public Criteria andFromTimeNotBetween(Date value1, Date value2) {
			addCriterion("from_time not between", value1, value2, "fromTime");
			return (Criteria) this;
		}

		public Criteria andToTimeIsNull() {
			addCriterion("to_time is null");
			return (Criteria) this;
		}

		public Criteria andToTimeIsNotNull() {
			addCriterion("to_time is not null");
			return (Criteria) this;
		}

		public Criteria andToTimeEqualTo(Date value) {
			addCriterion("to_time =", value, "toTime");
			return (Criteria) this;
		}

		public Criteria andToTimeNotEqualTo(Date value) {
			addCriterion("to_time <>", value, "toTime");
			return (Criteria) this;
		}

		public Criteria andToTimeGreaterThan(Date value) {
			addCriterion("to_time >", value, "toTime");
			return (Criteria) this;
		}

		public Criteria andToTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("to_time >=", value, "toTime");
			return (Criteria) this;
		}

		public Criteria andToTimeLessThan(Date value) {
			addCriterion("to_time <", value, "toTime");
			return (Criteria) this;
		}

		public Criteria andToTimeLessThanOrEqualTo(Date value) {
			addCriterion("to_time <=", value, "toTime");
			return (Criteria) this;
		}

		public Criteria andToTimeIn(List<Date> values) {
			addCriterion("to_time in", values, "toTime");
			return (Criteria) this;
		}

		public Criteria andToTimeNotIn(List<Date> values) {
			addCriterion("to_time not in", values, "toTime");
			return (Criteria) this;
		}

		public Criteria andToTimeBetween(Date value1, Date value2) {
			addCriterion("to_time between", value1, value2, "toTime");
			return (Criteria) this;
		}

		public Criteria andToTimeNotBetween(Date value1, Date value2) {
			addCriterion("to_time not between", value1, value2, "toTime");
			return (Criteria) this;
		}

		public Criteria andMemberLvIdsIsNull() {
			addCriterion("member_lv_ids is null");
			return (Criteria) this;
		}

		public Criteria andMemberLvIdsIsNotNull() {
			addCriterion("member_lv_ids is not null");
			return (Criteria) this;
		}

		public Criteria andMemberLvIdsEqualTo(String value) {
			addCriterion("member_lv_ids =", value, "memberLvIds");
			return (Criteria) this;
		}

		public Criteria andMemberLvIdsNotEqualTo(String value) {
			addCriterion("member_lv_ids <>", value, "memberLvIds");
			return (Criteria) this;
		}

		public Criteria andMemberLvIdsGreaterThan(String value) {
			addCriterion("member_lv_ids >", value, "memberLvIds");
			return (Criteria) this;
		}

		public Criteria andMemberLvIdsGreaterThanOrEqualTo(String value) {
			addCriterion("member_lv_ids >=", value, "memberLvIds");
			return (Criteria) this;
		}

		public Criteria andMemberLvIdsLessThan(String value) {
			addCriterion("member_lv_ids <", value, "memberLvIds");
			return (Criteria) this;
		}

		public Criteria andMemberLvIdsLessThanOrEqualTo(String value) {
			addCriterion("member_lv_ids <=", value, "memberLvIds");
			return (Criteria) this;
		}

		public Criteria andMemberLvIdsLike(String value) {
			addCriterion("member_lv_ids like", value, "memberLvIds");
			return (Criteria) this;
		}

		public Criteria andMemberLvIdsNotLike(String value) {
			addCriterion("member_lv_ids not like", value, "memberLvIds");
			return (Criteria) this;
		}

		public Criteria andMemberLvIdsIn(List<String> values) {
			addCriterion("member_lv_ids in", values, "memberLvIds");
			return (Criteria) this;
		}

		public Criteria andMemberLvIdsNotIn(List<String> values) {
			addCriterion("member_lv_ids not in", values, "memberLvIds");
			return (Criteria) this;
		}

		public Criteria andMemberLvIdsBetween(String value1, String value2) {
			addCriterion("member_lv_ids between", value1, value2, "memberLvIds");
			return (Criteria) this;
		}

		public Criteria andMemberLvIdsNotBetween(String value1, String value2) {
			addCriterion("member_lv_ids not between", value1, value2,
					"memberLvIds");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStopRulesProcessingIsNull() {
			addCriterion("stop_rules_processing is null");
			return (Criteria) this;
		}

		public Criteria andStopRulesProcessingIsNotNull() {
			addCriterion("stop_rules_processing is not null");
			return (Criteria) this;
		}

		public Criteria andStopRulesProcessingEqualTo(String value) {
			addCriterion("stop_rules_processing =", value,
					"stopRulesProcessing");
			return (Criteria) this;
		}

		public Criteria andStopRulesProcessingNotEqualTo(String value) {
			addCriterion("stop_rules_processing <>", value,
					"stopRulesProcessing");
			return (Criteria) this;
		}

		public Criteria andStopRulesProcessingGreaterThan(String value) {
			addCriterion("stop_rules_processing >", value,
					"stopRulesProcessing");
			return (Criteria) this;
		}

		public Criteria andStopRulesProcessingGreaterThanOrEqualTo(String value) {
			addCriterion("stop_rules_processing >=", value,
					"stopRulesProcessing");
			return (Criteria) this;
		}

		public Criteria andStopRulesProcessingLessThan(String value) {
			addCriterion("stop_rules_processing <", value,
					"stopRulesProcessing");
			return (Criteria) this;
		}

		public Criteria andStopRulesProcessingLessThanOrEqualTo(String value) {
			addCriterion("stop_rules_processing <=", value,
					"stopRulesProcessing");
			return (Criteria) this;
		}

		public Criteria andStopRulesProcessingLike(String value) {
			addCriterion("stop_rules_processing like", value,
					"stopRulesProcessing");
			return (Criteria) this;
		}

		public Criteria andStopRulesProcessingNotLike(String value) {
			addCriterion("stop_rules_processing not like", value,
					"stopRulesProcessing");
			return (Criteria) this;
		}

		public Criteria andStopRulesProcessingIn(List<String> values) {
			addCriterion("stop_rules_processing in", values,
					"stopRulesProcessing");
			return (Criteria) this;
		}

		public Criteria andStopRulesProcessingNotIn(List<String> values) {
			addCriterion("stop_rules_processing not in", values,
					"stopRulesProcessing");
			return (Criteria) this;
		}

		public Criteria andStopRulesProcessingBetween(String value1,
				String value2) {
			addCriterion("stop_rules_processing between", value1, value2,
					"stopRulesProcessing");
			return (Criteria) this;
		}

		public Criteria andStopRulesProcessingNotBetween(String value1,
				String value2) {
			addCriterion("stop_rules_processing not between", value1, value2,
					"stopRulesProcessing");
			return (Criteria) this;
		}

		public Criteria andSortOrderIsNull() {
			addCriterion("sort_order is null");
			return (Criteria) this;
		}

		public Criteria andSortOrderIsNotNull() {
			addCriterion("sort_order is not null");
			return (Criteria) this;
		}

		public Criteria andSortOrderEqualTo(Integer value) {
			addCriterion("sort_order =", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotEqualTo(Integer value) {
			addCriterion("sort_order <>", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderGreaterThan(Integer value) {
			addCriterion("sort_order >", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("sort_order >=", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderLessThan(Integer value) {
			addCriterion("sort_order <", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderLessThanOrEqualTo(Integer value) {
			addCriterion("sort_order <=", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderIn(List<Integer> values) {
			addCriterion("sort_order in", values, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotIn(List<Integer> values) {
			addCriterion("sort_order not in", values, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderBetween(Integer value1, Integer value2) {
			addCriterion("sort_order between", value1, value2, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("sort_order not between", value1, value2, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andFreeShippingIsNull() {
			addCriterion("free_shipping is null");
			return (Criteria) this;
		}

		public Criteria andFreeShippingIsNotNull() {
			addCriterion("free_shipping is not null");
			return (Criteria) this;
		}

		public Criteria andFreeShippingEqualTo(Boolean value) {
			addCriterion("free_shipping =", value, "freeShipping");
			return (Criteria) this;
		}

		public Criteria andFreeShippingNotEqualTo(Boolean value) {
			addCriterion("free_shipping <>", value, "freeShipping");
			return (Criteria) this;
		}

		public Criteria andFreeShippingGreaterThan(Boolean value) {
			addCriterion("free_shipping >", value, "freeShipping");
			return (Criteria) this;
		}

		public Criteria andFreeShippingGreaterThanOrEqualTo(Boolean value) {
			addCriterion("free_shipping >=", value, "freeShipping");
			return (Criteria) this;
		}

		public Criteria andFreeShippingLessThan(Boolean value) {
			addCriterion("free_shipping <", value, "freeShipping");
			return (Criteria) this;
		}

		public Criteria andFreeShippingLessThanOrEqualTo(Boolean value) {
			addCriterion("free_shipping <=", value, "freeShipping");
			return (Criteria) this;
		}

		public Criteria andFreeShippingIn(List<Boolean> values) {
			addCriterion("free_shipping in", values, "freeShipping");
			return (Criteria) this;
		}

		public Criteria andFreeShippingNotIn(List<Boolean> values) {
			addCriterion("free_shipping not in", values, "freeShipping");
			return (Criteria) this;
		}

		public Criteria andFreeShippingBetween(Boolean value1, Boolean value2) {
			addCriterion("free_shipping between", value1, value2,
					"freeShipping");
			return (Criteria) this;
		}

		public Criteria andFreeShippingNotBetween(Boolean value1, Boolean value2) {
			addCriterion("free_shipping not between", value1, value2,
					"freeShipping");
			return (Criteria) this;
		}

		public Criteria andCTemplateIsNull() {
			addCriterion("c_template is null");
			return (Criteria) this;
		}

		public Criteria andCTemplateIsNotNull() {
			addCriterion("c_template is not null");
			return (Criteria) this;
		}

		public Criteria andCTemplateEqualTo(String value) {
			addCriterion("c_template =", value, "cTemplate");
			return (Criteria) this;
		}

		public Criteria andCTemplateNotEqualTo(String value) {
			addCriterion("c_template <>", value, "cTemplate");
			return (Criteria) this;
		}

		public Criteria andCTemplateGreaterThan(String value) {
			addCriterion("c_template >", value, "cTemplate");
			return (Criteria) this;
		}

		public Criteria andCTemplateGreaterThanOrEqualTo(String value) {
			addCriterion("c_template >=", value, "cTemplate");
			return (Criteria) this;
		}

		public Criteria andCTemplateLessThan(String value) {
			addCriterion("c_template <", value, "cTemplate");
			return (Criteria) this;
		}

		public Criteria andCTemplateLessThanOrEqualTo(String value) {
			addCriterion("c_template <=", value, "cTemplate");
			return (Criteria) this;
		}

		public Criteria andCTemplateLike(String value) {
			addCriterion("c_template like", value, "cTemplate");
			return (Criteria) this;
		}

		public Criteria andCTemplateNotLike(String value) {
			addCriterion("c_template not like", value, "cTemplate");
			return (Criteria) this;
		}

		public Criteria andCTemplateIn(List<String> values) {
			addCriterion("c_template in", values, "cTemplate");
			return (Criteria) this;
		}

		public Criteria andCTemplateNotIn(List<String> values) {
			addCriterion("c_template not in", values, "cTemplate");
			return (Criteria) this;
		}

		public Criteria andCTemplateBetween(String value1, String value2) {
			addCriterion("c_template between", value1, value2, "cTemplate");
			return (Criteria) this;
		}

		public Criteria andCTemplateNotBetween(String value1, String value2) {
			addCriterion("c_template not between", value1, value2, "cTemplate");
			return (Criteria) this;
		}

		public Criteria andSTemplateIsNull() {
			addCriterion("s_template is null");
			return (Criteria) this;
		}

		public Criteria andSTemplateIsNotNull() {
			addCriterion("s_template is not null");
			return (Criteria) this;
		}

		public Criteria andSTemplateEqualTo(String value) {
			addCriterion("s_template =", value, "sTemplate");
			return (Criteria) this;
		}

		public Criteria andSTemplateNotEqualTo(String value) {
			addCriterion("s_template <>", value, "sTemplate");
			return (Criteria) this;
		}

		public Criteria andSTemplateGreaterThan(String value) {
			addCriterion("s_template >", value, "sTemplate");
			return (Criteria) this;
		}

		public Criteria andSTemplateGreaterThanOrEqualTo(String value) {
			addCriterion("s_template >=", value, "sTemplate");
			return (Criteria) this;
		}

		public Criteria andSTemplateLessThan(String value) {
			addCriterion("s_template <", value, "sTemplate");
			return (Criteria) this;
		}

		public Criteria andSTemplateLessThanOrEqualTo(String value) {
			addCriterion("s_template <=", value, "sTemplate");
			return (Criteria) this;
		}

		public Criteria andSTemplateLike(String value) {
			addCriterion("s_template like", value, "sTemplate");
			return (Criteria) this;
		}

		public Criteria andSTemplateNotLike(String value) {
			addCriterion("s_template not like", value, "sTemplate");
			return (Criteria) this;
		}

		public Criteria andSTemplateIn(List<String> values) {
			addCriterion("s_template in", values, "sTemplate");
			return (Criteria) this;
		}

		public Criteria andSTemplateNotIn(List<String> values) {
			addCriterion("s_template not in", values, "sTemplate");
			return (Criteria) this;
		}

		public Criteria andSTemplateBetween(String value1, String value2) {
			addCriterion("s_template between", value1, value2, "sTemplate");
			return (Criteria) this;
		}

		public Criteria andSTemplateNotBetween(String value1, String value2) {
			addCriterion("s_template not between", value1, value2, "sTemplate");
			return (Criteria) this;
		}

		public Criteria andApplyTimeIsNull() {
			addCriterion("apply_time is null");
			return (Criteria) this;
		}

		public Criteria andApplyTimeIsNotNull() {
			addCriterion("apply_time is not null");
			return (Criteria) this;
		}

		public Criteria andApplyTimeEqualTo(Date value) {
			addCriterion("apply_time =", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeNotEqualTo(Date value) {
			addCriterion("apply_time <>", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeGreaterThan(Date value) {
			addCriterion("apply_time >", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("apply_time >=", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeLessThan(Date value) {
			addCriterion("apply_time <", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeLessThanOrEqualTo(Date value) {
			addCriterion("apply_time <=", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeIn(List<Date> values) {
			addCriterion("apply_time in", values, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeNotIn(List<Date> values) {
			addCriterion("apply_time not in", values, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeBetween(Date value1, Date value2) {
			addCriterion("apply_time between", value1, value2, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeNotBetween(Date value1, Date value2) {
			addCriterion("apply_time not between", value1, value2, "applyTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sales_rule_goods
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 20 10:38:25 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}