package com.cnit.yoyo.model.requirement;

import java.io.Serializable;
import java.util.Date;

public class Requirement implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_requirement.id
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_requirement.require_name
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	private String requireName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_requirement.sort
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_requirement.last_modify
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	private Date lastModify;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_requirement.creation_time
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	private Date creationTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_requirement.disabled
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	private Boolean disabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_requirement
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_requirement.id
	 * @return  the value of t_requirement.id
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_requirement.id
	 * @param id  the value for t_requirement.id
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_requirement.require_name
	 * @return  the value of t_requirement.require_name
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	public String getRequireName() {
		return requireName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_requirement.require_name
	 * @param requireName  the value for t_requirement.require_name
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	public void setRequireName(String requireName) {
		this.requireName = requireName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_requirement.sort
	 * @return  the value of t_requirement.sort
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_requirement.sort
	 * @param sort  the value for t_requirement.sort
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_requirement.last_modify
	 * @return  the value of t_requirement.last_modify
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	public Date getLastModify() {
		return lastModify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_requirement.last_modify
	 * @param lastModify  the value for t_requirement.last_modify
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	public void setLastModify(Date lastModify) {
		this.lastModify = lastModify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_requirement.creation_time
	 * @return  the value of t_requirement.creation_time
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	public Date getCreationTime() {
		return creationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_requirement.creation_time
	 * @param creationTime  the value for t_requirement.creation_time
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_requirement.disabled
	 * @return  the value of t_requirement.disabled
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	public Boolean getDisabled() {
		return disabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_requirement.disabled
	 * @param disabled  the value for t_requirement.disabled
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	public void setDisabled(Boolean disabled) {
		this.disabled = disabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_requirement
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", requireName=").append(requireName);
		sb.append(", sort=").append(sort);
		sb.append(", lastModify=").append(lastModify);
		sb.append(", creationTime=").append(creationTime);
		sb.append(", disabled=").append(disabled);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_requirement
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Requirement other = (Requirement) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getRequireName() == null ? other.getRequireName() == null
						: this.getRequireName().equals(other.getRequireName()))
				&& (this.getSort() == null ? other.getSort() == null : this
						.getSort().equals(other.getSort()))
				&& (this.getLastModify() == null ? other.getLastModify() == null
						: this.getLastModify().equals(other.getLastModify()))
				&& (this.getCreationTime() == null ? other.getCreationTime() == null
						: this.getCreationTime()
								.equals(other.getCreationTime()))
				&& (this.getDisabled() == null ? other.getDisabled() == null
						: this.getDisabled().equals(other.getDisabled()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_requirement
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime
				* result
				+ ((getRequireName() == null) ? 0 : getRequireName().hashCode());
		result = prime * result
				+ ((getSort() == null) ? 0 : getSort().hashCode());
		result = prime * result
				+ ((getLastModify() == null) ? 0 : getLastModify().hashCode());
		result = prime
				* result
				+ ((getCreationTime() == null) ? 0 : getCreationTime()
						.hashCode());
		result = prime * result
				+ ((getDisabled() == null) ? 0 : getDisabled().hashCode());
		return result;
	}
}