package com.cnit.yoyo.model.member;

import java.io.Serializable;

public class ActivityWishList implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_activity_wishlist.id
	 * @mbggenerated  Mon May 04 10:45:03 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_activity_wishlist.member_id
	 * @mbggenerated  Mon May 04 10:45:03 CST 2015
	 */
	private Integer memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_activity_wishlist.activity_id
	 * @mbggenerated  Mon May 04 10:45:03 CST 2015
	 */
	private Integer activityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_activity_wishlist
	 * @mbggenerated  Mon May 04 10:45:03 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_activity_wishlist.id
	 * @return  the value of t_activity_wishlist.id
	 * @mbggenerated  Mon May 04 10:45:03 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_activity_wishlist.id
	 * @param id  the value for t_activity_wishlist.id
	 * @mbggenerated  Mon May 04 10:45:03 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_activity_wishlist.member_id
	 * @return  the value of t_activity_wishlist.member_id
	 * @mbggenerated  Mon May 04 10:45:03 CST 2015
	 */
	public Integer getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_activity_wishlist.member_id
	 * @param memberId  the value for t_activity_wishlist.member_id
	 * @mbggenerated  Mon May 04 10:45:03 CST 2015
	 */
	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_activity_wishlist.activity_id
	 * @return  the value of t_activity_wishlist.activity_id
	 * @mbggenerated  Mon May 04 10:45:03 CST 2015
	 */
	public Integer getActivityId() {
		return activityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_activity_wishlist.activity_id
	 * @param activityId  the value for t_activity_wishlist.activity_id
	 * @mbggenerated  Mon May 04 10:45:03 CST 2015
	 */
	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_activity_wishlist
	 * @mbggenerated  Mon May 04 10:45:03 CST 2015
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", memberId=").append(memberId);
		sb.append(", activityId=").append(activityId);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_activity_wishlist
	 * @mbggenerated  Mon May 04 10:45:03 CST 2015
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ActivityWishList other = (ActivityWishList) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getMemberId() == null ? other.getMemberId() == null
						: this.getMemberId().equals(other.getMemberId()))
				&& (this.getActivityId() == null ? other.getActivityId() == null
						: this.getActivityId().equals(other.getActivityId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_activity_wishlist
	 * @mbggenerated  Mon May 04 10:45:03 CST 2015
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getMemberId() == null) ? 0 : getMemberId().hashCode());
		result = prime * result
				+ ((getActivityId() == null) ? 0 : getActivityId().hashCode());
		return result;
	}
}