package com.cnit.yoyo.model.member;

import java.io.Serializable;
import java.util.Date;

public class MemberComment implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.comment_id
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Integer commentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.member_id
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Integer memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.for_comment_id
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Integer forCommentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.type_id
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Long typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.product_id
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.order_id
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Long orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.object_type
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private String objectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.author_id
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Integer authorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.author
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.contact
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private String contact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.mem_read_status
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Integer memReadStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.adm_read_status
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Integer admReadStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.time
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.lastreply
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Date lastreply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.reply_name
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private String replyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.inbox
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Integer inbox;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.track
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Integer track;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.has_sent
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Integer hasSent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.to_id
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Integer toId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.to_uname
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private String toUname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.title
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.ip
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.display
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Integer display;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.gask_type
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private String gaskType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.p_index
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Byte pIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.disabled
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Integer disabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.comments_type
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private String commentsType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_member_comments.store_id
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private Integer storeId;

	private Long companyId;

	private Integer praise;// 点赞次数
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_member_comments
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.comment_id
	 * 
	 * @return the value of t_member_comments.comment_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Integer getCommentId() {
		return commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.comment_id
	 * 
	 * @param commentId
	 *            the value for t_member_comments.comment_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.member_id
	 * 
	 * @return the value of t_member_comments.member_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Integer getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.member_id
	 * 
	 * @param memberId
	 *            the value for t_member_comments.member_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.for_comment_id
	 * 
	 * @return the value of t_member_comments.for_comment_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Integer getForCommentId() {
		return forCommentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.for_comment_id
	 * 
	 * @param forCommentId
	 *            the value for t_member_comments.for_comment_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setForCommentId(Integer forCommentId) {
		this.forCommentId = forCommentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.type_id
	 * 
	 * @return the value of t_member_comments.type_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Long getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.type_id
	 * 
	 * @param typeId
	 *            the value for t_member_comments.type_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.product_id
	 * 
	 * @return the value of t_member_comments.product_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.product_id
	 * 
	 * @param productId
	 *            the value for t_member_comments.product_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.order_id
	 * 
	 * @return the value of t_member_comments.order_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Long getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.order_id
	 * 
	 * @param orderId
	 *            the value for t_member_comments.order_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.object_type
	 * 
	 * @return the value of t_member_comments.object_type
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public String getObjectType() {
		return objectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.object_type
	 * 
	 * @param objectType
	 *            the value for t_member_comments.object_type
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.author_id
	 * 
	 * @return the value of t_member_comments.author_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Integer getAuthorId() {
		return authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.author_id
	 * 
	 * @param authorId
	 *            the value for t_member_comments.author_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.author
	 * 
	 * @return the value of t_member_comments.author
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.author
	 * 
	 * @param author
	 *            the value for t_member_comments.author
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.contact
	 * 
	 * @return the value of t_member_comments.contact
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.contact
	 * 
	 * @param contact
	 *            the value for t_member_comments.contact
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setContact(String contact) {
		this.contact = contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.mem_read_status
	 * 
	 * @return the value of t_member_comments.mem_read_status
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Integer getMemReadStatus() {
		return memReadStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.mem_read_status
	 * 
	 * @param memReadStatus
	 *            the value for t_member_comments.mem_read_status
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setMemReadStatus(Integer memReadStatus) {
		this.memReadStatus = memReadStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.adm_read_status
	 * 
	 * @return the value of t_member_comments.adm_read_status
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Integer getAdmReadStatus() {
		return admReadStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.adm_read_status
	 * 
	 * @param admReadStatus
	 *            the value for t_member_comments.adm_read_status
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setAdmReadStatus(Integer admReadStatus) {
		this.admReadStatus = admReadStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.time
	 * 
	 * @return the value of t_member_comments.time
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.time
	 * 
	 * @param time
	 *            the value for t_member_comments.time
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.lastreply
	 * 
	 * @return the value of t_member_comments.lastreply
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Date getLastreply() {
		return lastreply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.lastreply
	 * 
	 * @param lastreply
	 *            the value for t_member_comments.lastreply
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setLastreply(Date lastreply) {
		this.lastreply = lastreply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.reply_name
	 * 
	 * @return the value of t_member_comments.reply_name
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public String getReplyName() {
		return replyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.reply_name
	 * 
	 * @param replyName
	 *            the value for t_member_comments.reply_name
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setReplyName(String replyName) {
		this.replyName = replyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.inbox
	 * 
	 * @return the value of t_member_comments.inbox
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Integer getInbox() {
		return inbox;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.inbox
	 * 
	 * @param inbox
	 *            the value for t_member_comments.inbox
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setInbox(Integer inbox) {
		this.inbox = inbox;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.track
	 * 
	 * @return the value of t_member_comments.track
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Integer getTrack() {
		return track;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.track
	 * 
	 * @param track
	 *            the value for t_member_comments.track
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setTrack(Integer track) {
		this.track = track;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.has_sent
	 * 
	 * @return the value of t_member_comments.has_sent
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Integer getHasSent() {
		return hasSent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.has_sent
	 * 
	 * @param hasSent
	 *            the value for t_member_comments.has_sent
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setHasSent(Integer hasSent) {
		this.hasSent = hasSent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.to_id
	 * 
	 * @return the value of t_member_comments.to_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Integer getToId() {
		return toId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.to_id
	 * 
	 * @param toId
	 *            the value for t_member_comments.to_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setToId(Integer toId) {
		this.toId = toId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.to_uname
	 * 
	 * @return the value of t_member_comments.to_uname
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public String getToUname() {
		return toUname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.to_uname
	 * 
	 * @param toUname
	 *            the value for t_member_comments.to_uname
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setToUname(String toUname) {
		this.toUname = toUname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.title
	 * 
	 * @return the value of t_member_comments.title
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.title
	 * 
	 * @param title
	 *            the value for t_member_comments.title
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.ip
	 * 
	 * @return the value of t_member_comments.ip
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.ip
	 * 
	 * @param ip
	 *            the value for t_member_comments.ip
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.display
	 * 
	 * @return the value of t_member_comments.display
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Integer getDisplay() {
		return display;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.display
	 * 
	 * @param display
	 *            the value for t_member_comments.display
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setDisplay(Integer display) {
		this.display = display;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.gask_type
	 * 
	 * @return the value of t_member_comments.gask_type
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public String getGaskType() {
		return gaskType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.gask_type
	 * 
	 * @param gaskType
	 *            the value for t_member_comments.gask_type
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setGaskType(String gaskType) {
		this.gaskType = gaskType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.p_index
	 * 
	 * @return the value of t_member_comments.p_index
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Byte getpIndex() {
		return pIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.p_index
	 * 
	 * @param pIndex
	 *            the value for t_member_comments.p_index
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setpIndex(Byte pIndex) {
		this.pIndex = pIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.disabled
	 * 
	 * @return the value of t_member_comments.disabled
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Integer getDisabled() {
		return disabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.disabled
	 * 
	 * @param disabled
	 *            the value for t_member_comments.disabled
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setDisabled(Integer disabled) {
		this.disabled = disabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.comments_type
	 * 
	 * @return the value of t_member_comments.comments_type
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public String getCommentsType() {
		return commentsType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.comments_type
	 * 
	 * @param commentsType
	 *            the value for t_member_comments.comments_type
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setCommentsType(String commentsType) {
		this.commentsType = commentsType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_member_comments.store_id
	 * 
	 * @return the value of t_member_comments.store_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public Integer getStoreId() {
		return storeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_member_comments.store_id
	 * 
	 * @param storeId
	 *            the value for t_member_comments.store_id
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	public Long getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public Integer getPraise() {
		return praise;
	}

	public void setPraise(Integer praise) {
		this.praise = praise;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_member_comments
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", commentId=").append(commentId);
		sb.append(", memberId=").append(memberId);
		sb.append(", forCommentId=").append(forCommentId);
		sb.append(", typeId=").append(typeId);
		sb.append(", productId=").append(productId);
		sb.append(", orderId=").append(orderId);
		sb.append(", objectType=").append(objectType);
		sb.append(", authorId=").append(authorId);
		sb.append(", author=").append(author);
		sb.append(", contact=").append(contact);
		sb.append(", memReadStatus=").append(memReadStatus);
		sb.append(", admReadStatus=").append(admReadStatus);
		sb.append(", time=").append(time);
		sb.append(", lastreply=").append(lastreply);
		sb.append(", replyName=").append(replyName);
		sb.append(", inbox=").append(inbox);
		sb.append(", track=").append(track);
		sb.append(", hasSent=").append(hasSent);
		sb.append(", toId=").append(toId);
		sb.append(", toUname=").append(toUname);
		sb.append(", title=").append(title);
		sb.append(", ip=").append(ip);
		sb.append(", display=").append(display);
		sb.append(", gaskType=").append(gaskType);
		sb.append(", pIndex=").append(pIndex);
		sb.append(", disabled=").append(disabled);
		sb.append(", commentsType=").append(commentsType);
		sb.append(", storeId=").append(storeId);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_member_comments
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		MemberComment other = (MemberComment) that;
		return (this.getCommentId() == null ? other.getCommentId() == null
				: this.getCommentId().equals(other.getCommentId()))
				&& (this.getMemberId() == null ? other.getMemberId() == null
						: this.getMemberId().equals(other.getMemberId()))
				&& (this.getForCommentId() == null ? other.getForCommentId() == null
						: this.getForCommentId()
								.equals(other.getForCommentId()))
				&& (this.getTypeId() == null ? other.getTypeId() == null : this
						.getTypeId().equals(other.getTypeId()))
				&& (this.getProductId() == null ? other.getProductId() == null
						: this.getProductId().equals(other.getProductId()))
				&& (this.getOrderId() == null ? other.getOrderId() == null
						: this.getOrderId().equals(other.getOrderId()))
				&& (this.getObjectType() == null ? other.getObjectType() == null
						: this.getObjectType().equals(other.getObjectType()))
				&& (this.getAuthorId() == null ? other.getAuthorId() == null
						: this.getAuthorId().equals(other.getAuthorId()))
				&& (this.getAuthor() == null ? other.getAuthor() == null : this
						.getAuthor().equals(other.getAuthor()))
				&& (this.getContact() == null ? other.getContact() == null
						: this.getContact().equals(other.getContact()))
				&& (this.getMemReadStatus() == null ? other.getMemReadStatus() == null
						: this.getMemReadStatus().equals(
								other.getMemReadStatus()))
				&& (this.getAdmReadStatus() == null ? other.getAdmReadStatus() == null
						: this.getAdmReadStatus().equals(
								other.getAdmReadStatus()))
				&& (this.getTime() == null ? other.getTime() == null : this
						.getTime().equals(other.getTime()))
				&& (this.getLastreply() == null ? other.getLastreply() == null
						: this.getLastreply().equals(other.getLastreply()))
				&& (this.getReplyName() == null ? other.getReplyName() == null
						: this.getReplyName().equals(other.getReplyName()))
				&& (this.getInbox() == null ? other.getInbox() == null : this
						.getInbox().equals(other.getInbox()))
				&& (this.getTrack() == null ? other.getTrack() == null : this
						.getTrack().equals(other.getTrack()))
				&& (this.getHasSent() == null ? other.getHasSent() == null
						: this.getHasSent().equals(other.getHasSent()))
				&& (this.getToId() == null ? other.getToId() == null : this
						.getToId().equals(other.getToId()))
				&& (this.getToUname() == null ? other.getToUname() == null
						: this.getToUname().equals(other.getToUname()))
				&& (this.getTitle() == null ? other.getTitle() == null : this
						.getTitle().equals(other.getTitle()))
				&& (this.getIp() == null ? other.getIp() == null : this.getIp()
						.equals(other.getIp()))
				&& (this.getDisplay() == null ? other.getDisplay() == null
						: this.getDisplay().equals(other.getDisplay()))
				&& (this.getGaskType() == null ? other.getGaskType() == null
						: this.getGaskType().equals(other.getGaskType()))
				&& (this.getpIndex() == null ? other.getpIndex() == null : this
						.getpIndex().equals(other.getpIndex()))
				&& (this.getDisabled() == null ? other.getDisabled() == null
						: this.getDisabled().equals(other.getDisabled()))
				&& (this.getCommentsType() == null ? other.getCommentsType() == null
						: this.getCommentsType()
								.equals(other.getCommentsType()))
				&& (this.getStoreId() == null ? other.getStoreId() == null
						: this.getStoreId().equals(other.getStoreId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_member_comments
	 * 
	 * @mbggenerated Thu Mar 05 10:09:08 CST 2015
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getCommentId() == null) ? 0 : getCommentId().hashCode());
		result = prime * result
				+ ((getMemberId() == null) ? 0 : getMemberId().hashCode());
		result = prime
				* result
				+ ((getForCommentId() == null) ? 0 : getForCommentId()
						.hashCode());
		result = prime * result
				+ ((getTypeId() == null) ? 0 : getTypeId().hashCode());
		result = prime * result
				+ ((getProductId() == null) ? 0 : getProductId().hashCode());
		result = prime * result
				+ ((getOrderId() == null) ? 0 : getOrderId().hashCode());
		result = prime * result
				+ ((getObjectType() == null) ? 0 : getObjectType().hashCode());
		result = prime * result
				+ ((getAuthorId() == null) ? 0 : getAuthorId().hashCode());
		result = prime * result
				+ ((getAuthor() == null) ? 0 : getAuthor().hashCode());
		result = prime * result
				+ ((getContact() == null) ? 0 : getContact().hashCode());
		result = prime
				* result
				+ ((getMemReadStatus() == null) ? 0 : getMemReadStatus()
						.hashCode());
		result = prime
				* result
				+ ((getAdmReadStatus() == null) ? 0 : getAdmReadStatus()
						.hashCode());
		result = prime * result
				+ ((getTime() == null) ? 0 : getTime().hashCode());
		result = prime * result
				+ ((getLastreply() == null) ? 0 : getLastreply().hashCode());
		result = prime * result
				+ ((getReplyName() == null) ? 0 : getReplyName().hashCode());
		result = prime * result
				+ ((getInbox() == null) ? 0 : getInbox().hashCode());
		result = prime * result
				+ ((getTrack() == null) ? 0 : getTrack().hashCode());
		result = prime * result
				+ ((getHasSent() == null) ? 0 : getHasSent().hashCode());
		result = prime * result
				+ ((getToId() == null) ? 0 : getToId().hashCode());
		result = prime * result
				+ ((getToUname() == null) ? 0 : getToUname().hashCode());
		result = prime * result
				+ ((getTitle() == null) ? 0 : getTitle().hashCode());
		result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
		result = prime * result
				+ ((getDisplay() == null) ? 0 : getDisplay().hashCode());
		result = prime * result
				+ ((getGaskType() == null) ? 0 : getGaskType().hashCode());
		result = prime * result
				+ ((getpIndex() == null) ? 0 : getpIndex().hashCode());
		result = prime * result
				+ ((getDisabled() == null) ? 0 : getDisabled().hashCode());
		result = prime
				* result
				+ ((getCommentsType() == null) ? 0 : getCommentsType()
						.hashCode());
		result = prime * result
				+ ((getStoreId() == null) ? 0 : getStoreId().hashCode());
		return result;
	}
}