(function(){var h={},mt={},c={id:"e72ef138e02a09642f378f0fe01c2017",dm:["yangche51.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'',ctrk:false,align:-1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,conv:0,apps:'siteId=5943798&goTop=1'};var p=!0,q=null,t=!1;mt.g={};mt.g.xa=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.g.cookieEnabled=navigator.cookieEnabled;mt.g.javaEnabled=navigator.javaEnabled();mt.g.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.g.ia=(window.screen.width||0)+"x"+(window.screen.height||0);mt.g.colorDepth=window.screen.colorDepth||0;mt.cookie={};
mt.cookie.set=function(a,d,g){var f;g.A&&(f=new Date,f.setTime(f.getTime()+g.A));document.cookie=a+"="+d+(g.domain?"; domain="+g.domain:"")+(g.path?"; path="+g.path:"")+(f?"; expires="+f.toGMTString():"")+(g.Ba?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:q};mt.event={};mt.event.e=function(a,d,g){a.attachEvent?a.attachEvent("on"+d,function(f){g.call(a,f)}):a.addEventListener&&a.addEventListener(d,g,t)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=t};mt.n={};mt.n.parse=function(){return(new Function('return (" + source + ")'))()};
mt.n.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var d=g[a];if(d)return d;d=a.charCodeAt();return"\\u00"+Math.floor(d/16).toString(16)+(d%16).toString(16)}));return'"'+a+'"'}function d(a){return 10>a?"0"+a:a}var g={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(f){switch(typeof f){case "undefined":return"undefined";case "number":return isFinite(f)?String(f):"null";case "string":return a(f);case "boolean":return String(f);
default:if(f===q)return"null";if(f instanceof Array){var g=["["],n=f.length,m,e,b;for(e=0;e<n;e++)switch(b=f[e],typeof b){case "undefined":case "function":case "unknown":break;default:m&&g.push(","),g.push(mt.n.stringify(b)),m=1}g.push("]");return g.join("")}if(f instanceof Date)return'"'+f.getFullYear()+"-"+d(f.getMonth()+1)+"-"+d(f.getDate())+"T"+d(f.getHours())+":"+d(f.getMinutes())+":"+d(f.getSeconds())+'"';m=["{"];e=mt.n.stringify;for(n in f)if(Object.prototype.hasOwnProperty.call(f,n))switch(b=
f[n],typeof b){case "undefined":case "unknown":case "function":break;default:g&&m.push(","),g=1,m.push(e(n)+":"+e(b))}m.push("}");return m.join("")}}}();mt.lang={};mt.lang.d=function(a,d){return"[object "+d+"]"==={}.toString.call(a)};mt.lang.ya=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.Aa=function(a){return mt.lang.d(a,"String")};mt.localStorage={};
mt.localStorage.t=function(){if(!mt.localStorage.f)try{mt.localStorage.f=document.createElement("input"),mt.localStorage.f.type="hidden",mt.localStorage.f.style.display="none",mt.localStorage.f.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.f)}catch(a){return t}return p};
mt.localStorage.set=function(a,d,g){var f=new Date;f.setTime(f.getTime()+g||31536E6);try{window.localStorage?(d=f.getTime()+"|"+d,window.localStorage.setItem(a,d)):mt.localStorage.t()&&(mt.localStorage.f.expires=f.toUTCString(),mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.setAttribute(a,d),mt.localStorage.f.save(document.location.hostname))}catch(k){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var d=a.indexOf("|"),g=a.substring(0,d)-0;if(g&&g>(new Date).getTime())return a.substring(d+1)}}else if(mt.localStorage.t())try{return mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.getAttribute(a)}catch(f){}return q};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.t())try{mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.removeAttribute(a),mt.localStorage.f.save(document.location.hostname)}catch(d){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,d){if(window.sessionStorage)try{window.sessionStorage.setItem(a,d)}catch(g){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):q};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.H={};mt.H.log=function(a,d){var g=new Image,f="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[f]=g;g.onload=g.onerror=g.onabort=function(){g.onload=g.onerror=g.onabort=q;g=window[f]=q;d&&d(a)};g.src=a};mt.I={};
mt.I.ba=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var d=navigator.plugins["Shockwave Flash"];d&&d.description&&(a=d.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=d.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(g){}return a};
mt.I.ta=function(a,d,g,f,k){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+g+'" height="'+f+'"><param name="movie" value="'+d+'" /><param name="flashvars" value="'+(k||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+g+'" height="'+f+'" src="'+d+'" flashvars="'+(k||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.l=function(a,d){var g=a.match(RegExp("(^|&|\\?|#)("+d+")=([^&#]*)(&|$|#)",""));return g?g[3]:q};mt.url.va=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:q};mt.url.Z=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):q};mt.url.K=function(a){return(a=mt.url.Z(a))?a.replace(/:\d+$/,""):a};mt.url.ua=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):q};
h.k={wa:"http://tongji.baidu.com/hm-web/welcome/ico",P:"hm.baidu.com/hm.gif",S:"baidu.com",ea:"hmmd",fa:"hmpl",da:"hmkw",ca:"hmci",ga:"hmsr",m:0,h:Math.round(+new Date/1E3),protocol:"https:"==document.location.protocol?"https:":"http:",za:0,qa:6E5,ra:10,sa:1024,pa:1,r:2147483647,Q:"cc cf ci ck cl cm cp cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api tt u".split(" ")};
(function(){var a={i:{},e:function(a,g){this.i[a]=this.i[a]||[];this.i[a].push(g)},p:function(a,g){this.i[a]=this.i[a]||[];for(var f=this.i[a].length,k=0;k<f;k++)this.i[a][k](g)}};return h.z=a})();
(function(){function a(a,f){var k=document.createElement("script");k.charset="utf-8";d.d(f,"Function")&&(k.readyState?k.onreadystatechange=function(){if("loaded"===k.readyState||"complete"===k.readyState)k.onreadystatechange=q,f()}:k.onload=function(){f()});k.src=a;var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(k,n)}var d=mt.lang;return h.load=a})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.w.$()+","+h.w.Y();h.b.j()}}function d(){clearTimeout(A);var a;y&&(a="visible"==document[y]);B&&(a=!document[B]);e="undefined"==typeof a?p:a;if((!m||!b)&&e&&l)u=p,s=+new Date;else if(m&&b&&(!e||!l))u=t,r+=+new Date-s;m=e;b=l;A=setTimeout(d,100)}function g(b){var a=document,e="";if(b in a)e=b;else for(var l=["webkit","ms","moz","o"],s=0;s<l.length;s++){var r=l[s]+b.charAt(0).toUpperCase()+b.slice(1);if(r in a){e=
r;break}}return e}function f(b){if(!("focus"==b.type||"blur"==b.type)||!(b.target&&b.target!=window))l="focus"==b.type||"focusin"==b.type?p:t,d()}var k=mt.event,n=h.z,m=p,e=p,b=p,l=p,v=+new Date,s=v,r=0,u=p,y=g("visibilityState"),B=g("hidden"),A;d();(function(){var b=y.replace(/[vV]isibilityState/,"visibilitychange");k.e(document,b,d);k.e(window,"pageshow",d);k.e(window,"pagehide",d);"object"==typeof document.onfocusin?(k.e(document,"focusin",f),k.e(document,"focusout",f)):(k.e(window,"focus",f),
k.e(window,"blur",f))})();h.w={$:function(){return+new Date-v},Y:function(){return u?+new Date-s+r:r}};n.e("pv-b",function(){k.e(window,"unload",a())});return h.w})();
(function(){function a(b){for(var e in b)if({}.hasOwnProperty.call(b,e)){var d=b[e];f.d(d,"Object")||f.d(d,"Array")?a(d):b[e]=String(d)}}function d(b){return b.replace?b.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):b}var g=mt.H,f=mt.lang,k=mt.n,n=h.k,m=h.z,e={L:q,o:[],s:0,M:t,init:function(){e.c=0;e.L={push:function(){e.F.apply(e,arguments)}};m.e("pv-b",function(){e.V();e.W()});m.e("pv-d",e.X);m.e("stag-b",function(){h.b.a.api=e.c||e.s?e.c+"_"+e.s:""});m.e("stag-d",function(){h.b.a.api=
0;e.c=0;e.s=0})},V:function(){var b=window._hmt;if(b&&b.length)for(var a=0;a<b.length;a++){var d=b[a];switch(d[0]){case "_setAccount":1<d.length&&/^[0-9a-z]{32}$/.test(d[1])&&(e.c|=1,window._bdhm_account=d[1]);break;case "_setAutoPageview":if(1<d.length&&(d=d[1],t===d||p===d))e.c|=2,window._bdhm_autoPageview=d}}},W:function(){if("undefined"===typeof window._bdhm_account||window._bdhm_account===c.id){window._bdhm_account=c.id;var b=window._hmt;if(b&&b.length)for(var a=0,d=b.length;a<d;a++)f.d(b[a],
"Array")&&"_trackEvent"!==b[a][0]&&"_trackRTEvent"!==b[a][0]?e.F(b[a]):e.o.push(b[a]);window._hmt=e.L}},X:function(){if(0<e.o.length)for(var b=0,a=e.o.length;b<a;b++)e.F(e.o[b]);e.o=q},F:function(b){if(f.d(b,"Array")){var a=b[0];if(e.hasOwnProperty(a)&&f.d(e[a],"Function"))e[a](b)}},_trackPageview:function(b){if(1<b.length&&b[1].charAt&&"/"==b[1].charAt(0)){e.c|=4;h.b.a.et=0;h.b.a.ep="";h.b.C?(h.b.a.nv=0,h.b.a.st=4):h.b.C=p;var a=h.b.a.u,d=h.b.a.su;h.b.a.u=n.protocol+"//"+document.location.host+b[1];
e.M||(h.b.a.su=document.location.href);h.b.j();h.b.a.u=a;h.b.a.su=d}},_trackEvent:function(b){2<b.length&&(e.c|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=d(b[1])+"*"+d(b[2])+(b[3]?"*"+d(b[3]):"")+(b[4]?"*"+d(b[4]):""),h.b.j())},_setCustomVar:function(b){if(!(4>b.length)){var a=b[1],f=b[4]||3;if(0<a&&6>a&&0<f&&4>f){e.s++;for(var s=(h.b.a.cv||"*").split("!"),r=s.length;r<a-1;r++)s.push("*");s[a-1]=f+"*"+d(b[2])+"*"+d(b[3]);h.b.a.cv=s.join("!");b=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,
"");""!==b?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(b),c.age):h.b.ha("Hm_cv_"+c.id)}}},_setReferrerOverride:function(b){1<b.length&&(h.b.a.su=b[1].charAt&&"/"==b[1].charAt(0)?n.protocol+"//"+window.location.host+b[1]:b[1],e.M=p)},_trackOrder:function(b){b=b[1];f.d(b,"Object")&&(a(b),e.c|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=k.stringify(b),h.b.j())},_trackMobConv:function(b){if(b={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[b[1]])e.c|=32,h.b.a.et=93,h.b.a.ep=b,h.b.j()},_trackRTPageview:function(b){b=
b[1];f.d(b,"Object")&&(a(b),b=k.stringify(b),512>=encodeURIComponent(b).length&&(e.c|=64,h.b.a.rt=b))},_trackRTEvent:function(b){b=b[1];if(f.d(b,"Object")){a(b);b=encodeURIComponent(k.stringify(b));var d=function(b){var a=h.b.a.rt;e.c|=128;h.b.a.et=90;h.b.a.rt=b;h.b.j();h.b.a.rt=a},g=b.length;if(900>=g)d.call(this,b);else for(var g=Math.ceil(g/900),s="block|"+Math.round(Math.random()*n.r).toString(16)+"|"+g+"|",r=[],u=0;u<g;u++)r.push(u),r.push(b.substring(900*u,900*u+900)),d.call(this,s+r.join("|")),
r=[]}},_setUserId:function(b){b=b[1];if(f.d(b,"String")||f.d(b,"Number")){var a=h.b.B(),d="hm-"+h.b.a.v;e.O=e.O||Math.round(Math.random()*n.r);g.log("//datax.baidu.com/x.gif?si="+c.id+"&dm="+encodeURIComponent(a)+"&ac="+encodeURIComponent(b)+"&v="+d+"&li="+e.O+"&rnd="+Math.round(Math.random()*n.r))}}};e.init();h.T=e;return h.T})();
(function(){function a(){"undefined"==typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=p,this.a={},this.C=t,this.init())}var d=mt.url,g=mt.H,f=mt.I,k=mt.lang,n=mt.cookie,m=mt.g,e=mt.localStorage,b=mt.sessionStorage,l=h.k,v=h.z;a.prototype={D:function(b,a){b="."+b.replace(/:\d+/,"");a="."+a.replace(/:\d+/,"");var e=b.indexOf(a);return-1<e&&e+a.length==b.length},N:function(b,a){b=b.replace(/^https?:\/\//,"");return 0===b.indexOf(a)},q:function(b){for(var a=0;a<c.dm.length;a++)if(-1<
c.dm[a].indexOf("/")){if(this.N(b,c.dm[a]))return p}else{var e=d.K(b);if(e&&this.D(e,c.dm[a]))return p}return t},B:function(){for(var b=document.location.hostname,a=0,e=c.dm.length;a<e;a++)if(this.D(b,c.dm[a]))return c.dm[a].replace(/(:\d+)?[\/\?#].*/,"");return b},J:function(){for(var b=0,a=c.dm.length;b<a;b++){var e=c.dm[b];if(-1<e.indexOf("/")&&this.N(document.location.href,e))return e.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},aa:function(){if(!document.referrer)return l.h-l.m>c.vdur?1:4;var b=
t;this.q(document.referrer)&&this.q(document.location.href)?b=p:(b=d.K(document.referrer),b=this.D(b||"",document.location.hostname));return b?l.h-l.m>c.vdur?1:4:3},getData:function(a){try{return n.get(a)||b.get(a)||e.get(a)}catch(d){}},setData:function(a,d,f){try{n.set(a,d,{domain:this.B(),path:this.J(),A:f}),f?e.set(a,d,f):b.set(a,d)}catch(g){}},ha:function(a){try{n.set(a,"",{domain:this.B(),path:this.J(),A:-1}),b.remove(a),e.remove(a)}catch(d){}},na:function(){var a,b,e,d,f;l.m=this.getData("Hm_lpvt_"+
c.id)||0;13==l.m.length&&(l.m=Math.round(l.m/1E3));b=this.aa();a=4!=b?1:0;if(e=this.getData("Hm_lvt_"+c.id)){d=e.split(",");for(f=d.length-1;0<=f;f--)13==d[f].length&&(d[f]=""+Math.round(d[f]/1E3));for(;2592E3<l.h-d[0];)d.shift();f=4>d.length?2:3;for(1===a&&d.push(l.h);4<d.length;)d.shift();e=d.join(",");d=d[d.length-1]}else e=l.h,d="",f=1;this.setData("Hm_lvt_"+c.id,e,c.age);this.setData("Hm_lpvt_"+c.id,l.h);e=l.h==this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.q(document.location.href)&&
(""===document.referrer||this.q(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=e;this.a.lt=d;this.a.lv=f},ma:function(){for(var a=[],b=0,e=l.Q.length;b<e;b++){var d=l.Q[b],f=this.a[d];"undefined"!=typeof f&&""!==f&&a.push(d+"="+encodeURIComponent(f))}b=this.a.et;this.a.rt&&(0===b?a.push("rt="+encodeURIComponent(this.a.rt)):90===b&&a.push("rt="+this.a.rt));return a.join("&")},oa:function(){this.na();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=m.ia;this.a.cl=m.colorDepth+"-bit";
this.a.ln=m.language;this.a.ja=m.javaEnabled?1:0;this.a.ck=m.cookieEnabled?1:0;this.a.lo="number"==typeof _bdhm_top?1:0;this.a.fl=f.ba();this.a.v="1.0.81";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");1==this.a.nv&&(this.a.tt=document.title||"");var a=document.location.href;this.a.cm=d.l(a,l.ea)||"";this.a.cp=d.l(a,l.fa)||"";this.a.cw=d.l(a,l.da)||"";this.a.ci=d.l(a,l.ca)||"";this.a.cf=d.l(a,l.ga)||""},init:function(){try{this.oa(),0===this.a.nv?this.la():this.G(".*"),h.b=this,this.U(),
v.p("pv-b"),this.ka()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));g.log(l.protocol+"//"+l.P+"?"+b.join("&"))}},ka:function(){function a(){v.p("pv-d")}"undefined"===typeof window._bdhm_autoPageview||window._bdhm_autoPageview===p?(this.C=p,this.a.et=0,this.a.ep="",this.j(a)):a()},j:function(a){var b=this;b.a.rnd=Math.round(Math.random()*l.r);v.p("stag-b");var e=l.protocol+"//"+
l.P+"?"+b.ma();v.p("stag-d");b.R(e);g.log(e,function(e){b.G(e);k.d(a,"Function")&&a.call(b)})},U:function(){var a=document.location.hash.substring(1),b=RegExp(c.id),e=-1<document.referrer.indexOf(l.S)?p:t,f=d.l(a,"jn"),g=/^heatlink$|^select$/.test(f);a&&(b.test(a)&&e&&g)&&(a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",l.protocol+"//"+c.js+f+".js?"+this.a.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(a,
f))},R:function(a){var e=b.get("Hm_unsent_"+c.id)||"",d=this.a.u?"":"&u="+encodeURIComponent(document.location.href),e=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(e?","+e:"");b.set("Hm_unsent_"+c.id,e)},G:function(a){var e=b.get("Hm_unsent_"+c.id)||"";e&&((e=e.replace(RegExp(encodeURIComponent(a.replace(/^https?:\/\//,"")).replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),"").replace(/,$/,""))?b.set("Hm_unsent_"+c.id,e):b.remove("Hm_unsent_"+c.id))},la:function(){var a=this,e=b.get("Hm_unsent_"+
c.id);if(e)for(var e=e.split(","),d=function(b){g.log(l.protocol+"//"+decodeURIComponent(b).replace(/^https?:\/\//,""),function(b){a.G(b)})},f=0,k=e.length;f<k;f++)d(e[f])}};return new a})();var w=h.k,x=h.load;if(c.apps){var z=[w.protocol,"//ers.baidu.com/app/s.js?"];z.push(c.apps);x(z.join(""))}var C=h.k,D=h.load;if(c.conv&&"http:"===C.protocol){var E=["http://page.baidu.com/conversion_js.php?sid="];E.push(c.conv);D(E.join(""))}var F=h.k,G=h.load;
c.lxb&&G([F.protocol,"//lxbjs.baidu.com/lxb.js?sid=",c.lxb].join(""));var H=h.load,I=h.k.protocol;if(c.qiao){for(var J=[I+"//goutong.baidu.com/site/"],K=c.id,L=5381,M=K.length,N=0;N<M;N++)L=(33*L+Number(K.charCodeAt(N)))%4294967296;2147483648<L&&(L-=2147483648);J.push(L%1E3+"/");J.push(c.id+"/b.js");J.push("?siteId="+c.qiao);H(J.join(""))}
(function(){if("378f3aa9b8779062c8de4dc247dd8874"===c.id){var a=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},d={click:function(){for(var e=[],b=a(document.getElementsByTagName("a")),b=[].concat.apply(b,a(document.getElementsByTagName("area"))),d=/openZoosUrl\(/,f=0,g=b.length;f<g;f++)d.test(b[f].getAttribute("onclick"))&&e.push(b[f]);return e}},g=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===t)return t},f=function(a,
b){return Object.prototype.toString.call(a)==="[object "+b+"]"};window._hmt=window._hmt||[];var k,n="/zoosnet"+(/\/$/.test("/zoosnet")?"":"/"),m=function(a,b){if(k===b){window._hmt.push(["_trackPageview",n+a]);for(var d=+new Date;500>=+new Date-d;);return t}if(f(b,"Array")||f(b,"NodeList"))for(var d=0,g=b.length;d<g;d++)if(k===b[d]){window._hmt.push(["_trackPageview",n+a+"/"+(d+1)]);for(d=+new Date;500>=+new Date-d;);return t}};(function(a,b,d){a.addEventListener?a.addEventListener(b,d,p):a.attachEvent&&
a.attachEvent("on"+b,d)})(document,"click",function(a){a=a||window.event;k=a.target||a.srcElement;var b={};for(g(d,function(a,d){b[a]=f(d,"Function")?d():document.getElementById(d)});k&&k!==document&&g(b,m)!==t;)k=k.parentNode})}})();})();
