package com.cnit.yoyo.dao.member;

import com.cnit.yoyo.model.member.Clerks;

public interface ClerkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_storemember
     *
     * @mbggenerated Wed Mar 11 18:44:21 CST 2015
     */
    int deleteByPrimaryKey(Long attachId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_storemember
     *
     * @mbggenerated Wed Mar 11 18:44:21 CST 2015
     */
    int insert(Clerks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_storemember
     *
     * @mbggenerated Wed Mar 11 18:44:21 CST 2015
     */
    int insertSelective(Clerks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_storemember
     *
     * @mbggenerated Wed Mar 11 18:44:21 CST 2015
     */
    Clerks selectByPrimaryKey(Long attachId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_storemember
     *
     * @mbggenerated Wed Mar 11 18:44:21 CST 2015
     */
    int updateByPrimaryKeySelective(Clerks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_storemember
     *
     * @mbggenerated Wed Mar 11 18:44:21 CST 2015
     */
    int updateByPrimaryKey(Clerks record);
    
    int findStoreMemByMemid(Long memId);
    
    int updateById(Clerks record);
    
    Clerks getStoreMemByMemid(Long memId);
    int findClerksByRoleId(int roleId);
    /**根据公司id删除店员*/
    int deleteByCompanyId(Integer [] ids);
    
    
}