package com.cnit.yoyo.dao.member;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cnit.yoyo.domain.member.MemberCommentDo;
import com.cnit.yoyo.model.member.MemberComment;
import com.cnit.yoyo.model.member.MemberCommentWithBLOBs;
import com.cnit.yoyo.model.member.dto.MemberCommentDTO;
import com.cnit.yoyo.model.member.dto.MemberCommentDetailDTO;
import com.cnit.yoyo.model.member.dto.MemberCommentQryDTO;

public interface MemberCommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_member_comments
	 * @mbggenerated  Thu Mar 05 10:09:08 CST 2015
	 */
	int deleteByPrimaryKey(Integer commentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_member_comments
	 * @mbggenerated  Thu Mar 05 10:09:08 CST 2015
	 */
	int insert(MemberCommentWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_member_comments
	 * @mbggenerated  Thu Mar 05 10:09:08 CST 2015
	 */
	int insertSelective(MemberCommentWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_member_comments
	 * @mbggenerated  Thu Mar 05 10:09:08 CST 2015
	 */
	MemberCommentWithBLOBs selectByPrimaryKey(Integer commentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_member_comments
	 * @mbggenerated  Thu Mar 05 10:09:08 CST 2015
	 */
	int updateByPrimaryKeySelective(MemberCommentWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_member_comments
	 * @mbggenerated  Thu Mar 05 10:09:08 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(MemberCommentWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_member_comments
	 * @mbggenerated  Thu Mar 05 10:09:08 CST 2015
	 */
	int updateByPrimaryKey(MemberComment record);
	
	/**
	  * @description <b>商家查询评论列表</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-4-20
	  * @param @param obj
	  * @param @return
	  * @return List<MemberCommentDTO>
	*/
	List<Object> findCommentsForBusiness(MemberCommentQryDTO commentQryDTO);
	
	
	List<Object> findCommentsForBusinessCount(MemberCommentQryDTO commentQryDTO);
	/**
	  * @description <b>查询咨询列表数据</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-4-21
	  * @param @param params
	  * @param @return
	  * @return List<MemberCommentDo>
	*/
	List<MemberCommentDo> findMemberAskByParam(MemberCommentQryDTO params);
	
	
	
	MemberCommentDTO findMemberAskById(Long commentId);
	
	
	/**
	  * @description <b>批量删除评论信息(逻辑删除)</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-4-23
	  * @param @param commentIds
	  * @param @return
	  * @return int
	*/
	int batchDeleteMemberComment(String [] commentIds);

	/**
	  * @description <b>批量修改评论显示或关闭</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-4-23
	  * @param @param params
	  * @param @return
	  * @return int
	*/
	int batchUpdateMemberCommentDisplay(Map<String, Object> params);
	
	/**
	 * @Title:  selectOrderCommentByGoodsId  
	 * @Description:  TODO(根据商品id查询评论)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-13 下午2:30:49  
	 * @version 1.0.0 
	 * @param @param goodsId
	 * @param @return
	 * @return List<Object>  返回类型 
	 * @throws
	 */
	List<MemberCommentDetailDTO> selectOrderCommentByGoodsId(Integer goodsId);
	
	/**
	 * @Title:  selectDiscussCommentByGoodsId  
	 * @Description:  TODO(根据商品id查询商品咨询)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-13 下午3:21:47  
	 * @version 1.0.0 
	 * @param @param goodsId
	 * @param @param keywordsList
	 * @param @return
	 * @return List<MemberCommentWithBLOBs>  返回类型 
	 * @throws
	 */
	List<MemberCommentDetailDTO> selectDiscussCommentByGoodsId(@Param("goodsId") Integer goodsId, @Param("list") List<String> keywordsList);
	
	
	/**
	 * @Title:  selectCommentCountByGoodsId  
	 * @Description:  TODO(根据商品id查询评论数量)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-16 下午6:36:33  
	 * @version 1.0.0 
	 * @param @param goodsId
	 * @param @return
	 * @return Long  返回类型 
	 * @throws
	 */
	Long selectCommentCountByGoodsId(Integer goodsId);
	
	/**
	 * @Title:  selectCommentCountByGoodsIdAndPoint  
	 * @Description:  TODO(根据商品id和评分列表查询评论数量)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-16 下午6:37:34  
	 * @version 1.0.0 
	 * @param @param goodsId
	 * @param @param pointList
	 * @param @return
	 * @return Long  返回类型 
	 * @throws
	 */
	Long selectCommentCountByGoodsIdAndPoint(@Param("goodsId")Integer goodsId, @Param("list")List<Integer> pointList);
	
	/**
	  * @description <b>查询会员评论数量</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-5-16
	  * @param @param memberId
	  * @param @return
	  * @return List<Integer>
	*/
	List<Object> selectMemberCommentCount(Integer memberId);

	/**
	  * @description <b>查询会员咨询数量</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-5-16
	  * @param @param memberId
	  * @param @return
	  * @return List<Integer>
	*/
	List<Object> selectMemberConsultCount(MemberCommentQryDTO memberCommentQryDTO);
	
	/**
	  * @description <b>查询商品咨询数量</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-5-16
	  * @param @param memberId
	  * @param @return
	  * @return List<Integer>
	*/
	List<Object> selectGoodsConsultCount(MemberCommentQryDTO memberCommentQryDTO);
	
	/**
	  * @description <b>查询用户的评论信息</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-5-15
	  * @param @param memberId
	  * @param @return
	  * @return List<MemberCommentWithBLOBs>
	*/
	List<Object> selectMemberComment(MemberCommentQryDTO commentQryDTO);
	
	
	/**
	  * @description <b>查询用户的咨询信息</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-5-18
	  * @param @param commentQryDTO
	  * @param @return
	  * @return List<Object>
	*/
	List<Object> selectMemberConsult(MemberCommentQryDTO commentQryDTO);
	
	/**
	  * @description <b>查询商品咨询</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-5-16
	  * @param @param memberId
	  * @param @return
	  * @return List<Integer>
	*/
	List<Object> selectGoodsConsult(MemberCommentQryDTO memberId);
	
	/**
	  * @description <b>查看用户评论的回复信息</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-5-16
	  * @param @param commentQryDTO
	  * @param @return
	  * @return List<MemberCommentWithBLOBs>
	*/
	List<MemberCommentWithBLOBs> selectMemberCommentReply(MemberCommentQryDTO commentQryDTO);
	
	/**
	 * @Title:  selectCommentCountByProductId  
	 * @Description:  TODO(根据货品id查询评论总数)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-18 下午5:15:48  
	 * @version 1.0.0 
	 * @param @param productId
	 * @param @return
	 * @return Long  返回类型 
	 * @throws
	 */
	Long selectCommentCountByProductId(Long productId);
	
	/**
	 * @Title:  selectSumPointByProductId  
	 * @Description:  TODO(根据货品id查询评分总数)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-18 下午5:22:54  
	 * @version 1.0.0 
	 * @param @param productId
	 * @param @return
	 * @return Long  返回类型 
	 * @throws
	 */
	Long selectSumPointByProductId(Long productId);
	
	/**
	 * @Title:  selectReplyByCommentId  
	 * @Description:  TODO(根据评论id查询回复列表)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-19 下午7:50:05  
	 * @version 1.0.0 
	 * @param @param commentId
	 * @param @return
	 * @return Integer  返回类型 
	 * @throws
	 */
	List<MemberCommentDetailDTO> selectReplyByCommentId(Integer commentId);//???????????????????
	
	/**
	 * @Title:  selectReplyCountByCommentId  
	 * @Description:  TODO(根据评论id查询回复数量)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-19 下午8:15:38  
	 * @version 1.0.0 
	 * @param @param commentId
	 * @param @return
	 * @return Integer  返回类型 
	 * @throws
	 */
	Integer selectReplyCountByCommentId(Integer commentId);
	
	
	/**
	 * @Title:  selectCommentByBLOBs  
	 * @Description:  TODO(根据给定的例子查询对象)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-20 上午10:22:06  
	 * @version 1.0.0 
	 * @param @param comment
	 * @param @return
	 * @return List<>  返回类型 
	 * @throws
	 */
	List<MemberCommentDetailDTO> selectCommentByBLOBs(MemberCommentWithBLOBs comment);
	
	/**
	 * @Title:  selectCommentById  
	 * @Description:  TODO(根据评论id查询评论对象)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-20 下午5:03:03  
	 * @version 1.0.0 
	 * @param @param commentId
	 * @param @return
	 * @return List<MemberCommentDetailDTO>  返回类型 
	 * @throws
	 */
	MemberCommentDetailDTO selectCommentById(Integer commentId);
	
	/**
	 * @Title:  selectCommentOrReplyById  
	 * @Description:  TODO(根据评论id查询评论或回复对象)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-21 上午9:52:30  
	 * @version 1.0.0 
	 * @param @param commentId
	 * @param @return
	 * @return MemberCommentDetailDTO  返回类型 
	 * @throws
	 */
	MemberCommentDetailDTO selectReplyById(Integer commentId);
	
	/**
	 * @Title:  selectOrderCommentCountByProductId  
	 * @Description:  TODO(根据货品id查询评论数量)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-27 下午2:35:07  
	 * @version 1.0.0 
	 * @param @param productId
	 * @param @return
	 * @return List<MemberCommentDetailDTO>  返回类型 
	 * @throws
	 */
	Integer selectOrderCommentCountByProductId(Integer productId);
	
	/**
	 * @Title:  selectOrderCommentCountByGoodsId  
	 * @Description:  TODO(根据商品id查询评论数量)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-5-27 下午4:18:49  
	 * @version 1.0.0 
	 * @param @param productId
	 * @param @return
	 * @return Integer  返回类型 
	 * @throws
	 */
	Integer selectOrderCommentCountByGoodsId(Integer goodsId);
}