package com.cnit.yoyo.dao.member;

import com.cnit.yoyo.model.member.PamLogPlat;

public interface PamLogPlatMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_pam_log_plat
     * @mbggenerated  Mon Feb 09 17:07:07 CST 2015
     */
    int deleteByPrimaryKey(String eventId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_pam_log_plat
     * @mbggenerated  Mon Feb 09 17:07:07 CST 2015
     */
    int insert(PamLogPlat record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_pam_log_plat
     * @mbggenerated  Mon Feb 09 17:07:07 CST 2015
     */
    int insertSelective(PamLogPlat record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_pam_log_plat
     * @mbggenerated  Mon Feb 09 17:07:07 CST 2015
     */
    PamLogPlat selectByPrimaryKey(String eventId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_pam_log_plat
     * @mbggenerated  Mon Feb 09 17:07:07 CST 2015
     */
    int updateByPrimaryKeySelective(PamLogPlat record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_pam_log_plat
     * @mbggenerated  Mon Feb 09 17:07:07 CST 2015
     */
    int updateByPrimaryKey(PamLogPlat record);
}