package com.cnit.yoyo.dao.article;

import com.cnit.yoyo.model.article.ArticleBody;
import com.cnit.yoyo.model.article.ArticleBodyExample;
import com.cnit.yoyo.model.article.ArticleBodyWithBLOBs;
import com.cnit.yoyo.model.article.dto.ArticleDto;
import com.cnit.yoyo.model.article.dto.ArticleQryDto;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleBodyMapper {
    
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_bodys
	 * @mbggenerated  Mon Jul 06 17:33:14 CST 2015
	 */
	int countByExample(ArticleBodyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_bodys
	 * @mbggenerated  Mon Jul 06 17:33:14 CST 2015
	 */
	int deleteByExample(ArticleBodyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_bodys
	 * @mbggenerated  Mon Jul 06 17:33:14 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_bodys
	 * @mbggenerated  Mon Jul 06 17:33:14 CST 2015
	 */
	int insert(ArticleBodyWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_bodys
	 * @mbggenerated  Mon Jul 06 17:33:14 CST 2015
	 */
	int insertSelective(ArticleBodyWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_bodys
	 * @mbggenerated  Mon Jul 06 17:33:14 CST 2015
	 */
	List<ArticleBodyWithBLOBs> selectByExampleWithBLOBs(
			ArticleBodyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_bodys
	 * @mbggenerated  Mon Jul 06 17:33:14 CST 2015
	 */
	List<ArticleBody> selectByExample(ArticleBodyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_bodys
	 * @mbggenerated  Mon Jul 06 17:33:14 CST 2015
	 */
	ArticleBodyWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_bodys
	 * @mbggenerated  Mon Jul 06 17:33:14 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ArticleBodyWithBLOBs record,
			@Param("example") ArticleBodyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_bodys
	 * @mbggenerated  Mon Jul 06 17:33:14 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") ArticleBodyWithBLOBs record,
			@Param("example") ArticleBodyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_bodys
	 * @mbggenerated  Mon Jul 06 17:33:14 CST 2015
	 */
	int updateByExample(@Param("record") ArticleBody record,
			@Param("example") ArticleBodyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_bodys
	 * @mbggenerated  Mon Jul 06 17:33:14 CST 2015
	 */
	int updateByPrimaryKeySelective(ArticleBodyWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_bodys
	 * @mbggenerated  Mon Jul 06 17:33:14 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(ArticleBodyWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_bodys
	 * @mbggenerated  Mon Jul 06 17:33:14 CST 2015
	 */
	int updateByPrimaryKey(ArticleBody record);
	
	/**
	 * @Title:  selectByQryDto  
	 * @Description:  TODO(根据参数查询对象)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-7-6 下午5:48:31  
	 * @version 1.0.0 
	 * @param @param dto
	 * @param @return
	 * @return List<ArticleDto>  返回类型 
	 * @throws
	 */
	List<ArticleDto> selectByQryDto(ArticleQryDto dto);
	
	/**
	 * @Title:  selectByTitle  
	 * @Description:  TODO(根据文章标题查询文章)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-7-8 下午5:21:42  
	 * @version 1.0.0 
	 * @param @param title
	 * @param @return
	 * @return List<ArticleDto>  返回类型 
	 * @throws
	 */
	List<ArticleDto> selectByTitle(String title);
	
	/**
	 * @Title:  selectById  
	 * @Description:  TODO(根据id查询文章)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-7-9 上午10:00:12  
	 * @version 1.0.0 
	 * @param @param id
	 * @param @return
	 * @return ArticleDto  返回类型 
	 * @throws
	 */
	ArticleDto selectById(Integer id);
	/**
	 * 
	 *@description <根据articleId查询文章内容>
	 *@detail <方法详细描述>
	 *@author <a href="jpzhou@cnit.com">周加平</a>
	 *@version 1.0.0
	 *@data 2015年7月17日
	 *@param articleId
	 *@return
	 */
	ArticleDto selectByArticleId(Integer articleId);
}