package com.cnit.yoyo.dao.article;

import com.cnit.yoyo.model.article.ArticleIndex;
import com.cnit.yoyo.model.article.ArticleIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleIndexMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_indexs
	 * @mbggenerated  Mon Jul 06 17:33:18 CST 2015
	 */
	int countByExample(ArticleIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_indexs
	 * @mbggenerated  Mon Jul 06 17:33:18 CST 2015
	 */
	int deleteByExample(ArticleIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_indexs
	 * @mbggenerated  Mon Jul 06 17:33:18 CST 2015
	 */
	int deleteByPrimaryKey(Integer articleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_indexs
	 * @mbggenerated  Mon Jul 06 17:33:18 CST 2015
	 */
	int insert(ArticleIndex record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_indexs
	 * @mbggenerated  Mon Jul 06 17:33:18 CST 2015
	 */
	int insertSelective(ArticleIndex record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_indexs
	 * @mbggenerated  Mon Jul 06 17:33:18 CST 2015
	 */
	List<ArticleIndex> selectByExample(ArticleIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_indexs
	 * @mbggenerated  Mon Jul 06 17:33:18 CST 2015
	 */
	ArticleIndex selectByPrimaryKey(Integer articleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_indexs
	 * @mbggenerated  Mon Jul 06 17:33:18 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ArticleIndex record,
			@Param("example") ArticleIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_indexs
	 * @mbggenerated  Mon Jul 06 17:33:18 CST 2015
	 */
	int updateByExample(@Param("record") ArticleIndex record,
			@Param("example") ArticleIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_indexs
	 * @mbggenerated  Mon Jul 06 17:33:18 CST 2015
	 */
	int updateByPrimaryKeySelective(ArticleIndex record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_indexs
	 * @mbggenerated  Mon Jul 06 17:33:18 CST 2015
	 */
	int updateByPrimaryKey(ArticleIndex record);
	
	/**
	 * @Title:  updateDisabledPrimaryKey  
	 * @Description:  TODO(更新disabled状态)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-7-9 上午11:34:18  
	 * @version 1.0.0 
	 * @param @param articleList
	 * @param @param disabled
	 * @param @return
	 * @return int  返回类型 
	 * @throws
	 */
	int updateDisabledByPrimaryKey(@Param("list")List<Integer> articleList, @Param("disabled")Integer disabled);
	
	/**
	 * @Title:  updateDisabledByNodeId  
	 * @Description:  TODO(根据栏目id更新disabled状态)  
	 * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
	 * @date 2015-7-9 下午1:29:18  
	 * @version 1.0.0 
	 * @param @param nodeId
	 * @param @param disabled
	 * @param @return
	 * @return int  返回类型 
	 * @throws
	 */
	int updateDisabledByNodeId(@Param("nodeId")Integer nodeId, @Param("disabled")Integer disabled);
}