package com.cnit.yoyo.dao.system;

import java.util.List;

import com.cnit.yoyo.model.system.SiteRole;
import com.cnit.yoyo.model.system.SiteRoleWithBLOBs;
import com.cnit.yoyo.model.system.dto.ShopRoleListDTO;
import com.cnit.yoyo.model.system.dto.SiteRoleListDTO;

public interface SiteRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_roles
     *
     * @mbggenerated Thu Jun 04 13:18:32 CST 2015
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_roles
     *
     * @mbggenerated Thu Jun 04 13:18:32 CST 2015
     */
    int insert(SiteRoleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_roles
     *
     * @mbggenerated Thu Jun 04 13:18:32 CST 2015
     */
    int insertSelective(SiteRoleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_roles
     *
     * @mbggenerated Thu Jun 04 13:18:32 CST 2015
     */
    SiteRoleWithBLOBs selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_roles
     *
     * @mbggenerated Thu Jun 04 13:18:32 CST 2015
     */
    int updateByPrimaryKeySelective(SiteRoleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_roles
     *
     * @mbggenerated Thu Jun 04 13:18:32 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(SiteRoleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_roles
     *
     * @mbggenerated Thu Jun 04 13:18:32 CST 2015
     */
    int updateByPrimaryKey(SiteRole record);

	List<ShopRoleListDTO> selectAllRoleResource();
	
	SiteRole findByRolename(String roleName);

	List<SiteRole> findSelect();

	SiteRole findRoleByUserName(String loginName);
}