package com.cnit.yoyo.model.article;

import java.io.Serializable;
import java.util.List;

public class ArticleNodesWithBLOBs extends ArticleNodes implements Serializable {

	//增加子节点和文章索引
	private List<ArticleNodesWithBLOBs> children;
	private List<ArticleIndex> articleIndexList;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_content_article_nodes.seo_description
	 * @mbggenerated  Thu Jun 25 14:58:01 CST 2015
	 */
	private String seoDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_content_article_nodes.content
	 * @mbggenerated  Thu Jun 25 14:58:01 CST 2015
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_content_article_nodes
	 * @mbggenerated  Thu Jun 25 14:58:01 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_content_article_nodes.seo_description
	 * @return  the value of t_content_article_nodes.seo_description
	 * @mbggenerated  Thu Jun 25 14:58:01 CST 2015
	 */
	public String getSeoDescription() {
		return seoDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_content_article_nodes.seo_description
	 * @param seoDescription  the value for t_content_article_nodes.seo_description
	 * @mbggenerated  Thu Jun 25 14:58:01 CST 2015
	 */
	public void setSeoDescription(String seoDescription) {
		this.seoDescription = seoDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_content_article_nodes.content
	 * @return  the value of t_content_article_nodes.content
	 * @mbggenerated  Thu Jun 25 14:58:01 CST 2015
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_content_article_nodes.content
	 * @param content  the value for t_content_article_nodes.content
	 * @mbggenerated  Thu Jun 25 14:58:01 CST 2015
	 */
	public void setContent(String content) {
		this.content = content;
	}
	

	public List<ArticleNodesWithBLOBs> getChildren() {
		return children;
	}

	public void setChildren(List<ArticleNodesWithBLOBs> children) {
		this.children = children;
	}

	public List<ArticleIndex> getArticleIndexList() {
		return articleIndexList;
	}

	public void setArticleIndexList(List<ArticleIndex> articleIndexList) {
		this.articleIndexList = articleIndexList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_nodes
	 * @mbggenerated  Thu Jun 25 14:58:01 CST 2015
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", seoDescription=").append(seoDescription);
		sb.append(", content=").append(content);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_nodes
	 * @mbggenerated  Thu Jun 25 14:58:01 CST 2015
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ArticleNodesWithBLOBs other = (ArticleNodesWithBLOBs) that;
		return (this.getNodeId() == null ? other.getNodeId() == null : this
				.getNodeId().equals(other.getNodeId()))
				&& (this.getParentId() == null ? other.getParentId() == null
						: this.getParentId().equals(other.getParentId()))
				&& (this.getNodeDepth() == null ? other.getNodeDepth() == null
						: this.getNodeDepth().equals(other.getNodeDepth()))
				&& (this.getNodeName() == null ? other.getNodeName() == null
						: this.getNodeName().equals(other.getNodeName()))
				&& (this.getNodePagename() == null ? other.getNodePagename() == null
						: this.getNodePagename()
								.equals(other.getNodePagename()))
				&& (this.getNodePath() == null ? other.getNodePath() == null
						: this.getNodePath().equals(other.getNodePath()))
				&& (this.getSeoTitle() == null ? other.getSeoTitle() == null
						: this.getSeoTitle().equals(other.getSeoTitle()))
				&& (this.getSeoKeywords() == null ? other.getSeoKeywords() == null
						: this.getSeoKeywords().equals(other.getSeoKeywords()))
				&& (this.getIfpub() == null ? other.getIfpub() == null : this
						.getIfpub().equals(other.getIfpub()))
				&& (this.getHasChildren() == null ? other.getHasChildren() == null
						: this.getHasChildren().equals(other.getHasChildren()))
				&& (this.getHasimage() == null ? other.getHasimage() == null
						: this.getHasimage().equals(other.getHasimage()))
				&& (this.getOrdernum() == null ? other.getOrdernum() == null
						: this.getOrdernum().equals(other.getOrdernum()))
				&& (this.getHomepage() == null ? other.getHomepage() == null
						: this.getHomepage().equals(other.getHomepage()))
				&& (this.getUptime() == null ? other.getUptime() == null : this
						.getUptime().equals(other.getUptime()))
				&& (this.getTmplPath() == null ? other.getTmplPath() == null
						: this.getTmplPath().equals(other.getTmplPath()))
				&& (this.getListTmplPath() == null ? other.getListTmplPath() == null
						: this.getListTmplPath()
								.equals(other.getListTmplPath()))
				&& (this.getDisabled() == null ? other.getDisabled() == null
						: this.getDisabled().equals(other.getDisabled()))
				&& (this.getDeletable() == null ? other.getDeletable() == null
						: this.getDeletable().equals(other.getDeletable()))
				&& (this.getSeoDescription() == null ? other
						.getSeoDescription() == null : this.getSeoDescription()
						.equals(other.getSeoDescription()))
				&& (this.getContent() == null ? other.getContent() == null
						: this.getContent().equals(other.getContent()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_content_article_nodes
	 * @mbggenerated  Thu Jun 25 14:58:01 CST 2015
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getNodeId() == null) ? 0 : getNodeId().hashCode());
		result = prime * result
				+ ((getParentId() == null) ? 0 : getParentId().hashCode());
		result = prime * result
				+ ((getNodeDepth() == null) ? 0 : getNodeDepth().hashCode());
		result = prime * result
				+ ((getNodeName() == null) ? 0 : getNodeName().hashCode());
		result = prime
				* result
				+ ((getNodePagename() == null) ? 0 : getNodePagename()
						.hashCode());
		result = prime * result
				+ ((getNodePath() == null) ? 0 : getNodePath().hashCode());
		result = prime * result
				+ ((getSeoTitle() == null) ? 0 : getSeoTitle().hashCode());
		result = prime
				* result
				+ ((getSeoKeywords() == null) ? 0 : getSeoKeywords().hashCode());
		result = prime * result
				+ ((getIfpub() == null) ? 0 : getIfpub().hashCode());
		result = prime
				* result
				+ ((getHasChildren() == null) ? 0 : getHasChildren().hashCode());
		result = prime * result
				+ ((getHasimage() == null) ? 0 : getHasimage().hashCode());
		result = prime * result
				+ ((getOrdernum() == null) ? 0 : getOrdernum().hashCode());
		result = prime * result
				+ ((getHomepage() == null) ? 0 : getHomepage().hashCode());
		result = prime * result
				+ ((getUptime() == null) ? 0 : getUptime().hashCode());
		result = prime * result
				+ ((getTmplPath() == null) ? 0 : getTmplPath().hashCode());
		result = prime
				* result
				+ ((getListTmplPath() == null) ? 0 : getListTmplPath()
						.hashCode());
		result = prime * result
				+ ((getDisabled() == null) ? 0 : getDisabled().hashCode());
		result = prime * result
				+ ((getDeletable() == null) ? 0 : getDeletable().hashCode());
		result = prime
				* result
				+ ((getSeoDescription() == null) ? 0 : getSeoDescription()
						.hashCode());
		result = prime * result
				+ ((getContent() == null) ? 0 : getContent().hashCode());
		return result;
	}
}