package com.cnit.yoyo.model.order;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.cnit.yoyo.dto.BaseQryDTO;

public class RedbeltDetail extends BaseQryDTO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redbelt_detail.id
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redbelt_detail.redbelt_id
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    private Long redbeltId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redbelt_detail.member_id
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redbelt_detail.user_name
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redbelt_detail.amount
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redbelt_detail.status
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redbelt_detail.create_time
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redbelt_detail.use_time
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    private Date useTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_redbelt_detail
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redbelt_detail.id
     *
     * @return the value of t_redbelt_detail.id
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redbelt_detail.id
     *
     * @param id the value for t_redbelt_detail.id
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redbelt_detail.redbelt_id
     *
     * @return the value of t_redbelt_detail.redbelt_id
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public Long getRedbeltId() {
        return redbeltId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redbelt_detail.redbelt_id
     *
     * @param redbeltId the value for t_redbelt_detail.redbelt_id
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public void setRedbeltId(Long redbeltId) {
        this.redbeltId = redbeltId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redbelt_detail.member_id
     *
     * @return the value of t_redbelt_detail.member_id
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redbelt_detail.member_id
     *
     * @param memberId the value for t_redbelt_detail.member_id
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redbelt_detail.user_name
     *
     * @return the value of t_redbelt_detail.user_name
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redbelt_detail.user_name
     *
     * @param userName the value for t_redbelt_detail.user_name
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redbelt_detail.amount
     *
     * @return the value of t_redbelt_detail.amount
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redbelt_detail.amount
     *
     * @param amount the value for t_redbelt_detail.amount
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redbelt_detail.status
     *
     * @return the value of t_redbelt_detail.status
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redbelt_detail.status
     *
     * @param status the value for t_redbelt_detail.status
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redbelt_detail.create_time
     *
     * @return the value of t_redbelt_detail.create_time
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redbelt_detail.create_time
     *
     * @param createTime the value for t_redbelt_detail.create_time
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redbelt_detail.use_time
     *
     * @return the value of t_redbelt_detail.use_time
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public Date getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redbelt_detail.use_time
     *
     * @param useTime the value for t_redbelt_detail.use_time
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redbelt_detail
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", redbeltId=").append(redbeltId);
        sb.append(", memberId=").append(memberId);
        sb.append(", userName=").append(userName);
        sb.append(", amount=").append(amount);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", useTime=").append(useTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redbelt_detail
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RedbeltDetail other = (RedbeltDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRedbeltId() == null ? other.getRedbeltId() == null : this.getRedbeltId().equals(other.getRedbeltId()))
            && (this.getMemberId() == null ? other.getMemberId() == null : this.getMemberId().equals(other.getMemberId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUseTime() == null ? other.getUseTime() == null : this.getUseTime().equals(other.getUseTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redbelt_detail
     *
     * @mbggenerated Mon Sep 28 16:08:19 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRedbeltId() == null) ? 0 : getRedbeltId().hashCode());
        result = prime * result + ((getMemberId() == null) ? 0 : getMemberId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUseTime() == null) ? 0 : getUseTime().hashCode());
        return result;
    }
}