package com.cnit.yoyo.dao.car;

import com.cnit.yoyo.model.car.CarDataListValue;
import com.cnit.yoyo.model.car.CarDataString;

public interface CarDataStringMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_data_string
     *
     * @mbggenerated Tue Mar 31 10:36:00 CST 2015
     */
    int deleteByPrimaryKey(CarDataString key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_data_string
     *
     * @mbggenerated Tue Mar 31 10:36:00 CST 2015
     */
    int insert(CarDataString record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_data_string
     *
     * @mbggenerated Tue Mar 31 10:36:00 CST 2015
     */
    int insertSelective(CarDataString record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_data_string
     *
     * @mbggenerated Tue Mar 31 10:36:00 CST 2015
     */
    CarDataString selectByPrimaryKey(CarDataString key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_data_string
     *
     * @mbggenerated Tue Mar 31 10:36:00 CST 2015
     */
    int updateByPrimaryKeySelective(CarDataString record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_data_string
     *
     * @mbggenerated Tue Mar 31 10:36:00 CST 2015
     */
    int updateByPrimaryKey(CarDataString record);
    
    //根据数据项Id查找是否存在值
    int selectByDataId(Integer dataId);
    
    int deleteByCarId(Integer carId);
    
    int selectCountByPrimaryKey(CarDataString record);
}