package com.cnit.yoyo.dao.car;

import com.cnit.yoyo.model.car.CarDataBool;

public interface CarDataBoolMapper {
   
    int deleteByPrimaryKey(CarDataBool key);

  
    int insert(CarDataBool record);

  
    int insertSelective(CarDataBool record);

  
    CarDataBool selectByPrimaryKey(CarDataBool key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_data_bool
     *
     * @mbggenerated Tue Mar 31 10:42:40 CST 2015
     */
    int updateByPrimaryKeySelective(CarDataBool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_data_bool
     *
     * @mbggenerated Tue Mar 31 10:42:40 CST 2015
     */
    int updateByPrimaryKey(CarDataBool record);
    
  //根据数据项Id查找是否存在值
    int selectByDataId(Integer dataId);
    
    int deleteByCarId(Integer carId);
    
    int selectCountByPrimaryKey(CarDataBool record);
}