package com.cnit.yoyo.dao.car;

import java.util.List;

import com.cnit.yoyo.autohome.model.AutohomeCarInfoDTO;
import com.cnit.yoyo.model.car.CarFactory;
import com.cnit.yoyo.model.car.dto.CarFactoryDTO;

public interface CarFactoryMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_car_factory
	 * @mbggenerated  Sat Mar 28 11:32:32 CST 2015
	 */
	int deleteByPrimaryKey(Integer[] factoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_car_factory
	 * @mbggenerated  Sat Mar 28 11:32:32 CST 2015
	 */
	int insert(CarFactory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_car_factory
	 * @mbggenerated  Sat Mar 28 11:32:32 CST 2015
	 */
	int insertSelective(CarFactory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_car_factory
	 * @mbggenerated  Sat Mar 28 11:32:32 CST 2015
	 */
	CarFactory selectByPrimaryKey(Integer factoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_car_factory
	 * @mbggenerated  Sat Mar 28 11:32:32 CST 2015
	 */
	int updateByPrimaryKeySelective(CarFactory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_car_factory
	 * @mbggenerated  Sat Mar 28 11:32:32 CST 2015
	 */
	int updateByPrimaryKey(CarFactory record);

	List<CarFactory> findList(CarFactory dto);
	
	List<CarFactory> findSelect(Integer brandId);
	
	//通过厂商区域id查找厂商
	int selectByScopeId(Integer id);
	
	//通过厂商区域id查找厂商
	List<String> selectByScopeIds(Integer [] id);
	
	//查找是否同名
	int findByName(CarFactory dto);
	
	List<CarFactory> selectCarFactoryByBrand(Integer brandId);
	
	/**
	  * @description <b>查询厂商以及其包含的车系</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-5-21
	  * @param @return
	  * @return List<CarFactoryDTO>
	*/
	List<CarFactoryDTO> selectCarFactoryIncludeCarDept(Integer brandId);
	
	/**
	  * @description <b>查询厂商以及其包含的车系</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-5-21
	  * @param @return
	  * @return List<CarFactoryDTO>
	*/
	List<CarFactoryDTO> selectCarFactoryIncludeCarDeptHasGoods(Integer brandId);
	/**
	 * @Description:查询车厂商数据
	 * @param list
	 * @return
	 */
	List<CarFactoryDTO> selectCarFactorySpiderDataList(List<AutohomeCarInfoDTO> list);
	/**
	 * @Description:查询车厂商数据
	 * @param list
	 * @return
	 */
	CarFactoryDTO selectCarFactorySpiderData(AutohomeCarInfoDTO factoryId);
	
}