package com.cnit.yoyo.dao.car;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.cnit.yoyo.model.car.CarMaintain;
import com.cnit.yoyo.model.car.dto.CarMaintainDTO;
import com.cnit.yoyo.model.car.dto.CarMaintainGoodsDTO;
import com.cnit.yoyo.model.car.dto.CarMaintainItemDTO;
import com.cnit.yoyo.model.car.dto.CarMaintainQryDTO;
import com.cnit.yoyo.model.car.dto.CarMaintainReferenceDTO;
import com.cnit.yoyo.model.car.dto.MaintainAccessoryCatalogDTO;
import com.cnit.yoyo.model.car.dto.MaintainAccessoryItemsDTO;
import com.cnit.yoyo.model.car.dto.MaintainBrandDTO;
import com.cnit.yoyo.model.car.dto.MaintainCompanyDTO;
import com.cnit.yoyo.model.car.dto.MaintainProductDTO;

public interface CarMaintainMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_car_maintain_cycle
	 * 
	 * @mbggenerated Thu Mar 26 16:08:45 CST 2015
	 */
	int deleteByPrimaryKey(Integer[] maintainId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_car_maintain_cycle
	 * 
	 * @mbggenerated Thu Mar 26 16:08:45 CST 2015
	 */
	int insert(CarMaintain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_car_maintain_cycle
	 * 
	 * @mbggenerated Thu Mar 26 16:08:45 CST 2015
	 */
	int insertSelective(CarMaintainDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_car_maintain_cycle
	 * 
	 * @mbggenerated Thu Mar 26 16:08:45 CST 2015
	 */
	CarMaintain selectByPrimaryKey(Integer maintainId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_car_maintain_cycle
	 * 
	 * @mbggenerated Thu Mar 26 16:08:45 CST 2015
	 */
	int updateByPrimaryKeySelective(CarMaintainDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_car_maintain_cycle
	 * 
	 * @mbggenerated Thu Mar 26 16:08:45 CST 2015
	 */
	int updateByPrimaryKey(CarMaintain record);

	List<CarMaintainDTO> findList(CarMaintainDTO carMaintian);

	int findByCarIdandName(CarMaintainDTO carMaintian);

	/**
	 * @description <b>查具体车型的保养信息</b>
	 * @author 王鹏
	 * @version 1.0.0
	 * @data 2015-5-12
	 * @param @param carId
	 * @param @return
	 * @return List<CarMaintain>
	 */
	List<CarMaintain> selectCarmaintainByCarId(Integer carId);

	/**
	 * @description <b>查询本地数据和网络数据对比</b>
	 * @author 王鹏
	 * @version 1.0.0
	 * @data 2015-5-13
	 * @param @param dto
	 * @param @return
	 * @return List<CarMaintainReferenceDTO>
	 */
	List<CarMaintainReferenceDTO> selectCarMaintainReference(
			CarMaintainReferenceDTO dto);

	/**
	 * @description <b>同级爬虫表和本地表保养表数据总数</b>
	 * @author 王鹏
	 * @version 1.0.0
	 * @data 2015-5-14
	 * @param @return
	 * @return Map<String,Object>
	 */
	HashMap<String, BigDecimal> selectCarMaintainCount();

	/**
	 * 卖家中心--》获得所有保养周期
	 * */
	List<CarMaintainReferenceDTO> selectCarMaintainByParam(
			CarMaintainReferenceDTO dto);

	List<CarMaintainGoodsDTO> findCarMaintainItemByIds(Map map);

	// 通过车型id查找保养周期
	List<Integer> selectByCarId(Integer[] id);

	CarMaintain selectCarMaintain(CarMaintainQryDTO qryDTO);

	List<MaintainCompanyDTO> selectMaintainCompany(CarMaintainQryDTO qryDTO);

	List<MaintainProductDTO> selectDefautlGoods(CarMaintainQryDTO qryDTO);
	
	List<MaintainProductDTO> selectOptionalAccessoriesProduct(CarMaintainQryDTO qryDTO);
	
	List<MaintainBrandDTO> selectOptionalAccessoriesBrand(CarMaintainQryDTO qryDTO);
	
	List<MaintainAccessoryItemsDTO> selectMaintainAccessoryItems(List<CarMaintainItemDTO> list);
	
	List<MaintainAccessoryCatalogDTO> selectMaintainAccessoryCatalog(CarMaintainQryDTO qryDTO);

}