package com.cnit.yoyo.model.system;

import java.io.Serializable;

public class ResourceRoleLink implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_role.ID
     *
     * @mbggenerated Wed Mar 25 19:51:14 CST 2015
     */
    private Integer id;
    
    private Integer roleId;
    
    private Integer resourceId;

    public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_role.ROLE_ID
     *
     * @mbggenerated Wed Mar 25 19:51:14 CST 2015
     */
    private Role role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_role.RESOURCE_ID
     *
     * @mbggenerated Wed Mar 25 19:51:14 CST 2015
     */
    private Resource resource;

    public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Resource getResource() {
		return resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_resource_role
     *
     * @mbggenerated Wed Mar 25 19:51:14 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_role.ID
     *
     * @return the value of t_resource_role.ID
     *
     * @mbggenerated Wed Mar 25 19:51:14 CST 2015
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_role
     *
     * @mbggenerated Wed Mar 25 19:51:14 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(role.getRoleId());
        sb.append(", resourceId=").append(resource.getId());
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_role
     *
     * @mbggenerated Wed Mar 25 19:51:14 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ResourceRoleLink other = (ResourceRoleLink) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (role.getRoleId() == null ? other.getRole().getRoleId() == null : role.getRoleId().equals(other.getRole().getRoleId()))
            && (resource.getId() == null ? other.getResource().getId() == null : resource.getId().equals(other.getResource().getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_role
     *
     * @mbggenerated Wed Mar 25 19:51:14 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((role.getRoleId() == null) ? 0 : role.getRoleId().hashCode());
        result = prime * result + ((resource.getId() == null) ? 0 : resource.getId().hashCode());
        return result;
    }

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public Integer getResourceId() {
		return resourceId;
	}

	public void setResourceId(Integer resourceId) {
		this.resourceId = resourceId;
	}
}