package com.cnit.yoyo.model.system;

import java.io.Serializable;


public class SiteResource implements Serializable {
	public static enum SiteResourceType {
        menu("菜单"), button("按钮");

        private final String info;
        private SiteResourceType(String info) {
            this.info = info;
        }

        public String getInfo() {
            return info;
        }
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.ID
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.RESOURCE_NAME
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.RESOURCE_TYPE
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private SiteResourceType resourceType = SiteResourceType.menu; //资源类型

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.APP_ID
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.WORKGROUND
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private String workground;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.MENU_GROUP
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private String menuGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.MENU_TITLE
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private String menuTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.URL
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.DISABLED
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.DISPLAY
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private Boolean display;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.PERMISSION
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.TARGET
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.MENU_ORDER
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private Integer menuOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.IDENTITY
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private String identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.PARENT_ID
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.PARENT_IDS
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private String parentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.ICON
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.WEIGHT
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_resource.ADDON
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private String addon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_site_resource
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.ID
     *
     * @return the value of t_site_resource.ID
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.ID
     *
     * @param id the value for t_site_resource.ID
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.RESOURCE_NAME
     *
     * @return the value of t_site_resource.RESOURCE_NAME
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.RESOURCE_NAME
     *
     * @param resourceName the value for t_site_resource.RESOURCE_NAME
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.RESOURCE_TYPE
     *
     * @return the value of t_site_resource.RESOURCE_TYPE
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public SiteResourceType getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.RESOURCE_TYPE
     *
     * @param resourceType the value for t_site_resource.RESOURCE_TYPE
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setResourceType(SiteResourceType resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.APP_ID
     *
     * @return the value of t_site_resource.APP_ID
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.APP_ID
     *
     * @param appId the value for t_site_resource.APP_ID
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.WORKGROUND
     *
     * @return the value of t_site_resource.WORKGROUND
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public String getWorkground() {
        return workground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.WORKGROUND
     *
     * @param workground the value for t_site_resource.WORKGROUND
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setWorkground(String workground) {
        this.workground = workground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.MENU_GROUP
     *
     * @return the value of t_site_resource.MENU_GROUP
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public String getMenuGroup() {
        return menuGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.MENU_GROUP
     *
     * @param menuGroup the value for t_site_resource.MENU_GROUP
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setMenuGroup(String menuGroup) {
        this.menuGroup = menuGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.MENU_TITLE
     *
     * @return the value of t_site_resource.MENU_TITLE
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public String getMenuTitle() {
        return menuTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.MENU_TITLE
     *
     * @param menuTitle the value for t_site_resource.MENU_TITLE
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setMenuTitle(String menuTitle) {
        this.menuTitle = menuTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.URL
     *
     * @return the value of t_site_resource.URL
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.URL
     *
     * @param url the value for t_site_resource.URL
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.DISABLED
     *
     * @return the value of t_site_resource.DISABLED
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.DISABLED
     *
     * @param disabled the value for t_site_resource.DISABLED
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.DISPLAY
     *
     * @return the value of t_site_resource.DISPLAY
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public Boolean getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.DISPLAY
     *
     * @param display the value for t_site_resource.DISPLAY
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setDisplay(Boolean display) {
        this.display = display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.PERMISSION
     *
     * @return the value of t_site_resource.PERMISSION
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.PERMISSION
     *
     * @param permission the value for t_site_resource.PERMISSION
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.TARGET
     *
     * @return the value of t_site_resource.TARGET
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.TARGET
     *
     * @param target the value for t_site_resource.TARGET
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setTarget(String target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.MENU_ORDER
     *
     * @return the value of t_site_resource.MENU_ORDER
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public Integer getMenuOrder() {
        return menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.MENU_ORDER
     *
     * @param menuOrder the value for t_site_resource.MENU_ORDER
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setMenuOrder(Integer menuOrder) {
        this.menuOrder = menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.IDENTITY
     *
     * @return the value of t_site_resource.IDENTITY
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.IDENTITY
     *
     * @param identity the value for t_site_resource.IDENTITY
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setIdentity(String identity) {
        this.identity = identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.PARENT_ID
     *
     * @return the value of t_site_resource.PARENT_ID
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.PARENT_ID
     *
     * @param parentId the value for t_site_resource.PARENT_ID
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.PARENT_IDS
     *
     * @return the value of t_site_resource.PARENT_IDS
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.PARENT_IDS
     *
     * @param parentIds the value for t_site_resource.PARENT_IDS
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.ICON
     *
     * @return the value of t_site_resource.ICON
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.ICON
     *
     * @param icon the value for t_site_resource.ICON
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.WEIGHT
     *
     * @return the value of t_site_resource.WEIGHT
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.WEIGHT
     *
     * @param weight the value for t_site_resource.WEIGHT
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_resource.ADDON
     *
     * @return the value of t_site_resource.ADDON
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public String getAddon() {
        return addon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_resource.ADDON
     *
     * @param addon the value for t_site_resource.ADDON
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    public void setAddon(String addon) {
        this.addon = addon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_resource
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", resourceName=").append(resourceName);
        sb.append(", resourceType=").append(resourceType);
        sb.append(", appId=").append(appId);
        sb.append(", workground=").append(workground);
        sb.append(", menuGroup=").append(menuGroup);
        sb.append(", menuTitle=").append(menuTitle);
        sb.append(", url=").append(url);
        sb.append(", disabled=").append(disabled);
        sb.append(", display=").append(display);
        sb.append(", permission=").append(permission);
        sb.append(", target=").append(target);
        sb.append(", menuOrder=").append(menuOrder);
        sb.append(", identity=").append(identity);
        sb.append(", parentId=").append(parentId);
        sb.append(", parentIds=").append(parentIds);
        sb.append(", icon=").append(icon);
        sb.append(", weight=").append(weight);
        sb.append(", addon=").append(addon);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_resource
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SiteResource other = (SiteResource) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getResourceName() == null ? other.getResourceName() == null : this.getResourceName().equals(other.getResourceName()))
            && (this.getResourceType() == null ? other.getResourceType() == null : this.getResourceType().equals(other.getResourceType()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getWorkground() == null ? other.getWorkground() == null : this.getWorkground().equals(other.getWorkground()))
            && (this.getMenuGroup() == null ? other.getMenuGroup() == null : this.getMenuGroup().equals(other.getMenuGroup()))
            && (this.getMenuTitle() == null ? other.getMenuTitle() == null : this.getMenuTitle().equals(other.getMenuTitle()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getDisabled() == null ? other.getDisabled() == null : this.getDisabled().equals(other.getDisabled()))
            && (this.getDisplay() == null ? other.getDisplay() == null : this.getDisplay().equals(other.getDisplay()))
            && (this.getPermission() == null ? other.getPermission() == null : this.getPermission().equals(other.getPermission()))
            && (this.getTarget() == null ? other.getTarget() == null : this.getTarget().equals(other.getTarget()))
            && (this.getMenuOrder() == null ? other.getMenuOrder() == null : this.getMenuOrder().equals(other.getMenuOrder()))
            && (this.getIdentity() == null ? other.getIdentity() == null : this.getIdentity().equals(other.getIdentity()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getParentIds() == null ? other.getParentIds() == null : this.getParentIds().equals(other.getParentIds()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getWeight() == null ? other.getWeight() == null : this.getWeight().equals(other.getWeight()))
            && (this.getAddon() == null ? other.getAddon() == null : this.getAddon().equals(other.getAddon()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_resource
     *
     * @mbggenerated Fri Apr 10 13:30:10 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getResourceName() == null) ? 0 : getResourceName().hashCode());
        result = prime * result + ((getResourceType() == null) ? 0 : getResourceType().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getWorkground() == null) ? 0 : getWorkground().hashCode());
        result = prime * result + ((getMenuGroup() == null) ? 0 : getMenuGroup().hashCode());
        result = prime * result + ((getMenuTitle() == null) ? 0 : getMenuTitle().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getDisabled() == null) ? 0 : getDisabled().hashCode());
        result = prime * result + ((getDisplay() == null) ? 0 : getDisplay().hashCode());
        result = prime * result + ((getPermission() == null) ? 0 : getPermission().hashCode());
        result = prime * result + ((getTarget() == null) ? 0 : getTarget().hashCode());
        result = prime * result + ((getMenuOrder() == null) ? 0 : getMenuOrder().hashCode());
        result = prime * result + ((getIdentity() == null) ? 0 : getIdentity().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getParentIds() == null) ? 0 : getParentIds().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
        result = prime * result + ((getAddon() == null) ? 0 : getAddon().hashCode());
        return result;
    }
}