package com.cnit.yoyo.model.shop;

import java.io.Serializable;

public class StoreViolationCatWithBLOBs extends StoreViolationCat implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_violationcat.tabs
	 * @mbggenerated  Wed Jun 03 16:26:50 CST 2015
	 */
	private String tabs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_violationcat.addon
	 * @mbggenerated  Wed Jun 03 16:26:50 CST 2015
	 */
	private String addon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_business_violationcat
	 * @mbggenerated  Wed Jun 03 16:26:50 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_violationcat.tabs
	 * @return  the value of t_business_violationcat.tabs
	 * @mbggenerated  Wed Jun 03 16:26:50 CST 2015
	 */
	public String getTabs() {
		return tabs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_violationcat.tabs
	 * @param tabs  the value for t_business_violationcat.tabs
	 * @mbggenerated  Wed Jun 03 16:26:50 CST 2015
	 */
	public void setTabs(String tabs) {
		this.tabs = tabs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_violationcat.addon
	 * @return  the value of t_business_violationcat.addon
	 * @mbggenerated  Wed Jun 03 16:26:50 CST 2015
	 */
	public String getAddon() {
		return addon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_violationcat.addon
	 * @param addon  the value for t_business_violationcat.addon
	 * @mbggenerated  Wed Jun 03 16:26:50 CST 2015
	 */
	public void setAddon(String addon) {
		this.addon = addon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_violationcat
	 * @mbggenerated  Wed Jun 03 16:26:50 CST 2015
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", tabs=").append(tabs);
		sb.append(", addon=").append(addon);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_violationcat
	 * @mbggenerated  Wed Jun 03 16:26:50 CST 2015
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		StoreViolationCatWithBLOBs other = (StoreViolationCatWithBLOBs) that;
		return (this.getCatId() == null ? other.getCatId() == null : this
				.getCatId().equals(other.getCatId()))
				&& (this.getParentId() == null ? other.getParentId() == null
						: this.getParentId().equals(other.getParentId()))
				&& (this.getCatPath() == null ? other.getCatPath() == null
						: this.getCatPath().equals(other.getCatPath()))
				&& (this.getIsLeaf() == null ? other.getIsLeaf() == null : this
						.getIsLeaf().equals(other.getIsLeaf()))
				&& (this.getCatName() == null ? other.getCatName() == null
						: this.getCatName().equals(other.getCatName()))
				&& (this.getScore() == null ? other.getScore() == null : this
						.getScore().equals(other.getScore()))
				&& (this.getAddTime() == null ? other.getAddTime() == null
						: this.getAddTime().equals(other.getAddTime()))
				&& (this.getLastModify() == null ? other.getLastModify() == null
						: this.getLastModify().equals(other.getLastModify()))
				&& (this.getDisabled() == null ? other.getDisabled() == null
						: this.getDisabled().equals(other.getDisabled()))
				&& (this.getpOrder() == null ? other.getpOrder() == null : this
						.getpOrder().equals(other.getpOrder()))
				&& (this.getChildCount() == null ? other.getChildCount() == null
						: this.getChildCount().equals(other.getChildCount()))
				&& (this.getTabs() == null ? other.getTabs() == null : this
						.getTabs().equals(other.getTabs()))
				&& (this.getAddon() == null ? other.getAddon() == null : this
						.getAddon().equals(other.getAddon()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_violationcat
	 * @mbggenerated  Wed Jun 03 16:26:50 CST 2015
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getCatId() == null) ? 0 : getCatId().hashCode());
		result = prime * result
				+ ((getParentId() == null) ? 0 : getParentId().hashCode());
		result = prime * result
				+ ((getCatPath() == null) ? 0 : getCatPath().hashCode());
		result = prime * result
				+ ((getIsLeaf() == null) ? 0 : getIsLeaf().hashCode());
		result = prime * result
				+ ((getCatName() == null) ? 0 : getCatName().hashCode());
		result = prime * result
				+ ((getScore() == null) ? 0 : getScore().hashCode());
		result = prime * result
				+ ((getAddTime() == null) ? 0 : getAddTime().hashCode());
		result = prime * result
				+ ((getLastModify() == null) ? 0 : getLastModify().hashCode());
		result = prime * result
				+ ((getDisabled() == null) ? 0 : getDisabled().hashCode());
		result = prime * result
				+ ((getpOrder() == null) ? 0 : getpOrder().hashCode());
		result = prime * result
				+ ((getChildCount() == null) ? 0 : getChildCount().hashCode());
		result = prime * result
				+ ((getTabs() == null) ? 0 : getTabs().hashCode());
		result = prime * result
				+ ((getAddon() == null) ? 0 : getAddon().hashCode());
		return result;
	}
}