package com.cnit.yoyo.model.shop;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class StoreViolationExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	public StoreViolationExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andStoreIdIsNull() {
			addCriterion("store_id is null");
			return (Criteria) this;
		}

		public Criteria andStoreIdIsNotNull() {
			addCriterion("store_id is not null");
			return (Criteria) this;
		}

		public Criteria andStoreIdEqualTo(Long value) {
			addCriterion("store_id =", value, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdNotEqualTo(Long value) {
			addCriterion("store_id <>", value, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdGreaterThan(Long value) {
			addCriterion("store_id >", value, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdGreaterThanOrEqualTo(Long value) {
			addCriterion("store_id >=", value, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdLessThan(Long value) {
			addCriterion("store_id <", value, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdLessThanOrEqualTo(Long value) {
			addCriterion("store_id <=", value, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdIn(List<Long> values) {
			addCriterion("store_id in", values, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdNotIn(List<Long> values) {
			addCriterion("store_id not in", values, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdBetween(Long value1, Long value2) {
			addCriterion("store_id between", value1, value2, "storeId");
			return (Criteria) this;
		}

		public Criteria andStoreIdNotBetween(Long value1, Long value2) {
			addCriterion("store_id not between", value1, value2, "storeId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIsNull() {
			addCriterion("company_id is null");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIsNotNull() {
			addCriterion("company_id is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyIdEqualTo(Long value) {
			addCriterion("company_id =", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotEqualTo(Long value) {
			addCriterion("company_id <>", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdGreaterThan(Long value) {
			addCriterion("company_id >", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdGreaterThanOrEqualTo(Long value) {
			addCriterion("company_id >=", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdLessThan(Long value) {
			addCriterion("company_id <", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdLessThanOrEqualTo(Long value) {
			addCriterion("company_id <=", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIn(List<Long> values) {
			addCriterion("company_id in", values, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotIn(List<Long> values) {
			addCriterion("company_id not in", values, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdBetween(Long value1, Long value2) {
			addCriterion("company_id between", value1, value2, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotBetween(Long value1, Long value2) {
			addCriterion("company_id not between", value1, value2, "companyId");
			return (Criteria) this;
		}

		public Criteria andCatIdIsNull() {
			addCriterion("cat_id is null");
			return (Criteria) this;
		}

		public Criteria andCatIdIsNotNull() {
			addCriterion("cat_id is not null");
			return (Criteria) this;
		}

		public Criteria andCatIdEqualTo(Integer value) {
			addCriterion("cat_id =", value, "catId");
			return (Criteria) this;
		}

		public Criteria andCatIdNotEqualTo(Integer value) {
			addCriterion("cat_id <>", value, "catId");
			return (Criteria) this;
		}

		public Criteria andCatIdGreaterThan(Integer value) {
			addCriterion("cat_id >", value, "catId");
			return (Criteria) this;
		}

		public Criteria andCatIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("cat_id >=", value, "catId");
			return (Criteria) this;
		}

		public Criteria andCatIdLessThan(Integer value) {
			addCriterion("cat_id <", value, "catId");
			return (Criteria) this;
		}

		public Criteria andCatIdLessThanOrEqualTo(Integer value) {
			addCriterion("cat_id <=", value, "catId");
			return (Criteria) this;
		}

		public Criteria andCatIdIn(List<Integer> values) {
			addCriterion("cat_id in", values, "catId");
			return (Criteria) this;
		}

		public Criteria andCatIdNotIn(List<Integer> values) {
			addCriterion("cat_id not in", values, "catId");
			return (Criteria) this;
		}

		public Criteria andCatIdBetween(Integer value1, Integer value2) {
			addCriterion("cat_id between", value1, value2, "catId");
			return (Criteria) this;
		}

		public Criteria andCatIdNotBetween(Integer value1, Integer value2) {
			addCriterion("cat_id not between", value1, value2, "catId");
			return (Criteria) this;
		}

		public Criteria andGoodsStarttimeIsNull() {
			addCriterion("goods_starttime is null");
			return (Criteria) this;
		}

		public Criteria andGoodsStarttimeIsNotNull() {
			addCriterion("goods_starttime is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsStarttimeEqualTo(Date value) {
			addCriterion("goods_starttime =", value, "goodsStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsStarttimeNotEqualTo(Date value) {
			addCriterion("goods_starttime <>", value, "goodsStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsStarttimeGreaterThan(Date value) {
			addCriterion("goods_starttime >", value, "goodsStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsStarttimeGreaterThanOrEqualTo(Date value) {
			addCriterion("goods_starttime >=", value, "goodsStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsStarttimeLessThan(Date value) {
			addCriterion("goods_starttime <", value, "goodsStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsStarttimeLessThanOrEqualTo(Date value) {
			addCriterion("goods_starttime <=", value, "goodsStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsStarttimeIn(List<Date> values) {
			addCriterion("goods_starttime in", values, "goodsStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsStarttimeNotIn(List<Date> values) {
			addCriterion("goods_starttime not in", values, "goodsStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsStarttimeBetween(Date value1, Date value2) {
			addCriterion("goods_starttime between", value1, value2,
					"goodsStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsStarttimeNotBetween(Date value1, Date value2) {
			addCriterion("goods_starttime not between", value1, value2,
					"goodsStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsEndtimeIsNull() {
			addCriterion("goods_endtime is null");
			return (Criteria) this;
		}

		public Criteria andGoodsEndtimeIsNotNull() {
			addCriterion("goods_endtime is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsEndtimeEqualTo(Date value) {
			addCriterion("goods_endtime =", value, "goodsEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsEndtimeNotEqualTo(Date value) {
			addCriterion("goods_endtime <>", value, "goodsEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsEndtimeGreaterThan(Date value) {
			addCriterion("goods_endtime >", value, "goodsEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("goods_endtime >=", value, "goodsEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsEndtimeLessThan(Date value) {
			addCriterion("goods_endtime <", value, "goodsEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsEndtimeLessThanOrEqualTo(Date value) {
			addCriterion("goods_endtime <=", value, "goodsEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsEndtimeIn(List<Date> values) {
			addCriterion("goods_endtime in", values, "goodsEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsEndtimeNotIn(List<Date> values) {
			addCriterion("goods_endtime not in", values, "goodsEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsEndtimeBetween(Date value1, Date value2) {
			addCriterion("goods_endtime between", value1, value2,
					"goodsEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsEndtimeNotBetween(Date value1, Date value2) {
			addCriterion("goods_endtime not between", value1, value2,
					"goodsEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownStarttimeIsNull() {
			addCriterion("goodsdown_starttime is null");
			return (Criteria) this;
		}

		public Criteria andGoodsdownStarttimeIsNotNull() {
			addCriterion("goodsdown_starttime is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsdownStarttimeEqualTo(Date value) {
			addCriterion("goodsdown_starttime =", value, "goodsdownStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownStarttimeNotEqualTo(Date value) {
			addCriterion("goodsdown_starttime <>", value, "goodsdownStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownStarttimeGreaterThan(Date value) {
			addCriterion("goodsdown_starttime >", value, "goodsdownStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownStarttimeGreaterThanOrEqualTo(Date value) {
			addCriterion("goodsdown_starttime >=", value, "goodsdownStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownStarttimeLessThan(Date value) {
			addCriterion("goodsdown_starttime <", value, "goodsdownStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownStarttimeLessThanOrEqualTo(Date value) {
			addCriterion("goodsdown_starttime <=", value, "goodsdownStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownStarttimeIn(List<Date> values) {
			addCriterion("goodsdown_starttime in", values, "goodsdownStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownStarttimeNotIn(List<Date> values) {
			addCriterion("goodsdown_starttime not in", values,
					"goodsdownStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownStarttimeBetween(Date value1, Date value2) {
			addCriterion("goodsdown_starttime between", value1, value2,
					"goodsdownStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownStarttimeNotBetween(Date value1, Date value2) {
			addCriterion("goodsdown_starttime not between", value1, value2,
					"goodsdownStarttime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownEndtimeIsNull() {
			addCriterion("goodsdown_endtime is null");
			return (Criteria) this;
		}

		public Criteria andGoodsdownEndtimeIsNotNull() {
			addCriterion("goodsdown_endtime is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsdownEndtimeEqualTo(Date value) {
			addCriterion("goodsdown_endtime =", value, "goodsdownEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownEndtimeNotEqualTo(Date value) {
			addCriterion("goodsdown_endtime <>", value, "goodsdownEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownEndtimeGreaterThan(Date value) {
			addCriterion("goodsdown_endtime >", value, "goodsdownEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("goodsdown_endtime >=", value, "goodsdownEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownEndtimeLessThan(Date value) {
			addCriterion("goodsdown_endtime <", value, "goodsdownEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownEndtimeLessThanOrEqualTo(Date value) {
			addCriterion("goodsdown_endtime <=", value, "goodsdownEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownEndtimeIn(List<Date> values) {
			addCriterion("goodsdown_endtime in", values, "goodsdownEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownEndtimeNotIn(List<Date> values) {
			addCriterion("goodsdown_endtime not in", values, "goodsdownEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownEndtimeBetween(Date value1, Date value2) {
			addCriterion("goodsdown_endtime between", value1, value2,
					"goodsdownEndtime");
			return (Criteria) this;
		}

		public Criteria andGoodsdownEndtimeNotBetween(Date value1, Date value2) {
			addCriterion("goodsdown_endtime not between", value1, value2,
					"goodsdownEndtime");
			return (Criteria) this;
		}

		public Criteria andNewsStarttimeIsNull() {
			addCriterion("news_starttime is null");
			return (Criteria) this;
		}

		public Criteria andNewsStarttimeIsNotNull() {
			addCriterion("news_starttime is not null");
			return (Criteria) this;
		}

		public Criteria andNewsStarttimeEqualTo(Date value) {
			addCriterion("news_starttime =", value, "newsStarttime");
			return (Criteria) this;
		}

		public Criteria andNewsStarttimeNotEqualTo(Date value) {
			addCriterion("news_starttime <>", value, "newsStarttime");
			return (Criteria) this;
		}

		public Criteria andNewsStarttimeGreaterThan(Date value) {
			addCriterion("news_starttime >", value, "newsStarttime");
			return (Criteria) this;
		}

		public Criteria andNewsStarttimeGreaterThanOrEqualTo(Date value) {
			addCriterion("news_starttime >=", value, "newsStarttime");
			return (Criteria) this;
		}

		public Criteria andNewsStarttimeLessThan(Date value) {
			addCriterion("news_starttime <", value, "newsStarttime");
			return (Criteria) this;
		}

		public Criteria andNewsStarttimeLessThanOrEqualTo(Date value) {
			addCriterion("news_starttime <=", value, "newsStarttime");
			return (Criteria) this;
		}

		public Criteria andNewsStarttimeIn(List<Date> values) {
			addCriterion("news_starttime in", values, "newsStarttime");
			return (Criteria) this;
		}

		public Criteria andNewsStarttimeNotIn(List<Date> values) {
			addCriterion("news_starttime not in", values, "newsStarttime");
			return (Criteria) this;
		}

		public Criteria andNewsStarttimeBetween(Date value1, Date value2) {
			addCriterion("news_starttime between", value1, value2,
					"newsStarttime");
			return (Criteria) this;
		}

		public Criteria andNewsStarttimeNotBetween(Date value1, Date value2) {
			addCriterion("news_starttime not between", value1, value2,
					"newsStarttime");
			return (Criteria) this;
		}

		public Criteria andNewsEndtimeIsNull() {
			addCriterion("news_endtime is null");
			return (Criteria) this;
		}

		public Criteria andNewsEndtimeIsNotNull() {
			addCriterion("news_endtime is not null");
			return (Criteria) this;
		}

		public Criteria andNewsEndtimeEqualTo(Date value) {
			addCriterion("news_endtime =", value, "newsEndtime");
			return (Criteria) this;
		}

		public Criteria andNewsEndtimeNotEqualTo(Date value) {
			addCriterion("news_endtime <>", value, "newsEndtime");
			return (Criteria) this;
		}

		public Criteria andNewsEndtimeGreaterThan(Date value) {
			addCriterion("news_endtime >", value, "newsEndtime");
			return (Criteria) this;
		}

		public Criteria andNewsEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("news_endtime >=", value, "newsEndtime");
			return (Criteria) this;
		}

		public Criteria andNewsEndtimeLessThan(Date value) {
			addCriterion("news_endtime <", value, "newsEndtime");
			return (Criteria) this;
		}

		public Criteria andNewsEndtimeLessThanOrEqualTo(Date value) {
			addCriterion("news_endtime <=", value, "newsEndtime");
			return (Criteria) this;
		}

		public Criteria andNewsEndtimeIn(List<Date> values) {
			addCriterion("news_endtime in", values, "newsEndtime");
			return (Criteria) this;
		}

		public Criteria andNewsEndtimeNotIn(List<Date> values) {
			addCriterion("news_endtime not in", values, "newsEndtime");
			return (Criteria) this;
		}

		public Criteria andNewsEndtimeBetween(Date value1, Date value2) {
			addCriterion("news_endtime between", value1, value2, "newsEndtime");
			return (Criteria) this;
		}

		public Criteria andNewsEndtimeNotBetween(Date value1, Date value2) {
			addCriterion("news_endtime not between", value1, value2,
					"newsEndtime");
			return (Criteria) this;
		}

		public Criteria andNewsValueIsNull() {
			addCriterion("news_value is null");
			return (Criteria) this;
		}

		public Criteria andNewsValueIsNotNull() {
			addCriterion("news_value is not null");
			return (Criteria) this;
		}

		public Criteria andNewsValueEqualTo(Integer value) {
			addCriterion("news_value =", value, "newsValue");
			return (Criteria) this;
		}

		public Criteria andNewsValueNotEqualTo(Integer value) {
			addCriterion("news_value <>", value, "newsValue");
			return (Criteria) this;
		}

		public Criteria andNewsValueGreaterThan(Integer value) {
			addCriterion("news_value >", value, "newsValue");
			return (Criteria) this;
		}

		public Criteria andNewsValueGreaterThanOrEqualTo(Integer value) {
			addCriterion("news_value >=", value, "newsValue");
			return (Criteria) this;
		}

		public Criteria andNewsValueLessThan(Integer value) {
			addCriterion("news_value <", value, "newsValue");
			return (Criteria) this;
		}

		public Criteria andNewsValueLessThanOrEqualTo(Integer value) {
			addCriterion("news_value <=", value, "newsValue");
			return (Criteria) this;
		}

		public Criteria andNewsValueIn(List<Integer> values) {
			addCriterion("news_value in", values, "newsValue");
			return (Criteria) this;
		}

		public Criteria andNewsValueNotIn(List<Integer> values) {
			addCriterion("news_value not in", values, "newsValue");
			return (Criteria) this;
		}

		public Criteria andNewsValueBetween(Integer value1, Integer value2) {
			addCriterion("news_value between", value1, value2, "newsValue");
			return (Criteria) this;
		}

		public Criteria andNewsValueNotBetween(Integer value1, Integer value2) {
			addCriterion("news_value not between", value1, value2, "newsValue");
			return (Criteria) this;
		}

		public Criteria andStoreStarttimeIsNull() {
			addCriterion("store_starttime is null");
			return (Criteria) this;
		}

		public Criteria andStoreStarttimeIsNotNull() {
			addCriterion("store_starttime is not null");
			return (Criteria) this;
		}

		public Criteria andStoreStarttimeEqualTo(Date value) {
			addCriterion("store_starttime =", value, "storeStarttime");
			return (Criteria) this;
		}

		public Criteria andStoreStarttimeNotEqualTo(Date value) {
			addCriterion("store_starttime <>", value, "storeStarttime");
			return (Criteria) this;
		}

		public Criteria andStoreStarttimeGreaterThan(Date value) {
			addCriterion("store_starttime >", value, "storeStarttime");
			return (Criteria) this;
		}

		public Criteria andStoreStarttimeGreaterThanOrEqualTo(Date value) {
			addCriterion("store_starttime >=", value, "storeStarttime");
			return (Criteria) this;
		}

		public Criteria andStoreStarttimeLessThan(Date value) {
			addCriterion("store_starttime <", value, "storeStarttime");
			return (Criteria) this;
		}

		public Criteria andStoreStarttimeLessThanOrEqualTo(Date value) {
			addCriterion("store_starttime <=", value, "storeStarttime");
			return (Criteria) this;
		}

		public Criteria andStoreStarttimeIn(List<Date> values) {
			addCriterion("store_starttime in", values, "storeStarttime");
			return (Criteria) this;
		}

		public Criteria andStoreStarttimeNotIn(List<Date> values) {
			addCriterion("store_starttime not in", values, "storeStarttime");
			return (Criteria) this;
		}

		public Criteria andStoreStarttimeBetween(Date value1, Date value2) {
			addCriterion("store_starttime between", value1, value2,
					"storeStarttime");
			return (Criteria) this;
		}

		public Criteria andStoreStarttimeNotBetween(Date value1, Date value2) {
			addCriterion("store_starttime not between", value1, value2,
					"storeStarttime");
			return (Criteria) this;
		}

		public Criteria andStoreEndtimeIsNull() {
			addCriterion("store_endtime is null");
			return (Criteria) this;
		}

		public Criteria andStoreEndtimeIsNotNull() {
			addCriterion("store_endtime is not null");
			return (Criteria) this;
		}

		public Criteria andStoreEndtimeEqualTo(Date value) {
			addCriterion("store_endtime =", value, "storeEndtime");
			return (Criteria) this;
		}

		public Criteria andStoreEndtimeNotEqualTo(Date value) {
			addCriterion("store_endtime <>", value, "storeEndtime");
			return (Criteria) this;
		}

		public Criteria andStoreEndtimeGreaterThan(Date value) {
			addCriterion("store_endtime >", value, "storeEndtime");
			return (Criteria) this;
		}

		public Criteria andStoreEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("store_endtime >=", value, "storeEndtime");
			return (Criteria) this;
		}

		public Criteria andStoreEndtimeLessThan(Date value) {
			addCriterion("store_endtime <", value, "storeEndtime");
			return (Criteria) this;
		}

		public Criteria andStoreEndtimeLessThanOrEqualTo(Date value) {
			addCriterion("store_endtime <=", value, "storeEndtime");
			return (Criteria) this;
		}

		public Criteria andStoreEndtimeIn(List<Date> values) {
			addCriterion("store_endtime in", values, "storeEndtime");
			return (Criteria) this;
		}

		public Criteria andStoreEndtimeNotIn(List<Date> values) {
			addCriterion("store_endtime not in", values, "storeEndtime");
			return (Criteria) this;
		}

		public Criteria andStoreEndtimeBetween(Date value1, Date value2) {
			addCriterion("store_endtime between", value1, value2,
					"storeEndtime");
			return (Criteria) this;
		}

		public Criteria andStoreEndtimeNotBetween(Date value1, Date value2) {
			addCriterion("store_endtime not between", value1, value2,
					"storeEndtime");
			return (Criteria) this;
		}

		public Criteria andStoredownStarttimeIsNull() {
			addCriterion("storedown_starttime is null");
			return (Criteria) this;
		}

		public Criteria andStoredownStarttimeIsNotNull() {
			addCriterion("storedown_starttime is not null");
			return (Criteria) this;
		}

		public Criteria andStoredownStarttimeEqualTo(Date value) {
			addCriterion("storedown_starttime =", value, "storedownStarttime");
			return (Criteria) this;
		}

		public Criteria andStoredownStarttimeNotEqualTo(Date value) {
			addCriterion("storedown_starttime <>", value, "storedownStarttime");
			return (Criteria) this;
		}

		public Criteria andStoredownStarttimeGreaterThan(Date value) {
			addCriterion("storedown_starttime >", value, "storedownStarttime");
			return (Criteria) this;
		}

		public Criteria andStoredownStarttimeGreaterThanOrEqualTo(Date value) {
			addCriterion("storedown_starttime >=", value, "storedownStarttime");
			return (Criteria) this;
		}

		public Criteria andStoredownStarttimeLessThan(Date value) {
			addCriterion("storedown_starttime <", value, "storedownStarttime");
			return (Criteria) this;
		}

		public Criteria andStoredownStarttimeLessThanOrEqualTo(Date value) {
			addCriterion("storedown_starttime <=", value, "storedownStarttime");
			return (Criteria) this;
		}

		public Criteria andStoredownStarttimeIn(List<Date> values) {
			addCriterion("storedown_starttime in", values, "storedownStarttime");
			return (Criteria) this;
		}

		public Criteria andStoredownStarttimeNotIn(List<Date> values) {
			addCriterion("storedown_starttime not in", values,
					"storedownStarttime");
			return (Criteria) this;
		}

		public Criteria andStoredownStarttimeBetween(Date value1, Date value2) {
			addCriterion("storedown_starttime between", value1, value2,
					"storedownStarttime");
			return (Criteria) this;
		}

		public Criteria andStoredownStarttimeNotBetween(Date value1, Date value2) {
			addCriterion("storedown_starttime not between", value1, value2,
					"storedownStarttime");
			return (Criteria) this;
		}

		public Criteria andStoredownEndtimeIsNull() {
			addCriterion("storedown_endtime is null");
			return (Criteria) this;
		}

		public Criteria andStoredownEndtimeIsNotNull() {
			addCriterion("storedown_endtime is not null");
			return (Criteria) this;
		}

		public Criteria andStoredownEndtimeEqualTo(Date value) {
			addCriterion("storedown_endtime =", value, "storedownEndtime");
			return (Criteria) this;
		}

		public Criteria andStoredownEndtimeNotEqualTo(Date value) {
			addCriterion("storedown_endtime <>", value, "storedownEndtime");
			return (Criteria) this;
		}

		public Criteria andStoredownEndtimeGreaterThan(Date value) {
			addCriterion("storedown_endtime >", value, "storedownEndtime");
			return (Criteria) this;
		}

		public Criteria andStoredownEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("storedown_endtime >=", value, "storedownEndtime");
			return (Criteria) this;
		}

		public Criteria andStoredownEndtimeLessThan(Date value) {
			addCriterion("storedown_endtime <", value, "storedownEndtime");
			return (Criteria) this;
		}

		public Criteria andStoredownEndtimeLessThanOrEqualTo(Date value) {
			addCriterion("storedown_endtime <=", value, "storedownEndtime");
			return (Criteria) this;
		}

		public Criteria andStoredownEndtimeIn(List<Date> values) {
			addCriterion("storedown_endtime in", values, "storedownEndtime");
			return (Criteria) this;
		}

		public Criteria andStoredownEndtimeNotIn(List<Date> values) {
			addCriterion("storedown_endtime not in", values, "storedownEndtime");
			return (Criteria) this;
		}

		public Criteria andStoredownEndtimeBetween(Date value1, Date value2) {
			addCriterion("storedown_endtime between", value1, value2,
					"storedownEndtime");
			return (Criteria) this;
		}

		public Criteria andStoredownEndtimeNotBetween(Date value1, Date value2) {
			addCriterion("storedown_endtime not between", value1, value2,
					"storedownEndtime");
			return (Criteria) this;
		}

		public Criteria andSalesStarttimeIsNull() {
			addCriterion("sales_starttime is null");
			return (Criteria) this;
		}

		public Criteria andSalesStarttimeIsNotNull() {
			addCriterion("sales_starttime is not null");
			return (Criteria) this;
		}

		public Criteria andSalesStarttimeEqualTo(Date value) {
			addCriterion("sales_starttime =", value, "salesStarttime");
			return (Criteria) this;
		}

		public Criteria andSalesStarttimeNotEqualTo(Date value) {
			addCriterion("sales_starttime <>", value, "salesStarttime");
			return (Criteria) this;
		}

		public Criteria andSalesStarttimeGreaterThan(Date value) {
			addCriterion("sales_starttime >", value, "salesStarttime");
			return (Criteria) this;
		}

		public Criteria andSalesStarttimeGreaterThanOrEqualTo(Date value) {
			addCriterion("sales_starttime >=", value, "salesStarttime");
			return (Criteria) this;
		}

		public Criteria andSalesStarttimeLessThan(Date value) {
			addCriterion("sales_starttime <", value, "salesStarttime");
			return (Criteria) this;
		}

		public Criteria andSalesStarttimeLessThanOrEqualTo(Date value) {
			addCriterion("sales_starttime <=", value, "salesStarttime");
			return (Criteria) this;
		}

		public Criteria andSalesStarttimeIn(List<Date> values) {
			addCriterion("sales_starttime in", values, "salesStarttime");
			return (Criteria) this;
		}

		public Criteria andSalesStarttimeNotIn(List<Date> values) {
			addCriterion("sales_starttime not in", values, "salesStarttime");
			return (Criteria) this;
		}

		public Criteria andSalesStarttimeBetween(Date value1, Date value2) {
			addCriterion("sales_starttime between", value1, value2,
					"salesStarttime");
			return (Criteria) this;
		}

		public Criteria andSalesStarttimeNotBetween(Date value1, Date value2) {
			addCriterion("sales_starttime not between", value1, value2,
					"salesStarttime");
			return (Criteria) this;
		}

		public Criteria andSalesEndtimeIsNull() {
			addCriterion("sales_endtime is null");
			return (Criteria) this;
		}

		public Criteria andSalesEndtimeIsNotNull() {
			addCriterion("sales_endtime is not null");
			return (Criteria) this;
		}

		public Criteria andSalesEndtimeEqualTo(Date value) {
			addCriterion("sales_endtime =", value, "salesEndtime");
			return (Criteria) this;
		}

		public Criteria andSalesEndtimeNotEqualTo(Date value) {
			addCriterion("sales_endtime <>", value, "salesEndtime");
			return (Criteria) this;
		}

		public Criteria andSalesEndtimeGreaterThan(Date value) {
			addCriterion("sales_endtime >", value, "salesEndtime");
			return (Criteria) this;
		}

		public Criteria andSalesEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("sales_endtime >=", value, "salesEndtime");
			return (Criteria) this;
		}

		public Criteria andSalesEndtimeLessThan(Date value) {
			addCriterion("sales_endtime <", value, "salesEndtime");
			return (Criteria) this;
		}

		public Criteria andSalesEndtimeLessThanOrEqualTo(Date value) {
			addCriterion("sales_endtime <=", value, "salesEndtime");
			return (Criteria) this;
		}

		public Criteria andSalesEndtimeIn(List<Date> values) {
			addCriterion("sales_endtime in", values, "salesEndtime");
			return (Criteria) this;
		}

		public Criteria andSalesEndtimeNotIn(List<Date> values) {
			addCriterion("sales_endtime not in", values, "salesEndtime");
			return (Criteria) this;
		}

		public Criteria andSalesEndtimeBetween(Date value1, Date value2) {
			addCriterion("sales_endtime between", value1, value2,
					"salesEndtime");
			return (Criteria) this;
		}

		public Criteria andSalesEndtimeNotBetween(Date value1, Date value2) {
			addCriterion("sales_endtime not between", value1, value2,
					"salesEndtime");
			return (Criteria) this;
		}

		public Criteria andScoreIsNull() {
			addCriterion("score is null");
			return (Criteria) this;
		}

		public Criteria andScoreIsNotNull() {
			addCriterion("score is not null");
			return (Criteria) this;
		}

		public Criteria andScoreEqualTo(Integer value) {
			addCriterion("score =", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualTo(Integer value) {
			addCriterion("score <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThan(Integer value) {
			addCriterion("score >", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
			addCriterion("score >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThan(Integer value) {
			addCriterion("score <", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualTo(Integer value) {
			addCriterion("score <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreIn(List<Integer> values) {
			addCriterion("score in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotIn(List<Integer> values) {
			addCriterion("score not in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreBetween(Integer value1, Integer value2) {
			addCriterion("score between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotBetween(Integer value1, Integer value2) {
			addCriterion("score not between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andEarnestIsNull() {
			addCriterion("earnest is null");
			return (Criteria) this;
		}

		public Criteria andEarnestIsNotNull() {
			addCriterion("earnest is not null");
			return (Criteria) this;
		}

		public Criteria andEarnestEqualTo(BigDecimal value) {
			addCriterion("earnest =", value, "earnest");
			return (Criteria) this;
		}

		public Criteria andEarnestNotEqualTo(BigDecimal value) {
			addCriterion("earnest <>", value, "earnest");
			return (Criteria) this;
		}

		public Criteria andEarnestGreaterThan(BigDecimal value) {
			addCriterion("earnest >", value, "earnest");
			return (Criteria) this;
		}

		public Criteria andEarnestGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("earnest >=", value, "earnest");
			return (Criteria) this;
		}

		public Criteria andEarnestLessThan(BigDecimal value) {
			addCriterion("earnest <", value, "earnest");
			return (Criteria) this;
		}

		public Criteria andEarnestLessThanOrEqualTo(BigDecimal value) {
			addCriterion("earnest <=", value, "earnest");
			return (Criteria) this;
		}

		public Criteria andEarnestIn(List<BigDecimal> values) {
			addCriterion("earnest in", values, "earnest");
			return (Criteria) this;
		}

		public Criteria andEarnestNotIn(List<BigDecimal> values) {
			addCriterion("earnest not in", values, "earnest");
			return (Criteria) this;
		}

		public Criteria andEarnestBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("earnest between", value1, value2, "earnest");
			return (Criteria) this;
		}

		public Criteria andEarnestNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("earnest not between", value1, value2, "earnest");
			return (Criteria) this;
		}

		public Criteria andProcessedIsNull() {
			addCriterion("processed is null");
			return (Criteria) this;
		}

		public Criteria andProcessedIsNotNull() {
			addCriterion("processed is not null");
			return (Criteria) this;
		}

		public Criteria andProcessedEqualTo(Integer value) {
			addCriterion("processed =", value, "processed");
			return (Criteria) this;
		}

		public Criteria andProcessedNotEqualTo(Integer value) {
			addCriterion("processed <>", value, "processed");
			return (Criteria) this;
		}

		public Criteria andProcessedGreaterThan(Integer value) {
			addCriterion("processed >", value, "processed");
			return (Criteria) this;
		}

		public Criteria andProcessedGreaterThanOrEqualTo(Integer value) {
			addCriterion("processed >=", value, "processed");
			return (Criteria) this;
		}

		public Criteria andProcessedLessThan(Integer value) {
			addCriterion("processed <", value, "processed");
			return (Criteria) this;
		}

		public Criteria andProcessedLessThanOrEqualTo(Integer value) {
			addCriterion("processed <=", value, "processed");
			return (Criteria) this;
		}

		public Criteria andProcessedIn(List<Integer> values) {
			addCriterion("processed in", values, "processed");
			return (Criteria) this;
		}

		public Criteria andProcessedNotIn(List<Integer> values) {
			addCriterion("processed not in", values, "processed");
			return (Criteria) this;
		}

		public Criteria andProcessedBetween(Integer value1, Integer value2) {
			addCriterion("processed between", value1, value2, "processed");
			return (Criteria) this;
		}

		public Criteria andProcessedNotBetween(Integer value1, Integer value2) {
			addCriterion("processed not between", value1, value2, "processed");
			return (Criteria) this;
		}

		public Criteria andDisabledIsNull() {
			addCriterion("disabled is null");
			return (Criteria) this;
		}

		public Criteria andDisabledIsNotNull() {
			addCriterion("disabled is not null");
			return (Criteria) this;
		}

		public Criteria andDisabledEqualTo(Integer value) {
			addCriterion("disabled =", value, "disabled");
			return (Criteria) this;
		}

		public Criteria andDisabledNotEqualTo(Integer value) {
			addCriterion("disabled <>", value, "disabled");
			return (Criteria) this;
		}

		public Criteria andDisabledGreaterThan(Integer value) {
			addCriterion("disabled >", value, "disabled");
			return (Criteria) this;
		}

		public Criteria andDisabledGreaterThanOrEqualTo(Integer value) {
			addCriterion("disabled >=", value, "disabled");
			return (Criteria) this;
		}

		public Criteria andDisabledLessThan(Integer value) {
			addCriterion("disabled <", value, "disabled");
			return (Criteria) this;
		}

		public Criteria andDisabledLessThanOrEqualTo(Integer value) {
			addCriterion("disabled <=", value, "disabled");
			return (Criteria) this;
		}

		public Criteria andDisabledIn(List<Integer> values) {
			addCriterion("disabled in", values, "disabled");
			return (Criteria) this;
		}

		public Criteria andDisabledNotIn(List<Integer> values) {
			addCriterion("disabled not in", values, "disabled");
			return (Criteria) this;
		}

		public Criteria andDisabledBetween(Integer value1, Integer value2) {
			addCriterion("disabled between", value1, value2, "disabled");
			return (Criteria) this;
		}

		public Criteria andDisabledNotBetween(Integer value1, Integer value2) {
			addCriterion("disabled not between", value1, value2, "disabled");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("add_time is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("add_time is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterion("add_time =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterion("add_time <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterion("add_time >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("add_time >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterion("add_time <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("add_time <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterion("add_time in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterion("add_time not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterion("add_time between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("add_time not between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyIsNull() {
			addCriterion("last_modify is null");
			return (Criteria) this;
		}

		public Criteria andLastModifyIsNotNull() {
			addCriterion("last_modify is not null");
			return (Criteria) this;
		}

		public Criteria andLastModifyEqualTo(Date value) {
			addCriterion("last_modify =", value, "lastModify");
			return (Criteria) this;
		}

		public Criteria andLastModifyNotEqualTo(Date value) {
			addCriterion("last_modify <>", value, "lastModify");
			return (Criteria) this;
		}

		public Criteria andLastModifyGreaterThan(Date value) {
			addCriterion("last_modify >", value, "lastModify");
			return (Criteria) this;
		}

		public Criteria andLastModifyGreaterThanOrEqualTo(Date value) {
			addCriterion("last_modify >=", value, "lastModify");
			return (Criteria) this;
		}

		public Criteria andLastModifyLessThan(Date value) {
			addCriterion("last_modify <", value, "lastModify");
			return (Criteria) this;
		}

		public Criteria andLastModifyLessThanOrEqualTo(Date value) {
			addCriterion("last_modify <=", value, "lastModify");
			return (Criteria) this;
		}

		public Criteria andLastModifyIn(List<Date> values) {
			addCriterion("last_modify in", values, "lastModify");
			return (Criteria) this;
		}

		public Criteria andLastModifyNotIn(List<Date> values) {
			addCriterion("last_modify not in", values, "lastModify");
			return (Criteria) this;
		}

		public Criteria andLastModifyBetween(Date value1, Date value2) {
			addCriterion("last_modify between", value1, value2, "lastModify");
			return (Criteria) this;
		}

		public Criteria andLastModifyNotBetween(Date value1, Date value2) {
			addCriterion("last_modify not between", value1, value2,
					"lastModify");
			return (Criteria) this;
		}

		public Criteria andDOrderIsNull() {
			addCriterion("d_order is null");
			return (Criteria) this;
		}

		public Criteria andDOrderIsNotNull() {
			addCriterion("d_order is not null");
			return (Criteria) this;
		}

		public Criteria andDOrderEqualTo(Integer value) {
			addCriterion("d_order =", value, "dOrder");
			return (Criteria) this;
		}

		public Criteria andDOrderNotEqualTo(Integer value) {
			addCriterion("d_order <>", value, "dOrder");
			return (Criteria) this;
		}

		public Criteria andDOrderGreaterThan(Integer value) {
			addCriterion("d_order >", value, "dOrder");
			return (Criteria) this;
		}

		public Criteria andDOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("d_order >=", value, "dOrder");
			return (Criteria) this;
		}

		public Criteria andDOrderLessThan(Integer value) {
			addCriterion("d_order <", value, "dOrder");
			return (Criteria) this;
		}

		public Criteria andDOrderLessThanOrEqualTo(Integer value) {
			addCriterion("d_order <=", value, "dOrder");
			return (Criteria) this;
		}

		public Criteria andDOrderIn(List<Integer> values) {
			addCriterion("d_order in", values, "dOrder");
			return (Criteria) this;
		}

		public Criteria andDOrderNotIn(List<Integer> values) {
			addCriterion("d_order not in", values, "dOrder");
			return (Criteria) this;
		}

		public Criteria andDOrderBetween(Integer value1, Integer value2) {
			addCriterion("d_order between", value1, value2, "dOrder");
			return (Criteria) this;
		}

		public Criteria andDOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("d_order not between", value1, value2, "dOrder");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_business_storeviolation
	 * @mbggenerated  Fri Jun 12 09:26:34 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_business_storeviolation
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 28 16:22:25 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}