package com.cnit.yoyo.dao.shop;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cnit.yoyo.model.shop.CompanyCheckCat;
import com.cnit.yoyo.model.shop.CompanyCheckCatExample;

public interface CompanyCheckCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_check_category
     *
     * @mbggenerated Wed Jun 10 16:05:11 CST 2015
     */
    int countByExample(CompanyCheckCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_check_category
     *
     * @mbggenerated Wed Jun 10 16:05:11 CST 2015
     */
    int deleteByExample(CompanyCheckCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_check_category
     *
     * @mbggenerated Wed Jun 10 16:05:11 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_check_category
     *
     * @mbggenerated Wed Jun 10 16:05:11 CST 2015
     */
    int insert(CompanyCheckCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_check_category
     *
     * @mbggenerated Wed Jun 10 16:05:11 CST 2015
     */
    int insertSelective(CompanyCheckCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_check_category
     *
     * @mbggenerated Wed Jun 10 16:05:11 CST 2015
     */
    List<CompanyCheckCat> selectByExample(CompanyCheckCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_check_category
     *
     * @mbggenerated Wed Jun 10 16:05:11 CST 2015
     */
    CompanyCheckCat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_check_category
     *
     * @mbggenerated Wed Jun 10 16:05:11 CST 2015
     */
    int updateByExampleSelective(@Param("record") CompanyCheckCat record, @Param("example") CompanyCheckCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_check_category
     *
     * @mbggenerated Wed Jun 10 16:05:11 CST 2015
     */
    int updateByExample(@Param("record") CompanyCheckCat record, @Param("example") CompanyCheckCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_check_category
     *
     * @mbggenerated Wed Jun 10 16:05:11 CST 2015
     */
    int updateByPrimaryKeySelective(CompanyCheckCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_check_category
     *
     * @mbggenerated Wed Jun 10 16:05:11 CST 2015
     */
    int updateByPrimaryKey(CompanyCheckCat record);
    
    
    int save(Map<String,Object> map);
    int deleteByCompanyId(@Param("companyId")Integer companyId);
    int deleteByCompanyIds(Integer [] ids);
    List<CompanyCheckCat> getShopGoodsCat(@Param("companyId")Integer companyId);
    
}