package com.cnit.yoyo.dao.shop;

import com.cnit.yoyo.model.shop.StoreGrade;
import com.cnit.yoyo.model.shop.StoreGradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
/**
 * 店铺等级
 * @ClassName: StoreGradeMapper 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author xiaox
 * @date 2015-4-18 下午3:17:58
 */
public interface StoreGradeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storegrade
	 * @mbggenerated  Tue Apr 28 16:21:26 CST 2015
	 */
	int countByExample(StoreGradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storegrade
	 * @mbggenerated  Tue Apr 28 16:21:26 CST 2015
	 */
	int deleteByExample(StoreGradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storegrade
	 * @mbggenerated  Tue Apr 28 16:21:26 CST 2015
	 */
	int deleteByPrimaryKey(Long gradeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storegrade
	 * @mbggenerated  Tue Apr 28 16:21:26 CST 2015
	 */
	int insert(StoreGrade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storegrade
	 * @mbggenerated  Tue Apr 28 16:21:26 CST 2015
	 */
	int insertSelective(StoreGrade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storegrade
	 * @mbggenerated  Tue Apr 28 16:21:26 CST 2015
	 */
	List<StoreGrade> selectByExample(StoreGradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storegrade
	 * @mbggenerated  Tue Apr 28 16:21:26 CST 2015
	 */
	StoreGrade selectByPrimaryKey(Long gradeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storegrade
	 * @mbggenerated  Tue Apr 28 16:21:26 CST 2015
	 */
	int updateByExampleSelective(@Param("record") StoreGrade record,
			@Param("example") StoreGradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storegrade
	 * @mbggenerated  Tue Apr 28 16:21:26 CST 2015
	 */
	int updateByExample(@Param("record") StoreGrade record,
			@Param("example") StoreGradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storegrade
	 * @mbggenerated  Tue Apr 28 16:21:26 CST 2015
	 */
	int updateByPrimaryKeySelective(StoreGrade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_storegrade
	 * @mbggenerated  Tue Apr 28 16:21:26 CST 2015
	 */
	int updateByPrimaryKey(StoreGrade record);
}