package com.cnit.yoyo.dao.shop;

import com.cnit.yoyo.model.shop.Violation;
import com.cnit.yoyo.model.shop.ViolationExample;
import com.cnit.yoyo.model.shop.dto.ViolationDTO;
import com.cnit.yoyo.model.shop.dto.ViolationQryDTO;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ViolationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_violation
     *
     * @mbggenerated Wed Jun 03 17:11:04 CST 2015
     */
    int countByExample(ViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_violation
     *
     * @mbggenerated Wed Jun 03 17:11:04 CST 2015
     */
    int deleteByExample(ViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_violation
     *
     * @mbggenerated Wed Jun 03 17:11:04 CST 2015
     */
    int deleteByPrimaryKey(Integer violationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_violation
     *
     * @mbggenerated Wed Jun 03 17:11:04 CST 2015
     */
    int insert(Violation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_violation
     *
     * @mbggenerated Wed Jun 03 17:11:04 CST 2015
     */
    int insertSelective(Violation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_violation
     *
     * @mbggenerated Wed Jun 03 17:11:04 CST 2015
     */
    List<Violation> selectByExampleWithBLOBs(ViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_violation
     *
     * @mbggenerated Wed Jun 03 17:11:04 CST 2015
     */
    List<Violation> selectByExample(ViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_violation
     *
     * @mbggenerated Wed Jun 03 17:11:04 CST 2015
     */
    Violation selectByPrimaryKey(Integer violationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_violation
     *
     * @mbggenerated Wed Jun 03 17:11:04 CST 2015
     */
    int updateByExampleSelective(@Param("record") Violation record, @Param("example") ViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_violation
     *
     * @mbggenerated Wed Jun 03 17:11:04 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") Violation record, @Param("example") ViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_violation
     *
     * @mbggenerated Wed Jun 03 17:11:04 CST 2015
     */
    int updateByExample(@Param("record") Violation record, @Param("example") ViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_violation
     *
     * @mbggenerated Wed Jun 03 17:11:04 CST 2015
     */
    int updateByPrimaryKeySelective(Violation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_violation
     *
     * @mbggenerated Wed Jun 03 17:11:04 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(Violation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_violation
     *
     * @mbggenerated Wed Jun 03 17:11:04 CST 2015
     */
    int updateByPrimaryKey(Violation record);
    
    /**
     * @Title:  selectByQryDto  
     * @Description:  TODO(根据条件查询对象)  
     * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
     * @date 2015-6-4 下午3:29:54  
     * @version 1.0.0 
     * @param @param dto
     * @param @return
     * @return List<ViolationDTO>  返回类型 
     * @throws
     */
    List<ViolationDTO> selectByQryDto(ViolationQryDTO dto);
    
    /**
     * @Title:  selectByCatId  
     * @Description:  TODO(根据违规类型id查询对象)  
     * @author <a href="cmlai@chinacnit.com">赖彩妙</a> 
     * @date 2015-6-9 下午6:27:54  
     * @version 1.0.0 
     * @param @param violationId
     * @param @return
     * @return Violation  返回类型 
     * @throws
     */
    List<Violation> selectByCatId(Integer catId);
}