package com.cnit.yoyo.dao.consult;

import com.cnit.yoyo.model.other.consult.ConsultCommentBaseArguments;

/**  
* @Title: ConsultCommentBaseArgumentsMapper.java
* @Package com.cnit.yoyo.dao.consult
* @Description: 咨询评论基础设置
* @Author 王鹏
* @date 2015-4-28 上午9:26:14
* @version V1.0  
*/ 
public interface ConsultCommentBaseArgumentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult_comment_base_arguments
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult_comment_base_arguments
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int insert(ConsultCommentBaseArguments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult_comment_base_arguments
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int insertSelective(ConsultCommentBaseArguments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult_comment_base_arguments
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    ConsultCommentBaseArguments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult_comment_base_arguments
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int updateByPrimaryKeySelective(ConsultCommentBaseArguments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult_comment_base_arguments
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int updateByPrimaryKey(ConsultCommentBaseArguments record);
    
    ConsultCommentBaseArguments selectBaseArguments();
}