package com.cnit.yoyo.dao.consult;

import com.cnit.yoyo.model.other.consult.ConsultCommentArguments;

/**  
* @Title: ConsultCommentArgumentsMapper.java
* @Package com.cnit.yoyo.dao.consult
* @Description: 咨询评论设置
* @Author 王鹏
* @date 2015-4-28 上午9:25:19
* @version V1.0  
*/ 
public interface ConsultCommentArgumentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult_comment_arguments
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult_comment_arguments
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int insert(ConsultCommentArguments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult_comment_arguments
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int insertSelective(ConsultCommentArguments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult_comment_arguments
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    ConsultCommentArguments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult_comment_arguments
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int updateByPrimaryKeySelective(ConsultCommentArguments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult_comment_arguments
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int updateByPrimaryKey(ConsultCommentArguments record);
    
    ConsultCommentArguments selectByArgsType(String argsType);
}