package com.cnit.yoyo.dao.consult;

import java.util.List;

import com.cnit.yoyo.model.other.consult.ConsultItems;
import com.cnit.yoyo.model.other.consult.GoodsPoint;

/**  
* @Title: ConsultItemsMapper.java
* @Package com.cnit.yoyo.dao.consult
* @Description: 咨询项设置
* @Author 王鹏
* @date 2015-4-28 上午9:22:04
* @version V1.0  
*/ 
public interface ConsultItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult_items
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int insert(ConsultItems record);

    int deleteByPrimaryKey(Integer id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult_items
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int insertSelective(ConsultItems record);
    
    List<ConsultItems> selectAllCnsultItems();
    
    int batchUpdateConsultItems(List<ConsultItems> consultItems);
    
    int batchSaveConsultItems(List<ConsultItems> consultItems);
}