package com.cnit.yoyo.dao.consult;

import java.util.List;

import com.cnit.yoyo.model.other.consult.GoodsPoint;

/**  
* @Title: GoodsPointMapper.java
* @Package com.cnit.yoyo.dao.consult
* @Description: 商品评分设置表
* @Author 王鹏
* @date 2015-4-28 上午9:25:00
* @version V1.0  
*/ 
public interface GoodsPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_point
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_point
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int insert(GoodsPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_point
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int insertSelective(GoodsPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_point
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    GoodsPoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_point
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int updateByPrimaryKeySelective(GoodsPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_point
     *
     * @mbggenerated Tue Apr 28 09:16:20 CST 2015
     */
    int updateByPrimaryKey(GoodsPoint record);
    
    int batchUpdateGoodsPoint(List<GoodsPoint> goodsPoints);
    
    int batchSaveGoodsPoint(List<GoodsPoint> goodsPoints);
    
    List<GoodsPoint> selectAllGoodsPoint();
}