package com.cnit.yoyo.model.trade;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class AftersalesReturnProduct implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.return_id
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Long returnId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.order_id
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Long orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.return_bn
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private String returnBn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.title
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.old_return_id
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Long oldReturnId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.status
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.image_file3
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private String imageFile3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.image_file
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private String imageFile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.image_file2
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private String imageFile2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.intereven_image
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private String interevenImage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.add_time
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.seller_amount
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private BigDecimal sellerAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.amount
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private BigDecimal amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.shipping_amount
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private BigDecimal shippingAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.close_time
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Date closeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.store_id
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Long storeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.refund_type
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Integer refundType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.is_intervene
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Integer isIntervene;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.intervene_reason
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Integer interveneReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.intervene_phone
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private String intervenePhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.intervene_mail
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private String interveneMail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.ship_cost
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private BigDecimal shipCost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.amount_seller
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private BigDecimal amountSeller;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.is_safeguard
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Integer isSafeguard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.safeguard_type
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Integer safeguardType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.safeguard_require
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Integer safeguardRequire;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.refund_address
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private String refundAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.return_score
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private BigDecimal returnScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.image_upload
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private String imageUpload;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.is_return_money
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Integer isReturnMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.return_money_id
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private String returnMoneyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.disabled
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Integer disabled;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_aftersales_return_product.create_time
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_aftersales_return_product
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.return_id
	 * 
	 * @return the value of t_aftersales_return_product.return_id
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Long getReturnId() {
		return returnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.return_id
	 * 
	 * @param returnId
	 *            the value for t_aftersales_return_product.return_id
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setReturnId(Long returnId) {
		this.returnId = returnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.order_id
	 * 
	 * @return the value of t_aftersales_return_product.order_id
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Long getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.order_id
	 * 
	 * @param orderId
	 *            the value for t_aftersales_return_product.order_id
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.return_bn
	 * 
	 * @return the value of t_aftersales_return_product.return_bn
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public String getReturnBn() {
		return returnBn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.return_bn
	 * 
	 * @param returnBn
	 *            the value for t_aftersales_return_product.return_bn
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setReturnBn(String returnBn) {
		this.returnBn = returnBn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.title
	 * 
	 * @return the value of t_aftersales_return_product.title
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.title
	 * 
	 * @param title
	 *            the value for t_aftersales_return_product.title
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.old_return_id
	 * 
	 * @return the value of t_aftersales_return_product.old_return_id
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Long getOldReturnId() {
		return oldReturnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.old_return_id
	 * 
	 * @param oldReturnId
	 *            the value for t_aftersales_return_product.old_return_id
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setOldReturnId(Long oldReturnId) {
		this.oldReturnId = oldReturnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.status
	 * 
	 * @return the value of t_aftersales_return_product.status
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.status
	 * 
	 * @param status
	 *            the value for t_aftersales_return_product.status
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.image_file3
	 * 
	 * @return the value of t_aftersales_return_product.image_file3
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public String getImageFile3() {
		return imageFile3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.image_file3
	 * 
	 * @param imageFile3
	 *            the value for t_aftersales_return_product.image_file3
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setImageFile3(String imageFile3) {
		this.imageFile3 = imageFile3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.image_file
	 * 
	 * @return the value of t_aftersales_return_product.image_file
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public String getImageFile() {
		return imageFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.image_file
	 * 
	 * @param imageFile
	 *            the value for t_aftersales_return_product.image_file
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setImageFile(String imageFile) {
		this.imageFile = imageFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.image_file2
	 * 
	 * @return the value of t_aftersales_return_product.image_file2
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public String getImageFile2() {
		return imageFile2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.image_file2
	 * 
	 * @param imageFile2
	 *            the value for t_aftersales_return_product.image_file2
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setImageFile2(String imageFile2) {
		this.imageFile2 = imageFile2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.intereven_image
	 * 
	 * @return the value of t_aftersales_return_product.intereven_image
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public String getInterevenImage() {
		return interevenImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.intereven_image
	 * 
	 * @param interevenImage
	 *            the value for t_aftersales_return_product.intereven_image
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setInterevenImage(String interevenImage) {
		this.interevenImage = interevenImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.add_time
	 * 
	 * @return the value of t_aftersales_return_product.add_time
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.add_time
	 * 
	 * @param addTime
	 *            the value for t_aftersales_return_product.add_time
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.seller_amount
	 * 
	 * @return the value of t_aftersales_return_product.seller_amount
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public BigDecimal getSellerAmount() {
		return sellerAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.seller_amount
	 * 
	 * @param sellerAmount
	 *            the value for t_aftersales_return_product.seller_amount
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setSellerAmount(BigDecimal sellerAmount) {
		this.sellerAmount = sellerAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.amount
	 * 
	 * @return the value of t_aftersales_return_product.amount
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.amount
	 * 
	 * @param amount
	 *            the value for t_aftersales_return_product.amount
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.shipping_amount
	 * 
	 * @return the value of t_aftersales_return_product.shipping_amount
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public BigDecimal getShippingAmount() {
		return shippingAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.shipping_amount
	 * 
	 * @param shippingAmount
	 *            the value for t_aftersales_return_product.shipping_amount
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setShippingAmount(BigDecimal shippingAmount) {
		this.shippingAmount = shippingAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.close_time
	 * 
	 * @return the value of t_aftersales_return_product.close_time
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Date getCloseTime() {
		return closeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.close_time
	 * 
	 * @param closeTime
	 *            the value for t_aftersales_return_product.close_time
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setCloseTime(Date closeTime) {
		this.closeTime = closeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.store_id
	 * 
	 * @return the value of t_aftersales_return_product.store_id
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Long getStoreId() {
		return storeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.store_id
	 * 
	 * @param storeId
	 *            the value for t_aftersales_return_product.store_id
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setStoreId(Long storeId) {
		this.storeId = storeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.refund_type
	 * 
	 * @return the value of t_aftersales_return_product.refund_type
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Integer getRefundType() {
		return refundType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.refund_type
	 * 
	 * @param refundType
	 *            the value for t_aftersales_return_product.refund_type
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setRefundType(Integer refundType) {
		this.refundType = refundType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.is_intervene
	 * 
	 * @return the value of t_aftersales_return_product.is_intervene
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Integer getIsIntervene() {
		return isIntervene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.is_intervene
	 * 
	 * @param isIntervene
	 *            the value for t_aftersales_return_product.is_intervene
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setIsIntervene(Integer isIntervene) {
		this.isIntervene = isIntervene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.intervene_reason
	 * 
	 * @return the value of t_aftersales_return_product.intervene_reason
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Integer getInterveneReason() {
		return interveneReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.intervene_reason
	 * 
	 * @param interveneReason
	 *            the value for t_aftersales_return_product.intervene_reason
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setInterveneReason(Integer interveneReason) {
		this.interveneReason = interveneReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.intervene_phone
	 * 
	 * @return the value of t_aftersales_return_product.intervene_phone
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public String getIntervenePhone() {
		return intervenePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.intervene_phone
	 * 
	 * @param intervenePhone
	 *            the value for t_aftersales_return_product.intervene_phone
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setIntervenePhone(String intervenePhone) {
		this.intervenePhone = intervenePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.intervene_mail
	 * 
	 * @return the value of t_aftersales_return_product.intervene_mail
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public String getInterveneMail() {
		return interveneMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.intervene_mail
	 * 
	 * @param interveneMail
	 *            the value for t_aftersales_return_product.intervene_mail
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setInterveneMail(String interveneMail) {
		this.interveneMail = interveneMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.ship_cost
	 * 
	 * @return the value of t_aftersales_return_product.ship_cost
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public BigDecimal getShipCost() {
		return shipCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.ship_cost
	 * 
	 * @param shipCost
	 *            the value for t_aftersales_return_product.ship_cost
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setShipCost(BigDecimal shipCost) {
		this.shipCost = shipCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.amount_seller
	 * 
	 * @return the value of t_aftersales_return_product.amount_seller
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public BigDecimal getAmountSeller() {
		return amountSeller;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.amount_seller
	 * 
	 * @param amountSeller
	 *            the value for t_aftersales_return_product.amount_seller
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setAmountSeller(BigDecimal amountSeller) {
		this.amountSeller = amountSeller;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.is_safeguard
	 * 
	 * @return the value of t_aftersales_return_product.is_safeguard
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Integer getIsSafeguard() {
		return isSafeguard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.is_safeguard
	 * 
	 * @param isSafeguard
	 *            the value for t_aftersales_return_product.is_safeguard
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setIsSafeguard(Integer isSafeguard) {
		this.isSafeguard = isSafeguard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.safeguard_type
	 * 
	 * @return the value of t_aftersales_return_product.safeguard_type
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Integer getSafeguardType() {
		return safeguardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.safeguard_type
	 * 
	 * @param safeguardType
	 *            the value for t_aftersales_return_product.safeguard_type
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setSafeguardType(Integer safeguardType) {
		this.safeguardType = safeguardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * t_aftersales_return_product.safeguard_require
	 * 
	 * @return the value of t_aftersales_return_product.safeguard_require
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Integer getSafeguardRequire() {
		return safeguardRequire;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * t_aftersales_return_product.safeguard_require
	 * 
	 * @param safeguardRequire
	 *            the value for t_aftersales_return_product.safeguard_require
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */ 
	
	public void setSafeguardRequire(Integer safeguardRequire) {
		this.safeguardRequire = safeguardRequire;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.refund_address
	 * 
	 * @return the value of t_aftersales_return_product.refund_address
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public String getRefundAddress() {
		return refundAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.refund_address
	 * 
	 * @param refundAddress
	 *            the value for t_aftersales_return_product.refund_address
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setRefundAddress(String refundAddress) {
		this.refundAddress = refundAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.return_score
	 * 
	 * @return the value of t_aftersales_return_product.return_score
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public BigDecimal getReturnScore() {
		return returnScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.return_score
	 * 
	 * @param returnScore
	 *            the value for t_aftersales_return_product.return_score
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setReturnScore(BigDecimal returnScore) {
		this.returnScore = returnScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.image_upload
	 * 
	 * @return the value of t_aftersales_return_product.image_upload
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public String getImageUpload() {
		return imageUpload;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.image_upload
	 * 
	 * @param imageUpload
	 *            the value for t_aftersales_return_product.image_upload
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setImageUpload(String imageUpload) {
		this.imageUpload = imageUpload;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.is_return_money
	 * 
	 * @return the value of t_aftersales_return_product.is_return_money
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Integer getIsReturnMoney() {
		return isReturnMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.is_return_money
	 * 
	 * @param isReturnMoney
	 *            the value for t_aftersales_return_product.is_return_money
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setIsReturnMoney(Integer isReturnMoney) {
		this.isReturnMoney = isReturnMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.return_money_id
	 * 
	 * @return the value of t_aftersales_return_product.return_money_id
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public String getReturnMoneyId() {
		return returnMoneyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.return_money_id
	 * 
	 * @param returnMoneyId
	 *            the value for t_aftersales_return_product.return_money_id
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setReturnMoneyId(String returnMoneyId) {
		this.returnMoneyId = returnMoneyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_aftersales_return_product.disabled
	 * 
	 * @return the value of t_aftersales_return_product.disabled
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public Integer getDisabled() {
		return disabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_aftersales_return_product.disabled
	 * 
	 * @param disabled
	 *            the value for t_aftersales_return_product.disabled
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	public void setDisabled(Integer disabled) {
		this.disabled = disabled;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_aftersales_return_product
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", returnId=").append(returnId);
		sb.append(", orderId=").append(orderId);
		sb.append(", returnBn=").append(returnBn);
		sb.append(", title=").append(title);
		sb.append(", oldReturnId=").append(oldReturnId);
		sb.append(", status=").append(status);
		sb.append(", imageFile3=").append(imageFile3);
		sb.append(", imageFile=").append(imageFile);
		sb.append(", imageFile2=").append(imageFile2);
		sb.append(", interevenImage=").append(interevenImage);
		sb.append(", addTime=").append(addTime);
		sb.append(", sellerAmount=").append(sellerAmount);
		sb.append(", amount=").append(amount);
		sb.append(", shippingAmount=").append(shippingAmount);
		sb.append(", closeTime=").append(closeTime);
		sb.append(", storeId=").append(storeId);
		sb.append(", refundType=").append(refundType);
		sb.append(", isIntervene=").append(isIntervene);
		sb.append(", interveneReason=").append(interveneReason);
		sb.append(", intervenePhone=").append(intervenePhone);
		sb.append(", interveneMail=").append(interveneMail);
		sb.append(", shipCost=").append(shipCost);
		sb.append(", amountSeller=").append(amountSeller);
		sb.append(", isSafeguard=").append(isSafeguard);
		sb.append(", safeguardType=").append(safeguardType);
		sb.append(", safeguardRequire=").append(safeguardRequire);
		sb.append(", refundAddress=").append(refundAddress);
		sb.append(", returnScore=").append(returnScore);
		sb.append(", imageUpload=").append(imageUpload);
		sb.append(", isReturnMoney=").append(isReturnMoney);
		sb.append(", returnMoneyId=").append(returnMoneyId);
		sb.append(", disabled=").append(disabled);
		sb.append(", createTime=").append(createTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_aftersales_return_product
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		AftersalesReturnProduct other = (AftersalesReturnProduct) that;
		return (this.getReturnId() == null ? other.getReturnId() == null : this
				.getReturnId().equals(other.getReturnId()))
				&& (this.getOrderId() == null ? other.getOrderId() == null
						: this.getOrderId().equals(other.getOrderId()))
				&& (this.getReturnBn() == null ? other.getReturnBn() == null
						: this.getReturnBn().equals(other.getReturnBn()))
				&& (this.getTitle() == null ? other.getTitle() == null : this
						.getTitle().equals(other.getTitle()))
				&& (this.getOldReturnId() == null ? other.getOldReturnId() == null
						: this.getOldReturnId().equals(other.getOldReturnId()))
				&& (this.getStatus() == null ? other.getStatus() == null : this
						.getStatus().equals(other.getStatus()))
				&& (this.getImageFile3() == null ? other.getImageFile3() == null
						: this.getImageFile3().equals(other.getImageFile3()))
				&& (this.getImageFile() == null ? other.getImageFile() == null
						: this.getImageFile().equals(other.getImageFile()))
				&& (this.getImageFile2() == null ? other.getImageFile2() == null
						: this.getImageFile2().equals(other.getImageFile2()))
				&& (this.getInterevenImage() == null ? other
						.getInterevenImage() == null : this.getInterevenImage()
						.equals(other.getInterevenImage()))
				&& (this.getAddTime() == null ? other.getAddTime() == null
						: this.getAddTime().equals(other.getAddTime()))
				&& (this.getSellerAmount() == null ? other.getSellerAmount() == null
						: this.getSellerAmount()
								.equals(other.getSellerAmount()))
				&& (this.getAmount() == null ? other.getAmount() == null : this
						.getAmount().equals(other.getAmount()))
				&& (this.getShippingAmount() == null ? other
						.getShippingAmount() == null : this.getShippingAmount()
						.equals(other.getShippingAmount()))
				&& (this.getCloseTime() == null ? other.getCloseTime() == null
						: this.getCloseTime().equals(other.getCloseTime()))
				&& (this.getStoreId() == null ? other.getStoreId() == null
						: this.getStoreId().equals(other.getStoreId()))
				&& (this.getRefundType() == null ? other.getRefundType() == null
						: this.getRefundType().equals(other.getRefundType()))
				&& (this.getIsIntervene() == null ? other.getIsIntervene() == null
						: this.getIsIntervene().equals(other.getIsIntervene()))
				&& (this.getInterveneReason() == null ? other
						.getInterveneReason() == null : this
						.getInterveneReason()
						.equals(other.getInterveneReason()))
				&& (this.getIntervenePhone() == null ? other
						.getIntervenePhone() == null : this.getIntervenePhone()
						.equals(other.getIntervenePhone()))
				&& (this.getInterveneMail() == null ? other.getInterveneMail() == null
						: this.getInterveneMail().equals(
								other.getInterveneMail()))
				&& (this.getShipCost() == null ? other.getShipCost() == null
						: this.getShipCost().equals(other.getShipCost()))
				&& (this.getAmountSeller() == null ? other.getAmountSeller() == null
						: this.getAmountSeller()
								.equals(other.getAmountSeller()))
				&& (this.getIsSafeguard() == null ? other.getIsSafeguard() == null
						: this.getIsSafeguard().equals(other.getIsSafeguard()))
				&& (this.getSafeguardType() == null ? other.getSafeguardType() == null
						: this.getSafeguardType().equals(
								other.getSafeguardType()))
				&& (this.getSafeguardRequire() == null ? other
						.getSafeguardRequire() == null : this
						.getSafeguardRequire().equals(
								other.getSafeguardRequire()))
				&& (this.getRefundAddress() == null ? other.getRefundAddress() == null
						: this.getRefundAddress().equals(
								other.getRefundAddress()))
				&& (this.getReturnScore() == null ? other.getReturnScore() == null
						: this.getReturnScore().equals(other.getReturnScore()))
				&& (this.getImageUpload() == null ? other.getImageUpload() == null
						: this.getImageUpload().equals(other.getImageUpload()))
				&& (this.getIsReturnMoney() == null ? other.getIsReturnMoney() == null
						: this.getIsReturnMoney().equals(
								other.getIsReturnMoney()))
				&& (this.getReturnMoneyId() == null ? other.getReturnMoneyId() == null
						: this.getReturnMoneyId().equals(
								other.getReturnMoneyId()))
				&& (this.getDisabled() == null ? other.getDisabled() == null
						: this.getDisabled().equals(other.getDisabled()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_aftersales_return_product
	 * 
	 * @mbggenerated Sat Apr 18 17:01:00 CST 2015
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getReturnId() == null) ? 0 : getReturnId().hashCode());
		result = prime * result
				+ ((getOrderId() == null) ? 0 : getOrderId().hashCode());
		result = prime * result
				+ ((getReturnBn() == null) ? 0 : getReturnBn().hashCode());
		result = prime * result
				+ ((getTitle() == null) ? 0 : getTitle().hashCode());
		result = prime
				* result
				+ ((getOldReturnId() == null) ? 0 : getOldReturnId().hashCode());
		result = prime * result
				+ ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result
				+ ((getImageFile3() == null) ? 0 : getImageFile3().hashCode());
		result = prime * result
				+ ((getImageFile() == null) ? 0 : getImageFile().hashCode());
		result = prime * result
				+ ((getImageFile2() == null) ? 0 : getImageFile2().hashCode());
		result = prime
				* result
				+ ((getInterevenImage() == null) ? 0 : getInterevenImage()
						.hashCode());
		result = prime * result
				+ ((getAddTime() == null) ? 0 : getAddTime().hashCode());
		result = prime
				* result
				+ ((getSellerAmount() == null) ? 0 : getSellerAmount()
						.hashCode());
		result = prime * result
				+ ((getAmount() == null) ? 0 : getAmount().hashCode());
		result = prime
				* result
				+ ((getShippingAmount() == null) ? 0 : getShippingAmount()
						.hashCode());
		result = prime * result
				+ ((getCloseTime() == null) ? 0 : getCloseTime().hashCode());
		result = prime * result
				+ ((getStoreId() == null) ? 0 : getStoreId().hashCode());
		result = prime * result
				+ ((getRefundType() == null) ? 0 : getRefundType().hashCode());
		result = prime
				* result
				+ ((getIsIntervene() == null) ? 0 : getIsIntervene().hashCode());
		result = prime
				* result
				+ ((getInterveneReason() == null) ? 0 : getInterveneReason()
						.hashCode());
		result = prime
				* result
				+ ((getIntervenePhone() == null) ? 0 : getIntervenePhone()
						.hashCode());
		result = prime
				* result
				+ ((getInterveneMail() == null) ? 0 : getInterveneMail()
						.hashCode());
		result = prime * result
				+ ((getShipCost() == null) ? 0 : getShipCost().hashCode());
		result = prime
				* result
				+ ((getAmountSeller() == null) ? 0 : getAmountSeller()
						.hashCode());
		result = prime
				* result
				+ ((getIsSafeguard() == null) ? 0 : getIsSafeguard().hashCode());
		result = prime
				* result
				+ ((getSafeguardType() == null) ? 0 : getSafeguardType()
						.hashCode());
		result = prime
				* result
				+ ((getSafeguardRequire() == null) ? 0 : getSafeguardRequire()
						.hashCode());
		result = prime
				* result
				+ ((getRefundAddress() == null) ? 0 : getRefundAddress()
						.hashCode());
		result = prime
				* result
				+ ((getReturnScore() == null) ? 0 : getReturnScore().hashCode());
		result = prime
				* result
				+ ((getImageUpload() == null) ? 0 : getImageUpload().hashCode());
		result = prime
				* result
				+ ((getIsReturnMoney() == null) ? 0 : getIsReturnMoney()
						.hashCode());
		result = prime
				* result
				+ ((getReturnMoneyId() == null) ? 0 : getReturnMoneyId()
						.hashCode());
		result = prime * result
				+ ((getDisabled() == null) ? 0 : getDisabled().hashCode());
		result = prime * result
				+ ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		return result;
	}
}