package com.cnit.yoyo.dao.order;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cnit.yoyo.model.order.OrderLog;
import com.cnit.yoyo.model.order.OrderLogExample;
import com.cnit.yoyo.model.order.OrderLogWithBLOBs;

public interface OrderLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_log
	 * @mbggenerated  Thu Apr 16 13:59:11 CST 2015
	 */
	int deleteByExample(OrderLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_log
	 * @mbggenerated  Thu Apr 16 13:59:11 CST 2015
	 */
	int deleteByPrimaryKey(Integer logId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_log
	 * @mbggenerated  Thu Apr 16 13:59:11 CST 2015
	 */
	int insert(OrderLogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_log
	 * @mbggenerated  Thu Apr 16 13:59:11 CST 2015
	 */
	int insertSelective(OrderLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_log
	 * @mbggenerated  Thu Apr 16 13:59:11 CST 2015
	 */
	List<OrderLogWithBLOBs> selectByExampleWithBLOBs(OrderLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_log
	 * @mbggenerated  Thu Apr 16 13:59:11 CST 2015
	 */
	List<OrderLog> selectByExample(OrderLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_log
	 * @mbggenerated  Thu Apr 16 13:59:11 CST 2015
	 */
	OrderLogWithBLOBs selectByPrimaryKey(Integer logId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_log
	 * @mbggenerated  Thu Apr 16 13:59:11 CST 2015
	 */
	int updateByExampleSelective(@Param("record") OrderLogWithBLOBs record,
			@Param("example") OrderLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_log
	 * @mbggenerated  Thu Apr 16 13:59:11 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") OrderLogWithBLOBs record,
			@Param("example") OrderLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_log
	 * @mbggenerated  Thu Apr 16 13:59:11 CST 2015
	 */
	int updateByExample(@Param("record") OrderLog record,
			@Param("example") OrderLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_log
	 * @mbggenerated  Thu Apr 16 13:59:11 CST 2015
	 */
	int updateByPrimaryKeySelective(OrderLogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_log
	 * @mbggenerated  Thu Apr 16 13:59:11 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(OrderLogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_log
	 * @mbggenerated  Thu Apr 16 13:59:11 CST 2015
	 */
	int updateByPrimaryKey(OrderLog record);
	
	List<OrderLogWithBLOBs> selectByOrderId(Long orderId);
}