package com.cnit.yoyo.dao.order;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cnit.yoyo.model.order.Order;
import com.cnit.yoyo.model.order.dto.OrderDTO;
import com.cnit.yoyo.model.order.dto.OrderDetailDTO;
import com.cnit.yoyo.model.order.dto.OrderQryDTO;
import com.cnit.yoyo.model.order.dto.OrderRemarkDTO;
import com.cnit.yoyo.model.trade.dto.OrderSellsInfoDTO;
import com.cnit.yoyo.model.trade.dto.OrderTipsDTO;

public interface OrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_orders
	 * @mbggenerated  Mon Apr 13 16:49:11 CST 2015
	 */
	int deleteByPrimaryKey(Long orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_orders
	 * @mbggenerated  Mon Apr 13 16:49:11 CST 2015
	 */
	int insert(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_orders
	 * @mbggenerated  Mon Apr 13 16:49:11 CST 2015
	 */
	int insertSelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_orders
	 * @mbggenerated  Mon Apr 13 16:49:11 CST 2015
	 */
	Order selectByPrimaryKey(Long orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_orders
	 * @mbggenerated  Mon Apr 13 16:49:11 CST 2015
	 */
	int updateByPrimaryKeySelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_orders
	 * @mbggenerated  Mon Apr 13 16:49:11 CST 2015
	 */
	int updateByPrimaryKey(Order record);

	List<OrderDTO> selectOrderByParam(@Param("orderId")String orderId,@Param("payStatus")String payStatus,@Param("status")String status,@Param("shipStatusQ")String shipStatusQ,
			@Param("payment")String payment,@Param("orderType")String orderType,@Param("source")String source,
			@Param("refundStatus")String refundStatus, @Param("orderStmt")String orderBy);
	
	OrderDetailDTO selectOrderDetail(Long orderId);
	
	List<Object> selectOrderIdsListInfo(OrderQryDTO qryDTO);
	
	List<Object> selectOrderListInfo(OrderQryDTO qryDTO);
	
	Order selectOrderByOrderId(Long orderId);
	
	int updateOrderStatus(Map<String, Object> params);
	
	int updateOrderRemark(OrderRemarkDTO dto);
	
	int selectCountByPrimaryKey(Long orderId);
	
	List<Order> getAllOrderInfoList(Map<String, Object> orders);
	
	OrderTipsDTO selectOrderTips(Map<String, Object> param);
	
	OrderSellsInfoDTO selectShopSellsInfo(Map<String, Object> param);
	 
	/**
	  * @description <b>将24小时之前的订单取消</b>
	  * @author 王鹏
	  * @version 1.0.0
	  * @data 2015-7-1
	  * @param @return
	  * @return int
	*/
	int updateOrderStatusToDead();
}