package com.cnit.yoyo.dao.order;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cnit.yoyo.model.order.OrderRefunds;
import com.cnit.yoyo.model.order.OrderRefundsExample;
import com.cnit.yoyo.model.order.dto.OrderRefundsDTO;

public interface OrderRefundsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refunds
     *
     * @mbggenerated Fri Apr 17 11:32:57 CST 2015
     */
    int deleteByExample(OrderRefundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refunds
     *
     * @mbggenerated Fri Apr 17 11:32:57 CST 2015
     */
    int deleteByPrimaryKey(String refundId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refunds
     *
     * @mbggenerated Fri Apr 17 11:32:57 CST 2015
     */
    int insert(OrderRefunds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refunds
     *
     * @mbggenerated Fri Apr 17 11:32:57 CST 2015
     */
    int insertSelective(OrderRefunds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refunds
     *
     * @mbggenerated Fri Apr 17 11:32:57 CST 2015
     */
    List<OrderRefunds> selectByExample(OrderRefundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refunds
     *
     * @mbggenerated Fri Apr 17 11:32:57 CST 2015
     */
    OrderRefunds selectByPrimaryKey(String refundId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refunds
     *
     * @mbggenerated Fri Apr 17 11:32:57 CST 2015
     */
    int updateByExampleSelective(@Param("record") OrderRefunds record, @Param("example") OrderRefundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refunds
     *
     * @mbggenerated Fri Apr 17 11:32:57 CST 2015
     */
    int updateByExample(@Param("record") OrderRefunds record, @Param("example") OrderRefundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refunds
     *
     * @mbggenerated Fri Apr 17 11:32:57 CST 2015
     */
    int updateByPrimaryKeySelective(OrderRefunds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refunds
     *
     * @mbggenerated Fri Apr 17 11:32:57 CST 2015
     */
    int updateByPrimaryKey(OrderRefunds record);
    
    OrderRefunds selectOrderRefund(Long orderId);
    
    List<OrderRefundsDTO> selectOrderRefundByMapParams(Map<String, Object> params);
    
    OrderRefundsDTO selectOrderRefundById(String refundId);
}