package com.cnit.yoyo.model.thirdaccount;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class ThirdAccount implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_third_account.ACCOUNT_ID
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	private Integer accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_third_account.OPEN_ID
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	private String openId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_third_account.ACCOUNT_NAME
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	private String accountName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_third_account.ACCOUNT_TYPE
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	private String accountType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_third_account.PAM_ACCOUNT_ID
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	private Integer pamAccountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_third_account.ACCOUNT_STATUS
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	private String accountStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_third_account.REG_IP
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	private String regIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_third_account.REG_TIME
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	private String regTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_third_account.SOURCE
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	private String source;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_third_account.LOGIN_COUNT
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	private Integer loginCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_third_account.LOGIN_IP
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	private String loginIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_third_account.CREATE_TIME
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_third_account.UPDATE_TIME
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_third_account
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	
	private String loginPassword;
	
	private String loginName;
	
	private String yyAccountType;
	
	private boolean firstRegist;
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_third_account.ACCOUNT_ID
	 * @return  the value of t_third_account.ACCOUNT_ID
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public Integer getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_third_account.ACCOUNT_ID
	 * @param accountId  the value for t_third_account.ACCOUNT_ID
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_third_account.OPEN_ID
	 * @return  the value of t_third_account.OPEN_ID
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_third_account.OPEN_ID
	 * @param openId  the value for t_third_account.OPEN_ID
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public void setOpenId(String openId) {
		this.openId = openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_third_account.ACCOUNT_NAME
	 * @return  the value of t_third_account.ACCOUNT_NAME
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public String getAccountName() {
		return accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_third_account.ACCOUNT_NAME
	 * @param accountName  the value for t_third_account.ACCOUNT_NAME
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_third_account.ACCOUNT_TYPE
	 * @return  the value of t_third_account.ACCOUNT_TYPE
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public String getAccountType() {
		return accountType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_third_account.ACCOUNT_TYPE
	 * @param accountType  the value for t_third_account.ACCOUNT_TYPE
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_third_account.PAM_ACCOUNT_ID
	 * @return  the value of t_third_account.PAM_ACCOUNT_ID
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public Integer getPamAccountId() {
		return pamAccountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_third_account.PAM_ACCOUNT_ID
	 * @param pamAccountId  the value for t_third_account.PAM_ACCOUNT_ID
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public void setPamAccountId(Integer pamAccountId) {
		this.pamAccountId = pamAccountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_third_account.ACCOUNT_STATUS
	 * @return  the value of t_third_account.ACCOUNT_STATUS
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public String getAccountStatus() {
		return accountStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_third_account.ACCOUNT_STATUS
	 * @param accountStatus  the value for t_third_account.ACCOUNT_STATUS
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public void setAccountStatus(String accountStatus) {
		this.accountStatus = accountStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_third_account.REG_IP
	 * @return  the value of t_third_account.REG_IP
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public String getRegIp() {
		return regIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_third_account.REG_IP
	 * @param regIp  the value for t_third_account.REG_IP
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public void setRegIp(String regIp) {
		this.regIp = regIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_third_account.REG_TIME
	 * @return  the value of t_third_account.REG_TIME
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public String getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_third_account.REG_TIME
	 * @param regTime  the value for t_third_account.REG_TIME
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public void setRegTime(String regTime) {
		this.regTime = regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_third_account.SOURCE
	 * @return  the value of t_third_account.SOURCE
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public String getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_third_account.SOURCE
	 * @param source  the value for t_third_account.SOURCE
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public void setSource(String source) {
		this.source = source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_third_account.LOGIN_COUNT
	 * @return  the value of t_third_account.LOGIN_COUNT
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public Integer getLoginCount() {
		return loginCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_third_account.LOGIN_COUNT
	 * @param loginCount  the value for t_third_account.LOGIN_COUNT
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public void setLoginCount(Integer loginCount) {
		this.loginCount = loginCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_third_account.LOGIN_IP
	 * @return  the value of t_third_account.LOGIN_IP
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public String getLoginIp() {
		return loginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_third_account.LOGIN_IP
	 * @param loginIp  the value for t_third_account.LOGIN_IP
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_third_account.CREATE_TIME
	 * @return  the value of t_third_account.CREATE_TIME
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")  
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_third_account.CREATE_TIME
	 * @param createTime  the value for t_third_account.CREATE_TIME
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_third_account.UPDATE_TIME
	 * @return  the value of t_third_account.UPDATE_TIME
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_third_account.UPDATE_TIME
	 * @param updateTime  the value for t_third_account.UPDATE_TIME
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getLoginPassword() {
		return loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_third_account
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", accountId=").append(accountId);
		sb.append(", openId=").append(openId);
		sb.append(", accountName=").append(accountName);
		sb.append(", accountType=").append(accountType);
		sb.append(", pamAccountId=").append(pamAccountId);
		sb.append(", accountStatus=").append(accountStatus);
		sb.append(", regIp=").append(regIp);
		sb.append(", regTime=").append(regTime);
		sb.append(", source=").append(source);
		sb.append(", loginCount=").append(loginCount);
		sb.append(", loginIp=").append(loginIp);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getYyAccountType() {
		return yyAccountType;
	}

	public void setYyAccountType(String yyAccountType) {
		this.yyAccountType = yyAccountType;
	}

	public boolean isFirstRegist() {
		return firstRegist;
	}

	public void setFirstRegist(boolean firstRegist) {
		this.firstRegist = firstRegist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_third_account
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ThirdAccount other = (ThirdAccount) that;
		return (this.getAccountId() == null ? other.getAccountId() == null : this.getAccountId().equals(
				other.getAccountId()))
				&& (this.getOpenId() == null ? other.getOpenId() == null : this.getOpenId().equals(other.getOpenId()))
				&& (this.getAccountName() == null ? other.getAccountName() == null : this.getAccountName().equals(
						other.getAccountName()))
				&& (this.getAccountType() == null ? other.getAccountType() == null : this.getAccountType().equals(
						other.getAccountType()))
				&& (this.getPamAccountId() == null ? other.getPamAccountId() == null : this.getPamAccountId().equals(
						other.getPamAccountId()))
				&& (this.getAccountStatus() == null ? other.getAccountStatus() == null : this.getAccountStatus()
						.equals(other.getAccountStatus()))
				&& (this.getRegIp() == null ? other.getRegIp() == null : this.getRegIp().equals(other.getRegIp()))
				&& (this.getRegTime() == null ? other.getRegTime() == null : this.getRegTime().equals(
						other.getRegTime()))
				&& (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
				&& (this.getLoginCount() == null ? other.getLoginCount() == null : this.getLoginCount().equals(
						other.getLoginCount()))
				&& (this.getLoginIp() == null ? other.getLoginIp() == null : this.getLoginIp().equals(
						other.getLoginIp()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(
						other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(
						other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_third_account
	 * @mbggenerated  Tue Jun 02 19:12:26 CST 2015
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getAccountId() == null) ? 0 : getAccountId().hashCode());
		result = prime * result + ((getOpenId() == null) ? 0 : getOpenId().hashCode());
		result = prime * result + ((getAccountName() == null) ? 0 : getAccountName().hashCode());
		result = prime * result + ((getAccountType() == null) ? 0 : getAccountType().hashCode());
		result = prime * result + ((getPamAccountId() == null) ? 0 : getPamAccountId().hashCode());
		result = prime * result + ((getAccountStatus() == null) ? 0 : getAccountStatus().hashCode());
		result = prime * result + ((getRegIp() == null) ? 0 : getRegIp().hashCode());
		result = prime * result + ((getRegTime() == null) ? 0 : getRegTime().hashCode());
		result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
		result = prime * result + ((getLoginCount() == null) ? 0 : getLoginCount().hashCode());
		result = prime * result + ((getLoginIp() == null) ? 0 : getLoginIp().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}
}