package com.cnit.yoyo.dao.activity;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cnit.yoyo.model.activity.Coupons;
import com.cnit.yoyo.model.activity.CouponsExample;
import com.cnit.yoyo.model.activity.dto.CouponsDTO;

public interface CouponsMapper {

	/**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupons
     * @mbggenerated  Tue Apr 21 13:20:16 CST 2015
     */
    int deleteByExample(CouponsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupons
     * @mbggenerated  Tue Apr 21 13:20:16 CST 2015
     */
    int deleteByPrimaryKey(Integer cpnsId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupons
     * @mbggenerated  Tue Apr 21 13:20:16 CST 2015
     */
    int insert(Coupons record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupons
     * @mbggenerated  Tue Apr 21 13:20:16 CST 2015
     */
    int insertSelective(Coupons record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupons
     * @mbggenerated  Tue Apr 21 13:20:16 CST 2015
     */
    List<Coupons> selectByExample(CouponsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupons
     * @mbggenerated  Tue Apr 21 13:20:16 CST 2015
     */
    Coupons selectByPrimaryKey(Integer cpnsId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupons
     * @mbggenerated  Tue Apr 21 13:20:16 CST 2015
     */
    int updateByExampleSelective(@Param("record") Coupons record, @Param("example") CouponsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupons
     * @mbggenerated  Tue Apr 21 13:20:16 CST 2015
     */
    int updateByExample(@Param("record") Coupons record, @Param("example") CouponsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupons
     * @mbggenerated  Tue Apr 21 13:20:16 CST 2015
     */
    int updateByPrimaryKeySelective(Coupons record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupons
     * @mbggenerated  Tue Apr 21 13:20:16 CST 2015
     */
    int updateByPrimaryKey(Coupons record);

    List<Coupons> selectCouponsList(CouponsDTO dto);
    CouponsDTO findById(Integer id);
}