package com.cnit.yoyo.dao.activity;

import com.cnit.yoyo.model.activity.SalesRuleGoods;
import com.cnit.yoyo.model.activity.SalesRuleGoodsExample;
import com.cnit.yoyo.model.activity.SalesRuleGoodsWithBLOBs;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesRuleGoodsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	int deleteByExample(SalesRuleGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	int deleteByPrimaryKey(Integer ruleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	int insert(SalesRuleGoodsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	int insertSelective(SalesRuleGoodsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	List<SalesRuleGoodsWithBLOBs> selectByExampleWithBLOBs(
			SalesRuleGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	List<SalesRuleGoods> selectByExample(SalesRuleGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	SalesRuleGoodsWithBLOBs selectByPrimaryKey(Integer ruleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	int updateByExampleSelective(
			@Param("record") SalesRuleGoodsWithBLOBs record,
			@Param("example") SalesRuleGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	int updateByExampleWithBLOBs(
			@Param("record") SalesRuleGoodsWithBLOBs record,
			@Param("example") SalesRuleGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	int updateByExample(@Param("record") SalesRuleGoods record,
			@Param("example") SalesRuleGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	int updateByPrimaryKeySelective(SalesRuleGoodsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(SalesRuleGoodsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sales_rule_goods
	 * @mbggenerated  Mon Apr 20 15:33:34 CST 2015
	 */
	int updateByPrimaryKey(SalesRuleGoods record);
}