package com.cnit.yoyo.model.spider;

import java.io.Serializable;

public class AutohomeCarAttr implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_autohome_car_attr.ID
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_autohome_car_attr.NAME
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_autohome_car_attr.VAL
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    private String val;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_autohome_car_attr.CAR_TYPE_ID
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    private String carTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_autohome_car_attr.PARENT_ORDER_INDEX
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    private Integer parentOrderIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_autohome_car_attr.CHILD_ORDER_INDEX
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    private Integer childOrderIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_autohome_car_attr.VAL_TYPE
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    private String valType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_autohome_car_attr
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_autohome_car_attr.ID
     *
     * @return the value of t_autohome_car_attr.ID
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_autohome_car_attr.ID
     *
     * @param id the value for t_autohome_car_attr.ID
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_autohome_car_attr.NAME
     *
     * @return the value of t_autohome_car_attr.NAME
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_autohome_car_attr.NAME
     *
     * @param name the value for t_autohome_car_attr.NAME
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_autohome_car_attr.VAL
     *
     * @return the value of t_autohome_car_attr.VAL
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_autohome_car_attr.VAL
     *
     * @param val the value for t_autohome_car_attr.VAL
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    public void setVal(String val) {
        this.val = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_autohome_car_attr.CAR_TYPE_ID
     *
     * @return the value of t_autohome_car_attr.CAR_TYPE_ID
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    public String getCarTypeId() {
        return carTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_autohome_car_attr.CAR_TYPE_ID
     *
     * @param carTypeId the value for t_autohome_car_attr.CAR_TYPE_ID
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    public void setCarTypeId(String carTypeId) {
        this.carTypeId = carTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_autohome_car_attr.PARENT_ORDER_INDEX
     *
     * @return the value of t_autohome_car_attr.PARENT_ORDER_INDEX
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    public Integer getParentOrderIndex() {
        return parentOrderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_autohome_car_attr.PARENT_ORDER_INDEX
     *
     * @param parentOrderIndex the value for t_autohome_car_attr.PARENT_ORDER_INDEX
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    public void setParentOrderIndex(Integer parentOrderIndex) {
        this.parentOrderIndex = parentOrderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_autohome_car_attr.CHILD_ORDER_INDEX
     *
     * @return the value of t_autohome_car_attr.CHILD_ORDER_INDEX
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    public Integer getChildOrderIndex() {
        return childOrderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_autohome_car_attr.CHILD_ORDER_INDEX
     *
     * @param childOrderIndex the value for t_autohome_car_attr.CHILD_ORDER_INDEX
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    public void setChildOrderIndex(Integer childOrderIndex) {
        this.childOrderIndex = childOrderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_autohome_car_attr.VAL_TYPE
     *
     * @return the value of t_autohome_car_attr.VAL_TYPE
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    public String getValType() {
        return valType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_autohome_car_attr.VAL_TYPE
     *
     * @param valType the value for t_autohome_car_attr.VAL_TYPE
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    public void setValType(String valType) {
        this.valType = valType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_autohome_car_attr
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", val=").append(val);
        sb.append(", carTypeId=").append(carTypeId);
        sb.append(", parentOrderIndex=").append(parentOrderIndex);
        sb.append(", childOrderIndex=").append(childOrderIndex);
        sb.append(", valType=").append(valType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_autohome_car_attr
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AutohomeCarAttr other = (AutohomeCarAttr) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getVal() == null ? other.getVal() == null : this.getVal().equals(other.getVal()))
            && (this.getCarTypeId() == null ? other.getCarTypeId() == null : this.getCarTypeId().equals(other.getCarTypeId()))
            && (this.getParentOrderIndex() == null ? other.getParentOrderIndex() == null : this.getParentOrderIndex().equals(other.getParentOrderIndex()))
            && (this.getChildOrderIndex() == null ? other.getChildOrderIndex() == null : this.getChildOrderIndex().equals(other.getChildOrderIndex()))
            && (this.getValType() == null ? other.getValType() == null : this.getValType().equals(other.getValType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_autohome_car_attr
     *
     * @mbggenerated Thu Aug 06 11:17:30 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getVal() == null) ? 0 : getVal().hashCode());
        result = prime * result + ((getCarTypeId() == null) ? 0 : getCarTypeId().hashCode());
        result = prime * result + ((getParentOrderIndex() == null) ? 0 : getParentOrderIndex().hashCode());
        result = prime * result + ((getChildOrderIndex() == null) ? 0 : getChildOrderIndex().hashCode());
        result = prime * result + ((getValType() == null) ? 0 : getValType().hashCode());
        return result;
    }
}