package com.cnit.yoyo.dao.requirement;

import java.util.List;

import com.cnit.yoyo.model.requirement.Requirement;

public interface RequirementMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_requirement
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_requirement
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	int insert(Requirement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_requirement
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	int insertSelective(Requirement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_requirement
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	Requirement selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_requirement
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	int updateByPrimaryKeySelective(Requirement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_requirement
	 * @mbggenerated  Mon Jun 15 18:34:07 CST 2015
	 */
	int updateByPrimaryKey(Requirement record);
	
	List<Requirement> selectAll();
}