package com.cnit.yoyo.model.painting;

import java.io.Serializable;
import java.util.Date;

public class CarDamageDetail implements Serializable {

    private CarPart carPart;

    public CarPart getCarPart() {
        return carPart;
    }

    public void setCarPart(CarPart carPart) {
        this.carPart = carPart;
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_car_damage_detail.id
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_car_damage_detail.car_part_id
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    private Integer carPartId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_car_damage_detail.car_damage_id
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    private Integer carDamageId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_car_damage_detail.disabled
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    private Boolean disabled;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_car_damage_detail.pic
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    private String pic;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_car_damage_detail.createtime
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    private Date createtime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_car_damage_detail.remark
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    private String remark;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_car_damage_detail
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_car_damage_detail.id
     * @return  the value of t_car_damage_detail.id
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_car_damage_detail.id
     * @param id  the value for t_car_damage_detail.id
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_car_damage_detail.car_part_id
     * @return  the value of t_car_damage_detail.car_part_id
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    public Integer getCarPartId() {
        return carPartId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_car_damage_detail.car_part_id
     * @param carPartId  the value for t_car_damage_detail.car_part_id
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    public void setCarPartId(Integer carPartId) {
        this.carPartId = carPartId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_car_damage_detail.car_damage_id
     * @return  the value of t_car_damage_detail.car_damage_id
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    public Integer getCarDamageId() {
        return carDamageId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_car_damage_detail.car_damage_id
     * @param carDamageId  the value for t_car_damage_detail.car_damage_id
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    public void setCarDamageId(Integer carDamageId) {
        this.carDamageId = carDamageId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_car_damage_detail.disabled
     * @return  the value of t_car_damage_detail.disabled
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_car_damage_detail.disabled
     * @param disabled  the value for t_car_damage_detail.disabled
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_car_damage_detail.pic
     * @return  the value of t_car_damage_detail.pic
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_car_damage_detail.pic
     * @param pic  the value for t_car_damage_detail.pic
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_car_damage_detail.createtime
     * @return  the value of t_car_damage_detail.createtime
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_car_damage_detail.createtime
     * @param createtime  the value for t_car_damage_detail.createtime
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_car_damage_detail.remark
     * @return  the value of t_car_damage_detail.remark
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_car_damage_detail.remark
     * @param remark  the value for t_car_damage_detail.remark
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_car_damage_detail
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", carPartId=").append(carPartId);
        sb.append(", carDamageId=").append(carDamageId);
        sb.append(", disabled=").append(disabled);
        sb.append(", pic=").append(pic);
        sb.append(", createtime=").append(createtime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_car_damage_detail
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CarDamageDetail other = (CarDamageDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getCarPartId() == null ? other.getCarPartId() == null : this.getCarPartId().equals(other.getCarPartId()))
                && (this.getCarDamageId() == null ? other.getCarDamageId() == null : this.getCarDamageId().equals(other.getCarDamageId()))
                && (this.getDisabled() == null ? other.getDisabled() == null : this.getDisabled().equals(other.getDisabled()))
                && (this.getPic() == null ? other.getPic() == null : this.getPic().equals(other.getPic()))
                && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
                && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_car_damage_detail
     * @mbggenerated  Mon May 11 18:58:49 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCarPartId() == null) ? 0 : getCarPartId().hashCode());
        result = prime * result + ((getCarDamageId() == null) ? 0 : getCarDamageId().hashCode());
        result = prime * result + ((getDisabled() == null) ? 0 : getDisabled().hashCode());
        result = prime * result + ((getPic() == null) ? 0 : getPic().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}