package com.cnit.yoyo.dao.news;

import java.util.List;

import com.cnit.yoyo.model.news.News;
import com.cnit.yoyo.model.news.dto.NewsQueryDto;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_index
     *
     * @mbggenerated Mon Aug 17 15:10:52 CST 2015
     */
    int deleteByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_index
     *
     * @mbggenerated Mon Aug 17 15:10:52 CST 2015
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_index
     *
     * @mbggenerated Mon Aug 17 15:10:52 CST 2015
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_index
     *
     * @mbggenerated Mon Aug 17 15:10:52 CST 2015
     */
    News selectByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_index
     *
     * @mbggenerated Mon Aug 17 15:10:52 CST 2015
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_index
     *
     * @mbggenerated Mon Aug 17 15:10:52 CST 2015
     */
    int updateByPrimaryKey(News record);
    
    List<News> selectByQuery(NewsQueryDto dto);
    
    int deleteBatch(List<Integer> ids);
    
    List<News> selectIndexList(Integer number);
}