package com.cnit.yoyo.dao.trade;

import java.util.List;
import java.util.Map;

import com.cnit.yoyo.model.trade.AftersalesReturnProductWithBLOBs;
import com.cnit.yoyo.model.trade.dto.AfterSalesQryDTO;
import com.cnit.yoyo.model.trade.dto.RefundsProductDTO;
import com.cnit.yoyo.model.trade.dto.ReturnProductDTO;
import com.cnit.yoyo.reship.model.AftersalesReturnProduct;

public interface AftersalesReturnProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_aftersales_return_product
	 * @mbggenerated  Sat Apr 18 17:01:00 CST 2015
	 */
	int deleteByPrimaryKey(Long returnId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_aftersales_return_product
	 * @mbggenerated  Sat Apr 18 17:01:00 CST 2015
	 */
	int insert(AftersalesReturnProductWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_aftersales_return_product
	 * @mbggenerated  Sat Apr 18 17:01:00 CST 2015
	 */
	int insertSelective(AftersalesReturnProductWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_aftersales_return_product
	 * @mbggenerated  Sat Apr 18 17:01:00 CST 2015
	 */
	AftersalesReturnProductWithBLOBs selectByPrimaryKey(Long returnId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_aftersales_return_product
	 * @mbggenerated  Sat Apr 18 17:01:00 CST 2015
	 */
	int updateByPrimaryKeySelective(AftersalesReturnProductWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_aftersales_return_product
	 * @mbggenerated  Sat Apr 18 17:01:00 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(AftersalesReturnProductWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_aftersales_return_product
	 * @mbggenerated  Sat Apr 18 17:01:00 CST 2015
	 */
	int updateByPrimaryKey(AftersalesReturnProduct record);
	
	List<ReturnProductDTO> selectReturnProductInfo(Map<String, Object> map);
	
	List<ReturnProductDTO> selectOverdueReturnProductInfo();
	
	RefundsProductDTO selectReturnProductById(Long returnId);
	
	RefundsProductDTO selectRefundsProductById(Map<String, Object> params);
	
	List<ReturnProductDTO> selectAfterSalesAppeal(AfterSalesQryDTO qryDTO);
	
	List<RefundsProductDTO> selectNeedRefundsList(AfterSalesQryDTO qryDTO);
}