package com.cnit.yoyo.dao.trade;

import com.cnit.yoyo.model.trade.Reship;
import com.cnit.yoyo.model.trade.ReshipWithBLOBs;
import com.cnit.yoyo.model.trade.dto.ReshipDTO;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ReshipMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reship
     *
     * @mbggenerated Thu Apr 16 14:01:33 CST 2015
     */
    int deleteByPrimaryKey(Long reshipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reship
     *
     * @mbggenerated Thu Apr 16 14:01:33 CST 2015
     */
    int insert(ReshipWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reship
     *
     * @mbggenerated Thu Apr 16 14:01:33 CST 2015
     */
    int insertSelective(ReshipWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reship
     *
     * @mbggenerated Thu Apr 16 14:01:33 CST 2015
     */
    ReshipWithBLOBs selectByPrimaryKey(Long reshipId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reship
     *
     * @mbggenerated Thu Apr 16 14:01:33 CST 2015
     */
    int updateByPrimaryKeySelective(ReshipWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reship
     *
     * @mbggenerated Thu Apr 16 14:01:33 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(ReshipWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reship
     *
     * @mbggenerated Thu Apr 16 14:01:33 CST 2015
     */
    int updateByPrimaryKey(Reship record);
    
    List<Reship> selectReshipInfo(Map<String, Object> params);
    
    ReshipDTO selectReshipById(Long reshipId);
    
    int updateReshipStatus(ReshipDTO reshipDTO);
}